// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: graph/substreams/data_service/sds/session/v1/session.proto

package sessionv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/sds/session/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SessionServiceName is the fully-qualified name of the SessionService service.
	SessionServiceName = "graph.substreams.data_service.sds.session.v1.SessionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SessionServiceBorrowWorkerProcedure is the fully-qualified name of the SessionService's
	// BorrowWorker RPC.
	SessionServiceBorrowWorkerProcedure = "/graph.substreams.data_service.sds.session.v1.SessionService/BorrowWorker"
	// SessionServiceReturnWorkerProcedure is the fully-qualified name of the SessionService's
	// ReturnWorker RPC.
	SessionServiceReturnWorkerProcedure = "/graph.substreams.data_service.sds.session.v1.SessionService/ReturnWorker"
	// SessionServiceKeepAliveProcedure is the fully-qualified name of the SessionService's KeepAlive
	// RPC.
	SessionServiceKeepAliveProcedure = "/graph.substreams.data_service.sds.session.v1.SessionService/KeepAlive"
)

// SessionServiceClient is a client for the
// graph.substreams.data_service.sds.session.v1.SessionService service.
type SessionServiceClient interface {
	// BorrowWorker acquires a worker slot for a new streaming request.
	// Returns resource_exhausted if quota is exceeded.
	BorrowWorker(context.Context, *connect.Request[v1.BorrowWorkerRequest]) (*connect.Response[v1.BorrowWorkerResponse], error)
	// ReturnWorker releases a previously borrowed worker slot.
	ReturnWorker(context.Context, *connect.Request[v1.ReturnWorkerRequest]) (*connect.Response[v1.ReturnWorkerResponse], error)
	// KeepAlive refreshes the session's last-seen timestamp.
	KeepAlive(context.Context, *connect.Request[v1.KeepAliveRequest]) (*connect.Response[v1.KeepAliveResponse], error)
}

// NewSessionServiceClient constructs a client for the
// graph.substreams.data_service.sds.session.v1.SessionService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSessionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SessionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sessionServiceMethods := v1.File_graph_substreams_data_service_sds_session_v1_session_proto.Services().ByName("SessionService").Methods()
	return &sessionServiceClient{
		borrowWorker: connect.NewClient[v1.BorrowWorkerRequest, v1.BorrowWorkerResponse](
			httpClient,
			baseURL+SessionServiceBorrowWorkerProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("BorrowWorker")),
			connect.WithClientOptions(opts...),
		),
		returnWorker: connect.NewClient[v1.ReturnWorkerRequest, v1.ReturnWorkerResponse](
			httpClient,
			baseURL+SessionServiceReturnWorkerProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("ReturnWorker")),
			connect.WithClientOptions(opts...),
		),
		keepAlive: connect.NewClient[v1.KeepAliveRequest, v1.KeepAliveResponse](
			httpClient,
			baseURL+SessionServiceKeepAliveProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("KeepAlive")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sessionServiceClient implements SessionServiceClient.
type sessionServiceClient struct {
	borrowWorker *connect.Client[v1.BorrowWorkerRequest, v1.BorrowWorkerResponse]
	returnWorker *connect.Client[v1.ReturnWorkerRequest, v1.ReturnWorkerResponse]
	keepAlive    *connect.Client[v1.KeepAliveRequest, v1.KeepAliveResponse]
}

// BorrowWorker calls graph.substreams.data_service.sds.session.v1.SessionService.BorrowWorker.
func (c *sessionServiceClient) BorrowWorker(ctx context.Context, req *connect.Request[v1.BorrowWorkerRequest]) (*connect.Response[v1.BorrowWorkerResponse], error) {
	return c.borrowWorker.CallUnary(ctx, req)
}

// ReturnWorker calls graph.substreams.data_service.sds.session.v1.SessionService.ReturnWorker.
func (c *sessionServiceClient) ReturnWorker(ctx context.Context, req *connect.Request[v1.ReturnWorkerRequest]) (*connect.Response[v1.ReturnWorkerResponse], error) {
	return c.returnWorker.CallUnary(ctx, req)
}

// KeepAlive calls graph.substreams.data_service.sds.session.v1.SessionService.KeepAlive.
func (c *sessionServiceClient) KeepAlive(ctx context.Context, req *connect.Request[v1.KeepAliveRequest]) (*connect.Response[v1.KeepAliveResponse], error) {
	return c.keepAlive.CallUnary(ctx, req)
}

// SessionServiceHandler is an implementation of the
// graph.substreams.data_service.sds.session.v1.SessionService service.
type SessionServiceHandler interface {
	// BorrowWorker acquires a worker slot for a new streaming request.
	// Returns resource_exhausted if quota is exceeded.
	BorrowWorker(context.Context, *connect.Request[v1.BorrowWorkerRequest]) (*connect.Response[v1.BorrowWorkerResponse], error)
	// ReturnWorker releases a previously borrowed worker slot.
	ReturnWorker(context.Context, *connect.Request[v1.ReturnWorkerRequest]) (*connect.Response[v1.ReturnWorkerResponse], error)
	// KeepAlive refreshes the session's last-seen timestamp.
	KeepAlive(context.Context, *connect.Request[v1.KeepAliveRequest]) (*connect.Response[v1.KeepAliveResponse], error)
}

// NewSessionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSessionServiceHandler(svc SessionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sessionServiceMethods := v1.File_graph_substreams_data_service_sds_session_v1_session_proto.Services().ByName("SessionService").Methods()
	sessionServiceBorrowWorkerHandler := connect.NewUnaryHandler(
		SessionServiceBorrowWorkerProcedure,
		svc.BorrowWorker,
		connect.WithSchema(sessionServiceMethods.ByName("BorrowWorker")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceReturnWorkerHandler := connect.NewUnaryHandler(
		SessionServiceReturnWorkerProcedure,
		svc.ReturnWorker,
		connect.WithSchema(sessionServiceMethods.ByName("ReturnWorker")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceKeepAliveHandler := connect.NewUnaryHandler(
		SessionServiceKeepAliveProcedure,
		svc.KeepAlive,
		connect.WithSchema(sessionServiceMethods.ByName("KeepAlive")),
		connect.WithHandlerOptions(opts...),
	)
	return "/graph.substreams.data_service.sds.session.v1.SessionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SessionServiceBorrowWorkerProcedure:
			sessionServiceBorrowWorkerHandler.ServeHTTP(w, r)
		case SessionServiceReturnWorkerProcedure:
			sessionServiceReturnWorkerHandler.ServeHTTP(w, r)
		case SessionServiceKeepAliveProcedure:
			sessionServiceKeepAliveHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSessionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSessionServiceHandler struct{}

func (UnimplementedSessionServiceHandler) BorrowWorker(context.Context, *connect.Request[v1.BorrowWorkerRequest]) (*connect.Response[v1.BorrowWorkerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.sds.session.v1.SessionService.BorrowWorker is not implemented"))
}

func (UnimplementedSessionServiceHandler) ReturnWorker(context.Context, *connect.Request[v1.ReturnWorkerRequest]) (*connect.Response[v1.ReturnWorkerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.sds.session.v1.SessionService.ReturnWorker is not implemented"))
}

func (UnimplementedSessionServiceHandler) KeepAlive(context.Context, *connect.Request[v1.KeepAliveRequest]) (*connect.Response[v1.KeepAliveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.sds.session.v1.SessionService.KeepAlive is not implemented"))
}
