// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: graph/substreams/data_service/common/v1/types.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EndReason indicates why a session ended.
type EndReason int32

const (
	EndReason_END_REASON_UNSPECIFIED EndReason = 0
	// Normal completion
	EndReason_END_REASON_COMPLETE EndReason = 1
	// Client disconnected
	EndReason_END_REASON_CLIENT_DISCONNECT EndReason = 2
	// Provider initiated stop
	EndReason_END_REASON_PROVIDER_STOP EndReason = 3
	// Error occurred
	EndReason_END_REASON_ERROR EndReason = 4
	// Payment issue
	EndReason_END_REASON_PAYMENT_ISSUE EndReason = 5
)

// Enum value maps for EndReason.
var (
	EndReason_name = map[int32]string{
		0: "END_REASON_UNSPECIFIED",
		1: "END_REASON_COMPLETE",
		2: "END_REASON_CLIENT_DISCONNECT",
		3: "END_REASON_PROVIDER_STOP",
		4: "END_REASON_ERROR",
		5: "END_REASON_PAYMENT_ISSUE",
	}
	EndReason_value = map[string]int32{
		"END_REASON_UNSPECIFIED":       0,
		"END_REASON_COMPLETE":          1,
		"END_REASON_CLIENT_DISCONNECT": 2,
		"END_REASON_PROVIDER_STOP":     3,
		"END_REASON_ERROR":             4,
		"END_REASON_PAYMENT_ISSUE":     5,
	}
)

func (x EndReason) Enum() *EndReason {
	p := new(EndReason)
	*p = x
	return p
}

func (x EndReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndReason) Descriptor() protoreflect.EnumDescriptor {
	return file_graph_substreams_data_service_common_v1_types_proto_enumTypes[0].Descriptor()
}

func (EndReason) Type() protoreflect.EnumType {
	return &file_graph_substreams_data_service_common_v1_types_proto_enumTypes[0]
}

func (x EndReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndReason.Descriptor instead.
func (EndReason) EnumDescriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_common_v1_types_proto_rawDescGZIP(), []int{0}
}

// Address represents an Ethereum address (20 bytes).
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bytes         []byte                 `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_graph_substreams_data_service_common_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_common_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_common_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

// BigInt represents an arbitrary precision integer as big-endian bytes.
type BigInt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bytes         []byte                 `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BigInt) Reset() {
	*x = BigInt{}
	mi := &file_graph_substreams_data_service_common_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BigInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BigInt) ProtoMessage() {}

func (x *BigInt) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_common_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BigInt.ProtoReflect.Descriptor instead.
func (*BigInt) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_common_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *BigInt) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

// GRT represents a GRT token amount in base units (18 decimals).
// 1 GRT = 10^18 base units.
// Stored as big-endian bytes, same encoding as BigInt.
type GRT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bytes         []byte                 `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GRT) Reset() {
	*x = GRT{}
	mi := &file_graph_substreams_data_service_common_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GRT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRT) ProtoMessage() {}

func (x *GRT) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_common_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRT.ProtoReflect.Descriptor instead.
func (*GRT) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_common_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *GRT) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

// PricingConfig defines the pricing for a data service.
// Used to communicate pricing from provider to consumer at session start.
type PricingConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Price per block processed in GRT
	PricePerBlock *GRT `protobuf:"bytes,1,opt,name=price_per_block,json=pricePerBlock,proto3" json:"price_per_block,omitempty"`
	// Price per byte transferred in GRT
	PricePerByte  *GRT `protobuf:"bytes,2,opt,name=price_per_byte,json=pricePerByte,proto3" json:"price_per_byte,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PricingConfig) Reset() {
	*x = PricingConfig{}
	mi := &file_graph_substreams_data_service_common_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricingConfig) ProtoMessage() {}

func (x *PricingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_common_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricingConfig.ProtoReflect.Descriptor instead.
func (*PricingConfig) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_common_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *PricingConfig) GetPricePerBlock() *GRT {
	if x != nil {
		return x.PricePerBlock
	}
	return nil
}

func (x *PricingConfig) GetPricePerByte() *GRT {
	if x != nil {
		return x.PricePerByte
	}
	return nil
}

// SignedRAV represents a signed Receipt Aggregate Voucher.
// This is the core payment primitive - a signed commitment to pay for usage.
type SignedRAV struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The RAV data that was signed
	Rav *RAV `protobuf:"bytes,1,opt,name=rav,proto3" json:"rav,omitempty"`
	// The signature over the RAV (EIP-712 typed data signature), 65 bytes.
	//
	// Canonical encoding for RPC/headers: V (1 byte) + R (32 bytes) + S (32 bytes),
	// matching `eth.Signature` from `github.com/streamingfast/eth-go`.
	//
	// Solidity's `ECDSA.recover` expects R (32) + S (32) + V (1) ("R+S+V"); convert
	// at the Solidity boundary (e.g. on-chain collection calldata encoding).
	Signature     []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedRAV) Reset() {
	*x = SignedRAV{}
	mi := &file_graph_substreams_data_service_common_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedRAV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedRAV) ProtoMessage() {}

func (x *SignedRAV) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_common_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedRAV.ProtoReflect.Descriptor instead.
func (*SignedRAV) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_common_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *SignedRAV) GetRav() *RAV {
	if x != nil {
		return x.Rav
	}
	return nil
}

func (x *SignedRAV) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// RAV (Receipt Aggregate Voucher) represents accumulated usage that the payer
// commits to pay. RAVs are aggregated over time and only the latest RAV
// needs to be submitted on-chain for payment collection.
type RAV struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The collection identifier (32 bytes). This is part of the EIP-712 signed payload.
	CollectionId []byte `protobuf:"bytes,7,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	// The payer's address (who is paying for the service)
	Payer *Address `protobuf:"bytes,1,opt,name=payer,proto3" json:"payer,omitempty"`
	// The data service contract address
	DataService *Address `protobuf:"bytes,2,opt,name=data_service,json=dataService,proto3" json:"data_service,omitempty"`
	// The service provider's address (who is providing the service)
	ServiceProvider *Address `protobuf:"bytes,3,opt,name=service_provider,json=serviceProvider,proto3" json:"service_provider,omitempty"`
	// Timestamp when this RAV was created (Unix nanoseconds)
	TimestampNs uint64 `protobuf:"varint,4,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	// Total value in GRT accumulated in this RAV
	ValueAggregate *GRT `protobuf:"bytes,5,opt,name=value_aggregate,json=valueAggregate,proto3" json:"value_aggregate,omitempty"`
	// Arbitrary metadata (e.g., request CID)
	Metadata      []byte `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAV) Reset() {
	*x = RAV{}
	mi := &file_graph_substreams_data_service_common_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAV) ProtoMessage() {}

func (x *RAV) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_common_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAV.ProtoReflect.Descriptor instead.
func (*RAV) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_common_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *RAV) GetCollectionId() []byte {
	if x != nil {
		return x.CollectionId
	}
	return nil
}

func (x *RAV) GetPayer() *Address {
	if x != nil {
		return x.Payer
	}
	return nil
}

func (x *RAV) GetDataService() *Address {
	if x != nil {
		return x.DataService
	}
	return nil
}

func (x *RAV) GetServiceProvider() *Address {
	if x != nil {
		return x.ServiceProvider
	}
	return nil
}

func (x *RAV) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *RAV) GetValueAggregate() *GRT {
	if x != nil {
		return x.ValueAggregate
	}
	return nil
}

func (x *RAV) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Usage represents metered usage during a session.
type Usage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of blocks processed
	BlocksProcessed uint64 `protobuf:"varint,1,opt,name=blocks_processed,json=blocksProcessed,proto3" json:"blocks_processed,omitempty"`
	// Number of bytes transferred
	BytesTransferred uint64 `protobuf:"varint,2,opt,name=bytes_transferred,json=bytesTransferred,proto3" json:"bytes_transferred,omitempty"`
	// Number of requests made
	Requests uint64 `protobuf:"varint,3,opt,name=requests,proto3" json:"requests,omitempty"`
	// Computed cost in GRT for this usage
	Cost          *GRT `protobuf:"bytes,4,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_graph_substreams_data_service_common_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_common_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_common_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *Usage) GetBlocksProcessed() uint64 {
	if x != nil {
		return x.BlocksProcessed
	}
	return 0
}

func (x *Usage) GetBytesTransferred() uint64 {
	if x != nil {
		return x.BytesTransferred
	}
	return 0
}

func (x *Usage) GetRequests() uint64 {
	if x != nil {
		return x.Requests
	}
	return 0
}

func (x *Usage) GetCost() *GRT {
	if x != nil {
		return x.Cost
	}
	return nil
}

// EscrowAccount identifies an escrow deposit that funds payments.
type EscrowAccount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The payer's address
	Payer *Address `protobuf:"bytes,1,opt,name=payer,proto3" json:"payer,omitempty"`
	// The receiver's address (service provider)
	Receiver *Address `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	// The data service contract address
	DataService   *Address `protobuf:"bytes,3,opt,name=data_service,json=dataService,proto3" json:"data_service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EscrowAccount) Reset() {
	*x = EscrowAccount{}
	mi := &file_graph_substreams_data_service_common_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscrowAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscrowAccount) ProtoMessage() {}

func (x *EscrowAccount) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_common_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscrowAccount.ProtoReflect.Descriptor instead.
func (*EscrowAccount) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_common_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *EscrowAccount) GetPayer() *Address {
	if x != nil {
		return x.Payer
	}
	return nil
}

func (x *EscrowAccount) GetReceiver() *Address {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *EscrowAccount) GetDataService() *Address {
	if x != nil {
		return x.DataService
	}
	return nil
}

// SessionInfo contains information about an active payment session.
type SessionInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique session identifier
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// The escrow account funding this session
	EscrowAccount *EscrowAccount `protobuf:"bytes,2,opt,name=escrow_account,json=escrowAccount,proto3" json:"escrow_account,omitempty"`
	// The current RAV for this session
	CurrentRav *SignedRAV `protobuf:"bytes,3,opt,name=current_rav,json=currentRav,proto3" json:"current_rav,omitempty"`
	// Accumulated usage in this session
	AccumulatedUsage *Usage `protobuf:"bytes,4,opt,name=accumulated_usage,json=accumulatedUsage,proto3" json:"accumulated_usage,omitempty"`
	// Pricing configuration for this session (set by provider)
	PricingConfig *PricingConfig `protobuf:"bytes,5,opt,name=pricing_config,json=pricingConfig,proto3" json:"pricing_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_graph_substreams_data_service_common_v1_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_common_v1_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_common_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetEscrowAccount() *EscrowAccount {
	if x != nil {
		return x.EscrowAccount
	}
	return nil
}

func (x *SessionInfo) GetCurrentRav() *SignedRAV {
	if x != nil {
		return x.CurrentRav
	}
	return nil
}

func (x *SessionInfo) GetAccumulatedUsage() *Usage {
	if x != nil {
		return x.AccumulatedUsage
	}
	return nil
}

func (x *SessionInfo) GetPricingConfig() *PricingConfig {
	if x != nil {
		return x.PricingConfig
	}
	return nil
}

// ServiceParameters defines pricing and requirements for a service.
type ServiceParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Minimum blocks that need to be preprocessed before streaming
	RequiredBlocksPreproc uint64 `protobuf:"varint,1,opt,name=required_blocks_preproc,json=requiredBlocksPreproc,proto3" json:"required_blocks_preproc,omitempty"`
	// Estimated bytes per block
	EstimatedBytesPerBlock uint64 `protobuf:"varint,2,opt,name=estimated_bytes_per_block,json=estimatedBytesPerBlock,proto3" json:"estimated_bytes_per_block,omitempty"`
	// Price per block in GRT
	PricePerBlock *GRT `protobuf:"bytes,3,opt,name=price_per_block,json=pricePerBlock,proto3" json:"price_per_block,omitempty"`
	// Price per byte in GRT
	PricePerByte  *GRT `protobuf:"bytes,4,opt,name=price_per_byte,json=pricePerByte,proto3" json:"price_per_byte,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceParameters) Reset() {
	*x = ServiceParameters{}
	mi := &file_graph_substreams_data_service_common_v1_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceParameters) ProtoMessage() {}

func (x *ServiceParameters) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_common_v1_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceParameters.ProtoReflect.Descriptor instead.
func (*ServiceParameters) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_common_v1_types_proto_rawDescGZIP(), []int{9}
}

func (x *ServiceParameters) GetRequiredBlocksPreproc() uint64 {
	if x != nil {
		return x.RequiredBlocksPreproc
	}
	return 0
}

func (x *ServiceParameters) GetEstimatedBytesPerBlock() uint64 {
	if x != nil {
		return x.EstimatedBytesPerBlock
	}
	return 0
}

func (x *ServiceParameters) GetPricePerBlock() *GRT {
	if x != nil {
		return x.PricePerBlock
	}
	return nil
}

func (x *ServiceParameters) GetPricePerByte() *GRT {
	if x != nil {
		return x.PricePerByte
	}
	return nil
}

// PaymentStatus represents the current payment state of a session.
type PaymentStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current RAV value in GRT
	CurrentRavValue *GRT `protobuf:"bytes,1,opt,name=current_rav_value,json=currentRavValue,proto3" json:"current_rav_value,omitempty"`
	// Accumulated usage value in GRT
	AccumulatedUsageValue *GRT `protobuf:"bytes,2,opt,name=accumulated_usage_value,json=accumulatedUsageValue,proto3" json:"accumulated_usage_value,omitempty"`
	// Available escrow balance in GRT
	EscrowBalance *GRT `protobuf:"bytes,3,opt,name=escrow_balance,json=escrowBalance,proto3" json:"escrow_balance,omitempty"`
	// Whether funds are sufficient
	FundsSufficient bool `protobuf:"varint,4,opt,name=funds_sufficient,json=fundsSufficient,proto3" json:"funds_sufficient,omitempty"`
	// Estimated blocks remaining at current rate
	EstimatedBlocksRemaining uint64 `protobuf:"varint,5,opt,name=estimated_blocks_remaining,json=estimatedBlocksRemaining,proto3" json:"estimated_blocks_remaining,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *PaymentStatus) Reset() {
	*x = PaymentStatus{}
	mi := &file_graph_substreams_data_service_common_v1_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentStatus) ProtoMessage() {}

func (x *PaymentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_common_v1_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentStatus.ProtoReflect.Descriptor instead.
func (*PaymentStatus) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_common_v1_types_proto_rawDescGZIP(), []int{10}
}

func (x *PaymentStatus) GetCurrentRavValue() *GRT {
	if x != nil {
		return x.CurrentRavValue
	}
	return nil
}

func (x *PaymentStatus) GetAccumulatedUsageValue() *GRT {
	if x != nil {
		return x.AccumulatedUsageValue
	}
	return nil
}

func (x *PaymentStatus) GetEscrowBalance() *GRT {
	if x != nil {
		return x.EscrowBalance
	}
	return nil
}

func (x *PaymentStatus) GetFundsSufficient() bool {
	if x != nil {
		return x.FundsSufficient
	}
	return false
}

func (x *PaymentStatus) GetEstimatedBlocksRemaining() uint64 {
	if x != nil {
		return x.EstimatedBlocksRemaining
	}
	return 0
}

var File_graph_substreams_data_service_common_v1_types_proto protoreflect.FileDescriptor

const file_graph_substreams_data_service_common_v1_types_proto_rawDesc = "" +
	"\n" +
	"3graph/substreams/data_service/common/v1/types.proto\x12'graph.substreams.data_service.common.v1\"\x1f\n" +
	"\aAddress\x12\x14\n" +
	"\x05bytes\x18\x01 \x01(\fR\x05bytes\"\x1e\n" +
	"\x06BigInt\x12\x14\n" +
	"\x05bytes\x18\x01 \x01(\fR\x05bytes\"\x1b\n" +
	"\x03GRT\x12\x14\n" +
	"\x05bytes\x18\x01 \x01(\fR\x05bytes\"\xb9\x01\n" +
	"\rPricingConfig\x12T\n" +
	"\x0fprice_per_block\x18\x01 \x01(\v2,.graph.substreams.data_service.common.v1.GRTR\rpricePerBlock\x12R\n" +
	"\x0eprice_per_byte\x18\x02 \x01(\v2,.graph.substreams.data_service.common.v1.GRTR\fpricePerByte\"i\n" +
	"\tSignedRAV\x12>\n" +
	"\x03rav\x18\x01 \x01(\v2,.graph.substreams.data_service.common.v1.RAVR\x03rav\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xba\x03\n" +
	"\x03RAV\x12#\n" +
	"\rcollection_id\x18\a \x01(\fR\fcollectionId\x12F\n" +
	"\x05payer\x18\x01 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\x05payer\x12S\n" +
	"\fdata_service\x18\x02 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\vdataService\x12[\n" +
	"\x10service_provider\x18\x03 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\x0fserviceProvider\x12!\n" +
	"\ftimestamp_ns\x18\x04 \x01(\x04R\vtimestampNs\x12U\n" +
	"\x0fvalue_aggregate\x18\x05 \x01(\v2,.graph.substreams.data_service.common.v1.GRTR\x0evalueAggregate\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\fR\bmetadata\"\xbd\x01\n" +
	"\x05Usage\x12)\n" +
	"\x10blocks_processed\x18\x01 \x01(\x04R\x0fblocksProcessed\x12+\n" +
	"\x11bytes_transferred\x18\x02 \x01(\x04R\x10bytesTransferred\x12\x1a\n" +
	"\brequests\x18\x03 \x01(\x04R\brequests\x12@\n" +
	"\x04cost\x18\x04 \x01(\v2,.graph.substreams.data_service.common.v1.GRTR\x04cost\"\xfa\x01\n" +
	"\rEscrowAccount\x12F\n" +
	"\x05payer\x18\x01 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\x05payer\x12L\n" +
	"\breceiver\x18\x02 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\breceiver\x12S\n" +
	"\fdata_service\x18\x03 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\vdataService\"\x9c\x03\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12]\n" +
	"\x0eescrow_account\x18\x02 \x01(\v26.graph.substreams.data_service.common.v1.EscrowAccountR\rescrowAccount\x12S\n" +
	"\vcurrent_rav\x18\x03 \x01(\v22.graph.substreams.data_service.common.v1.SignedRAVR\n" +
	"currentRav\x12[\n" +
	"\x11accumulated_usage\x18\x04 \x01(\v2..graph.substreams.data_service.common.v1.UsageR\x10accumulatedUsage\x12]\n" +
	"\x0epricing_config\x18\x05 \x01(\v26.graph.substreams.data_service.common.v1.PricingConfigR\rpricingConfig\"\xb0\x02\n" +
	"\x11ServiceParameters\x126\n" +
	"\x17required_blocks_preproc\x18\x01 \x01(\x04R\x15requiredBlocksPreproc\x129\n" +
	"\x19estimated_bytes_per_block\x18\x02 \x01(\x04R\x16estimatedBytesPerBlock\x12T\n" +
	"\x0fprice_per_block\x18\x03 \x01(\v2,.graph.substreams.data_service.common.v1.GRTR\rpricePerBlock\x12R\n" +
	"\x0eprice_per_byte\x18\x04 \x01(\v2,.graph.substreams.data_service.common.v1.GRTR\fpricePerByte\"\x8d\x03\n" +
	"\rPaymentStatus\x12X\n" +
	"\x11current_rav_value\x18\x01 \x01(\v2,.graph.substreams.data_service.common.v1.GRTR\x0fcurrentRavValue\x12d\n" +
	"\x17accumulated_usage_value\x18\x02 \x01(\v2,.graph.substreams.data_service.common.v1.GRTR\x15accumulatedUsageValue\x12S\n" +
	"\x0eescrow_balance\x18\x03 \x01(\v2,.graph.substreams.data_service.common.v1.GRTR\rescrowBalance\x12)\n" +
	"\x10funds_sufficient\x18\x04 \x01(\bR\x0ffundsSufficient\x12<\n" +
	"\x1aestimated_blocks_remaining\x18\x05 \x01(\x04R\x18estimatedBlocksRemaining*\xb4\x01\n" +
	"\tEndReason\x12\x1a\n" +
	"\x16END_REASON_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13END_REASON_COMPLETE\x10\x01\x12 \n" +
	"\x1cEND_REASON_CLIENT_DISCONNECT\x10\x02\x12\x1c\n" +
	"\x18END_REASON_PROVIDER_STOP\x10\x03\x12\x14\n" +
	"\x10END_REASON_ERROR\x10\x04\x12\x1c\n" +
	"\x18END_REASON_PAYMENT_ISSUE\x10\x05B\xdc\x02\n" +
	"+com.graph.substreams.data_service.common.v1B\n" +
	"TypesProtoP\x01Zdgithub.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/common/v1;commonv1\xa2\x02\x04GSDC\xaa\x02&Graph.Substreams.DataService.Common.V1\xca\x02&Graph\\Substreams\\DataService\\Common\\V1\xe2\x022Graph\\Substreams\\DataService\\Common\\V1\\GPBMetadata\xea\x02*Graph::Substreams::DataService::Common::V1b\x06proto3"

var (
	file_graph_substreams_data_service_common_v1_types_proto_rawDescOnce sync.Once
	file_graph_substreams_data_service_common_v1_types_proto_rawDescData []byte
)

func file_graph_substreams_data_service_common_v1_types_proto_rawDescGZIP() []byte {
	file_graph_substreams_data_service_common_v1_types_proto_rawDescOnce.Do(func() {
		file_graph_substreams_data_service_common_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_substreams_data_service_common_v1_types_proto_rawDesc), len(file_graph_substreams_data_service_common_v1_types_proto_rawDesc)))
	})
	return file_graph_substreams_data_service_common_v1_types_proto_rawDescData
}

var file_graph_substreams_data_service_common_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_graph_substreams_data_service_common_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_graph_substreams_data_service_common_v1_types_proto_goTypes = []any{
	(EndReason)(0),            // 0: graph.substreams.data_service.common.v1.EndReason
	(*Address)(nil),           // 1: graph.substreams.data_service.common.v1.Address
	(*BigInt)(nil),            // 2: graph.substreams.data_service.common.v1.BigInt
	(*GRT)(nil),               // 3: graph.substreams.data_service.common.v1.GRT
	(*PricingConfig)(nil),     // 4: graph.substreams.data_service.common.v1.PricingConfig
	(*SignedRAV)(nil),         // 5: graph.substreams.data_service.common.v1.SignedRAV
	(*RAV)(nil),               // 6: graph.substreams.data_service.common.v1.RAV
	(*Usage)(nil),             // 7: graph.substreams.data_service.common.v1.Usage
	(*EscrowAccount)(nil),     // 8: graph.substreams.data_service.common.v1.EscrowAccount
	(*SessionInfo)(nil),       // 9: graph.substreams.data_service.common.v1.SessionInfo
	(*ServiceParameters)(nil), // 10: graph.substreams.data_service.common.v1.ServiceParameters
	(*PaymentStatus)(nil),     // 11: graph.substreams.data_service.common.v1.PaymentStatus
}
var file_graph_substreams_data_service_common_v1_types_proto_depIdxs = []int32{
	3,  // 0: graph.substreams.data_service.common.v1.PricingConfig.price_per_block:type_name -> graph.substreams.data_service.common.v1.GRT
	3,  // 1: graph.substreams.data_service.common.v1.PricingConfig.price_per_byte:type_name -> graph.substreams.data_service.common.v1.GRT
	6,  // 2: graph.substreams.data_service.common.v1.SignedRAV.rav:type_name -> graph.substreams.data_service.common.v1.RAV
	1,  // 3: graph.substreams.data_service.common.v1.RAV.payer:type_name -> graph.substreams.data_service.common.v1.Address
	1,  // 4: graph.substreams.data_service.common.v1.RAV.data_service:type_name -> graph.substreams.data_service.common.v1.Address
	1,  // 5: graph.substreams.data_service.common.v1.RAV.service_provider:type_name -> graph.substreams.data_service.common.v1.Address
	3,  // 6: graph.substreams.data_service.common.v1.RAV.value_aggregate:type_name -> graph.substreams.data_service.common.v1.GRT
	3,  // 7: graph.substreams.data_service.common.v1.Usage.cost:type_name -> graph.substreams.data_service.common.v1.GRT
	1,  // 8: graph.substreams.data_service.common.v1.EscrowAccount.payer:type_name -> graph.substreams.data_service.common.v1.Address
	1,  // 9: graph.substreams.data_service.common.v1.EscrowAccount.receiver:type_name -> graph.substreams.data_service.common.v1.Address
	1,  // 10: graph.substreams.data_service.common.v1.EscrowAccount.data_service:type_name -> graph.substreams.data_service.common.v1.Address
	8,  // 11: graph.substreams.data_service.common.v1.SessionInfo.escrow_account:type_name -> graph.substreams.data_service.common.v1.EscrowAccount
	5,  // 12: graph.substreams.data_service.common.v1.SessionInfo.current_rav:type_name -> graph.substreams.data_service.common.v1.SignedRAV
	7,  // 13: graph.substreams.data_service.common.v1.SessionInfo.accumulated_usage:type_name -> graph.substreams.data_service.common.v1.Usage
	4,  // 14: graph.substreams.data_service.common.v1.SessionInfo.pricing_config:type_name -> graph.substreams.data_service.common.v1.PricingConfig
	3,  // 15: graph.substreams.data_service.common.v1.ServiceParameters.price_per_block:type_name -> graph.substreams.data_service.common.v1.GRT
	3,  // 16: graph.substreams.data_service.common.v1.ServiceParameters.price_per_byte:type_name -> graph.substreams.data_service.common.v1.GRT
	3,  // 17: graph.substreams.data_service.common.v1.PaymentStatus.current_rav_value:type_name -> graph.substreams.data_service.common.v1.GRT
	3,  // 18: graph.substreams.data_service.common.v1.PaymentStatus.accumulated_usage_value:type_name -> graph.substreams.data_service.common.v1.GRT
	3,  // 19: graph.substreams.data_service.common.v1.PaymentStatus.escrow_balance:type_name -> graph.substreams.data_service.common.v1.GRT
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_graph_substreams_data_service_common_v1_types_proto_init() }
func file_graph_substreams_data_service_common_v1_types_proto_init() {
	if File_graph_substreams_data_service_common_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_substreams_data_service_common_v1_types_proto_rawDesc), len(file_graph_substreams_data_service_common_v1_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_graph_substreams_data_service_common_v1_types_proto_goTypes,
		DependencyIndexes: file_graph_substreams_data_service_common_v1_types_proto_depIdxs,
		EnumInfos:         file_graph_substreams_data_service_common_v1_types_proto_enumTypes,
		MessageInfos:      file_graph_substreams_data_service_common_v1_types_proto_msgTypes,
	}.Build()
	File_graph_substreams_data_service_common_v1_types_proto = out.File
	file_graph_substreams_data_service_common_v1_types_proto_goTypes = nil
	file_graph_substreams_data_service_common_v1_types_proto_depIdxs = nil
}
