// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: graph/substreams/data_service/sds/session/v1/session.proto

package sessionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BorrowStatus indicates the outcome of a BorrowWorker call.
type BorrowStatus int32

const (
	BorrowStatus_BORROW_STATUS_UNSPECIFIED BorrowStatus = 0
	// Worker slot acquired successfully
	BorrowStatus_BORROW_STATUS_BORROWED BorrowStatus = 1
	// Quota exceeded; caller should return an unavailable error to the client
	BorrowStatus_BORROW_STATUS_RESOURCE_EXHAUSTED BorrowStatus = 2
)

// Enum value maps for BorrowStatus.
var (
	BorrowStatus_name = map[int32]string{
		0: "BORROW_STATUS_UNSPECIFIED",
		1: "BORROW_STATUS_BORROWED",
		2: "BORROW_STATUS_RESOURCE_EXHAUSTED",
	}
	BorrowStatus_value = map[string]int32{
		"BORROW_STATUS_UNSPECIFIED":        0,
		"BORROW_STATUS_BORROWED":           1,
		"BORROW_STATUS_RESOURCE_EXHAUSTED": 2,
	}
)

func (x BorrowStatus) Enum() *BorrowStatus {
	p := new(BorrowStatus)
	*p = x
	return p
}

func (x BorrowStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BorrowStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_graph_substreams_data_service_sds_session_v1_session_proto_enumTypes[0].Descriptor()
}

func (BorrowStatus) Type() protoreflect.EnumType {
	return &file_graph_substreams_data_service_sds_session_v1_session_proto_enumTypes[0]
}

func (x BorrowStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BorrowStatus.Descriptor instead.
func (BorrowStatus) EnumDescriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_sds_session_v1_session_proto_rawDescGZIP(), []int{0}
}

// BorrowWorkerRequest acquires a worker slot for a request.
type BorrowWorkerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service identifier, e.g., "substreams"
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Payer Ethereum address (from auth context)
	OrganizationId string `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// Optional sub-key or signer identifier; empty for now
	ApiKeyId string `protobuf:"bytes,3,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	// SDS session ID from auth service (used for tracking payment sessions)
	// This is the actual session ID that links workers to payment sessions in the database.
	SessionId string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Maximum concurrent workers allowed for this session
	MaxWorkersPerSession int64 `protobuf:"varint,5,opt,name=max_workers_per_session,json=maxWorkersPerSession,proto3" json:"max_workers_per_session,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BorrowWorkerRequest) Reset() {
	*x = BorrowWorkerRequest{}
	mi := &file_graph_substreams_data_service_sds_session_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BorrowWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowWorkerRequest) ProtoMessage() {}

func (x *BorrowWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_sds_session_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowWorkerRequest.ProtoReflect.Descriptor instead.
func (*BorrowWorkerRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_sds_session_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *BorrowWorkerRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *BorrowWorkerRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *BorrowWorkerRequest) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

func (x *BorrowWorkerRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BorrowWorkerRequest) GetMaxWorkersPerSession() int64 {
	if x != nil {
		return x.MaxWorkersPerSession
	}
	return 0
}

type BorrowWorkerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique key identifying this worker slot; returned in ReturnWorker
	WorkerKey string `protobuf:"bytes,1,opt,name=worker_key,json=workerKey,proto3" json:"worker_key,omitempty"`
	// Outcome of the borrow attempt
	Status BorrowStatus `protobuf:"varint,2,opt,name=status,proto3,enum=graph.substreams.data_service.sds.session.v1.BorrowStatus" json:"status,omitempty"`
	// Capacity information about the worker pool
	WorkerState   *WorkerState `protobuf:"bytes,3,opt,name=worker_state,json=workerState,proto3" json:"worker_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BorrowWorkerResponse) Reset() {
	*x = BorrowWorkerResponse{}
	mi := &file_graph_substreams_data_service_sds_session_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BorrowWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowWorkerResponse) ProtoMessage() {}

func (x *BorrowWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_sds_session_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowWorkerResponse.ProtoReflect.Descriptor instead.
func (*BorrowWorkerResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_sds_session_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *BorrowWorkerResponse) GetWorkerKey() string {
	if x != nil {
		return x.WorkerKey
	}
	return ""
}

func (x *BorrowWorkerResponse) GetStatus() BorrowStatus {
	if x != nil {
		return x.Status
	}
	return BorrowStatus_BORROW_STATUS_UNSPECIFIED
}

func (x *BorrowWorkerResponse) GetWorkerState() *WorkerState {
	if x != nil {
		return x.WorkerState
	}
	return nil
}

// WorkerState describes the current capacity of the worker pool.
type WorkerState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of workers available in the pool
	MaxWorkers int64 `protobuf:"varint,1,opt,name=max_workers,json=maxWorkers,proto3" json:"max_workers,omitempty"`
	// Number of workers currently in use
	ActiveWorkers int64 `protobuf:"varint,2,opt,name=active_workers,json=activeWorkers,proto3" json:"active_workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerState) Reset() {
	*x = WorkerState{}
	mi := &file_graph_substreams_data_service_sds_session_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerState) ProtoMessage() {}

func (x *WorkerState) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_sds_session_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerState.ProtoReflect.Descriptor instead.
func (*WorkerState) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_sds_session_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerState) GetMaxWorkers() int64 {
	if x != nil {
		return x.MaxWorkers
	}
	return 0
}

func (x *WorkerState) GetActiveWorkers() int64 {
	if x != nil {
		return x.ActiveWorkers
	}
	return 0
}

// ReturnWorkerRequest releases a previously borrowed worker slot.
type ReturnWorkerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Worker key returned from BorrowWorker
	WorkerKey string `protobuf:"bytes,1,opt,name=worker_key,json=workerKey,proto3" json:"worker_key,omitempty"`
	// Minimum duration the worker should have been active before being released.
	// Used to enforce minimum billing windows.
	MinimalWorkerLifeDuration *durationpb.Duration `protobuf:"bytes,2,opt,name=minimal_worker_life_duration,json=minimalWorkerLifeDuration,proto3" json:"minimal_worker_life_duration,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ReturnWorkerRequest) Reset() {
	*x = ReturnWorkerRequest{}
	mi := &file_graph_substreams_data_service_sds_session_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnWorkerRequest) ProtoMessage() {}

func (x *ReturnWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_sds_session_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnWorkerRequest.ProtoReflect.Descriptor instead.
func (*ReturnWorkerRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_sds_session_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *ReturnWorkerRequest) GetWorkerKey() string {
	if x != nil {
		return x.WorkerKey
	}
	return ""
}

func (x *ReturnWorkerRequest) GetMinimalWorkerLifeDuration() *durationpb.Duration {
	if x != nil {
		return x.MinimalWorkerLifeDuration
	}
	return nil
}

type ReturnWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnWorkerResponse) Reset() {
	*x = ReturnWorkerResponse{}
	mi := &file_graph_substreams_data_service_sds_session_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnWorkerResponse) ProtoMessage() {}

func (x *ReturnWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_sds_session_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnWorkerResponse.ProtoReflect.Descriptor instead.
func (*ReturnWorkerResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_sds_session_v1_session_proto_rawDescGZIP(), []int{4}
}

// KeepAliveRequest refreshes the session's last-seen timestamp.
type KeepAliveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Worker key identifying the session to keep alive
	WorkerKey string `protobuf:"bytes,1,opt,name=worker_key,json=workerKey,proto3" json:"worker_key,omitempty"`
	// Optional sub-key or signer identifier
	ApiKeyId      string `protobuf:"bytes,2,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepAliveRequest) Reset() {
	*x = KeepAliveRequest{}
	mi := &file_graph_substreams_data_service_sds_session_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepAliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAliveRequest) ProtoMessage() {}

func (x *KeepAliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_sds_session_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAliveRequest.ProtoReflect.Descriptor instead.
func (*KeepAliveRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_sds_session_v1_session_proto_rawDescGZIP(), []int{5}
}

func (x *KeepAliveRequest) GetWorkerKey() string {
	if x != nil {
		return x.WorkerKey
	}
	return ""
}

func (x *KeepAliveRequest) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

type KeepAliveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepAliveResponse) Reset() {
	*x = KeepAliveResponse{}
	mi := &file_graph_substreams_data_service_sds_session_v1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepAliveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAliveResponse) ProtoMessage() {}

func (x *KeepAliveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_sds_session_v1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAliveResponse.ProtoReflect.Descriptor instead.
func (*KeepAliveResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_sds_session_v1_session_proto_rawDescGZIP(), []int{6}
}

var File_graph_substreams_data_service_sds_session_v1_session_proto protoreflect.FileDescriptor

const file_graph_substreams_data_service_sds_session_v1_session_proto_rawDesc = "" +
	"\n" +
	":graph/substreams/data_service/sds/session/v1/session.proto\x12,graph.substreams.data_service.sds.session.v1\x1a\x1egoogle/protobuf/duration.proto\"\xcc\x01\n" +
	"\x13BorrowWorkerRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x03 \x01(\tR\bapiKeyId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x125\n" +
	"\x17max_workers_per_session\x18\x05 \x01(\x03R\x14maxWorkersPerSession\"\xe7\x01\n" +
	"\x14BorrowWorkerResponse\x12\x1d\n" +
	"\n" +
	"worker_key\x18\x01 \x01(\tR\tworkerKey\x12R\n" +
	"\x06status\x18\x02 \x01(\x0e2:.graph.substreams.data_service.sds.session.v1.BorrowStatusR\x06status\x12\\\n" +
	"\fworker_state\x18\x03 \x01(\v29.graph.substreams.data_service.sds.session.v1.WorkerStateR\vworkerState\"U\n" +
	"\vWorkerState\x12\x1f\n" +
	"\vmax_workers\x18\x01 \x01(\x03R\n" +
	"maxWorkers\x12%\n" +
	"\x0eactive_workers\x18\x02 \x01(\x03R\ractiveWorkers\"\x90\x01\n" +
	"\x13ReturnWorkerRequest\x12\x1d\n" +
	"\n" +
	"worker_key\x18\x01 \x01(\tR\tworkerKey\x12Z\n" +
	"\x1cminimal_worker_life_duration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x19minimalWorkerLifeDuration\"\x16\n" +
	"\x14ReturnWorkerResponse\"O\n" +
	"\x10KeepAliveRequest\x12\x1d\n" +
	"\n" +
	"worker_key\x18\x01 \x01(\tR\tworkerKey\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x02 \x01(\tR\bapiKeyId\"\x13\n" +
	"\x11KeepAliveResponse*o\n" +
	"\fBorrowStatus\x12\x1d\n" +
	"\x19BORROW_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16BORROW_STATUS_BORROWED\x10\x01\x12$\n" +
	" BORROW_STATUS_RESOURCE_EXHAUSTED\x10\x022\xcf\x03\n" +
	"\x0eSessionService\x12\x95\x01\n" +
	"\fBorrowWorker\x12A.graph.substreams.data_service.sds.session.v1.BorrowWorkerRequest\x1aB.graph.substreams.data_service.sds.session.v1.BorrowWorkerResponse\x12\x95\x01\n" +
	"\fReturnWorker\x12A.graph.substreams.data_service.sds.session.v1.ReturnWorkerRequest\x1aB.graph.substreams.data_service.sds.session.v1.ReturnWorkerResponse\x12\x8c\x01\n" +
	"\tKeepAlive\x12>.graph.substreams.data_service.sds.session.v1.KeepAliveRequest\x1a?.graph.substreams.data_service.sds.session.v1.KeepAliveResponseB\xff\x02\n" +
	"0com.graph.substreams.data_service.sds.session.v1B\fSessionProtoP\x01Zjgithub.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/sds/session/v1;sessionv1\xa2\x02\x05GSDSS\xaa\x02+Graph.Substreams.DataService.Sds.Session.V1\xca\x02+Graph\\Substreams\\DataService\\Sds\\Session\\V1\xe2\x027Graph\\Substreams\\DataService\\Sds\\Session\\V1\\GPBMetadata\xea\x020Graph::Substreams::DataService::Sds::Session::V1b\x06proto3"

var (
	file_graph_substreams_data_service_sds_session_v1_session_proto_rawDescOnce sync.Once
	file_graph_substreams_data_service_sds_session_v1_session_proto_rawDescData []byte
)

func file_graph_substreams_data_service_sds_session_v1_session_proto_rawDescGZIP() []byte {
	file_graph_substreams_data_service_sds_session_v1_session_proto_rawDescOnce.Do(func() {
		file_graph_substreams_data_service_sds_session_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_substreams_data_service_sds_session_v1_session_proto_rawDesc), len(file_graph_substreams_data_service_sds_session_v1_session_proto_rawDesc)))
	})
	return file_graph_substreams_data_service_sds_session_v1_session_proto_rawDescData
}

var file_graph_substreams_data_service_sds_session_v1_session_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_graph_substreams_data_service_sds_session_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_graph_substreams_data_service_sds_session_v1_session_proto_goTypes = []any{
	(BorrowStatus)(0),            // 0: graph.substreams.data_service.sds.session.v1.BorrowStatus
	(*BorrowWorkerRequest)(nil),  // 1: graph.substreams.data_service.sds.session.v1.BorrowWorkerRequest
	(*BorrowWorkerResponse)(nil), // 2: graph.substreams.data_service.sds.session.v1.BorrowWorkerResponse
	(*WorkerState)(nil),          // 3: graph.substreams.data_service.sds.session.v1.WorkerState
	(*ReturnWorkerRequest)(nil),  // 4: graph.substreams.data_service.sds.session.v1.ReturnWorkerRequest
	(*ReturnWorkerResponse)(nil), // 5: graph.substreams.data_service.sds.session.v1.ReturnWorkerResponse
	(*KeepAliveRequest)(nil),     // 6: graph.substreams.data_service.sds.session.v1.KeepAliveRequest
	(*KeepAliveResponse)(nil),    // 7: graph.substreams.data_service.sds.session.v1.KeepAliveResponse
	(*durationpb.Duration)(nil),  // 8: google.protobuf.Duration
}
var file_graph_substreams_data_service_sds_session_v1_session_proto_depIdxs = []int32{
	0, // 0: graph.substreams.data_service.sds.session.v1.BorrowWorkerResponse.status:type_name -> graph.substreams.data_service.sds.session.v1.BorrowStatus
	3, // 1: graph.substreams.data_service.sds.session.v1.BorrowWorkerResponse.worker_state:type_name -> graph.substreams.data_service.sds.session.v1.WorkerState
	8, // 2: graph.substreams.data_service.sds.session.v1.ReturnWorkerRequest.minimal_worker_life_duration:type_name -> google.protobuf.Duration
	1, // 3: graph.substreams.data_service.sds.session.v1.SessionService.BorrowWorker:input_type -> graph.substreams.data_service.sds.session.v1.BorrowWorkerRequest
	4, // 4: graph.substreams.data_service.sds.session.v1.SessionService.ReturnWorker:input_type -> graph.substreams.data_service.sds.session.v1.ReturnWorkerRequest
	6, // 5: graph.substreams.data_service.sds.session.v1.SessionService.KeepAlive:input_type -> graph.substreams.data_service.sds.session.v1.KeepAliveRequest
	2, // 6: graph.substreams.data_service.sds.session.v1.SessionService.BorrowWorker:output_type -> graph.substreams.data_service.sds.session.v1.BorrowWorkerResponse
	5, // 7: graph.substreams.data_service.sds.session.v1.SessionService.ReturnWorker:output_type -> graph.substreams.data_service.sds.session.v1.ReturnWorkerResponse
	7, // 8: graph.substreams.data_service.sds.session.v1.SessionService.KeepAlive:output_type -> graph.substreams.data_service.sds.session.v1.KeepAliveResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_graph_substreams_data_service_sds_session_v1_session_proto_init() }
func file_graph_substreams_data_service_sds_session_v1_session_proto_init() {
	if File_graph_substreams_data_service_sds_session_v1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_substreams_data_service_sds_session_v1_session_proto_rawDesc), len(file_graph_substreams_data_service_sds_session_v1_session_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graph_substreams_data_service_sds_session_v1_session_proto_goTypes,
		DependencyIndexes: file_graph_substreams_data_service_sds_session_v1_session_proto_depIdxs,
		EnumInfos:         file_graph_substreams_data_service_sds_session_v1_session_proto_enumTypes,
		MessageInfos:      file_graph_substreams_data_service_sds_session_v1_session_proto_msgTypes,
	}.Build()
	File_graph_substreams_data_service_sds_session_v1_session_proto = out.File
	file_graph_substreams_data_service_sds_session_v1_session_proto_goTypes = nil
	file_graph_substreams_data_service_sds_session_v1_session_proto_depIdxs = nil
}
