// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: graph/substreams/data_service/provider/v1/gateway.proto

package providerv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/provider/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PaymentGatewayServiceName is the fully-qualified name of the PaymentGatewayService service.
	PaymentGatewayServiceName = "graph.substreams.data_service.provider.v1.PaymentGatewayService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PaymentGatewayServiceStartSessionProcedure is the fully-qualified name of the
	// PaymentGatewayService's StartSession RPC.
	PaymentGatewayServiceStartSessionProcedure = "/graph.substreams.data_service.provider.v1.PaymentGatewayService/StartSession"
	// PaymentGatewayServiceGetSessionStatusProcedure is the fully-qualified name of the
	// PaymentGatewayService's GetSessionStatus RPC.
	PaymentGatewayServiceGetSessionStatusProcedure = "/graph.substreams.data_service.provider.v1.PaymentGatewayService/GetSessionStatus"
	// PaymentGatewayServiceSubmitRAVProcedure is the fully-qualified name of the
	// PaymentGatewayService's SubmitRAV RPC.
	PaymentGatewayServiceSubmitRAVProcedure = "/graph.substreams.data_service.provider.v1.PaymentGatewayService/SubmitRAV"
	// PaymentGatewayServicePaymentSessionProcedure is the fully-qualified name of the
	// PaymentGatewayService's PaymentSession RPC.
	PaymentGatewayServicePaymentSessionProcedure = "/graph.substreams.data_service.provider.v1.PaymentGatewayService/PaymentSession"
)

// PaymentGatewayServiceClient is a client for the
// graph.substreams.data_service.provider.v1.PaymentGatewayService service.
type PaymentGatewayServiceClient interface {
	// StartSession initiates a payment session with the provider.
	// The consumer sidecar calls this to establish a session before
	// the substreams client connects to the provider.
	StartSession(context.Context, *connect.Request[v1.StartSessionRequest]) (*connect.Response[v1.StartSessionResponse], error)
	// GetSessionStatus returns basic status for a session, intended for operator
	// tooling and demo/integration flows.
	GetSessionStatus(context.Context, *connect.Request[v1.GetSessionStatusRequest]) (*connect.Response[v1.GetSessionStatusResponse], error)
	// SubmitRAV submits a signed RAV to the provider gateway.
	// Called when the provider requests a new RAV for continued service.
	SubmitRAV(context.Context, *connect.Request[v1.SubmitRAVRequest]) (*connect.Response[v1.SubmitRAVResponse], error)
	// PaymentSession is a bidirectional stream for ongoing payment negotiation.
	// This allows the provider gateway to request RAVs and notify about
	// funding requirements in real-time.
	PaymentSession(context.Context) *connect.BidiStreamForClient[v1.PaymentSessionRequest, v1.PaymentSessionResponse]
}

// NewPaymentGatewayServiceClient constructs a client for the
// graph.substreams.data_service.provider.v1.PaymentGatewayService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPaymentGatewayServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PaymentGatewayServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	paymentGatewayServiceMethods := v1.File_graph_substreams_data_service_provider_v1_gateway_proto.Services().ByName("PaymentGatewayService").Methods()
	return &paymentGatewayServiceClient{
		startSession: connect.NewClient[v1.StartSessionRequest, v1.StartSessionResponse](
			httpClient,
			baseURL+PaymentGatewayServiceStartSessionProcedure,
			connect.WithSchema(paymentGatewayServiceMethods.ByName("StartSession")),
			connect.WithClientOptions(opts...),
		),
		getSessionStatus: connect.NewClient[v1.GetSessionStatusRequest, v1.GetSessionStatusResponse](
			httpClient,
			baseURL+PaymentGatewayServiceGetSessionStatusProcedure,
			connect.WithSchema(paymentGatewayServiceMethods.ByName("GetSessionStatus")),
			connect.WithClientOptions(opts...),
		),
		submitRAV: connect.NewClient[v1.SubmitRAVRequest, v1.SubmitRAVResponse](
			httpClient,
			baseURL+PaymentGatewayServiceSubmitRAVProcedure,
			connect.WithSchema(paymentGatewayServiceMethods.ByName("SubmitRAV")),
			connect.WithClientOptions(opts...),
		),
		paymentSession: connect.NewClient[v1.PaymentSessionRequest, v1.PaymentSessionResponse](
			httpClient,
			baseURL+PaymentGatewayServicePaymentSessionProcedure,
			connect.WithSchema(paymentGatewayServiceMethods.ByName("PaymentSession")),
			connect.WithClientOptions(opts...),
		),
	}
}

// paymentGatewayServiceClient implements PaymentGatewayServiceClient.
type paymentGatewayServiceClient struct {
	startSession     *connect.Client[v1.StartSessionRequest, v1.StartSessionResponse]
	getSessionStatus *connect.Client[v1.GetSessionStatusRequest, v1.GetSessionStatusResponse]
	submitRAV        *connect.Client[v1.SubmitRAVRequest, v1.SubmitRAVResponse]
	paymentSession   *connect.Client[v1.PaymentSessionRequest, v1.PaymentSessionResponse]
}

// StartSession calls graph.substreams.data_service.provider.v1.PaymentGatewayService.StartSession.
func (c *paymentGatewayServiceClient) StartSession(ctx context.Context, req *connect.Request[v1.StartSessionRequest]) (*connect.Response[v1.StartSessionResponse], error) {
	return c.startSession.CallUnary(ctx, req)
}

// GetSessionStatus calls
// graph.substreams.data_service.provider.v1.PaymentGatewayService.GetSessionStatus.
func (c *paymentGatewayServiceClient) GetSessionStatus(ctx context.Context, req *connect.Request[v1.GetSessionStatusRequest]) (*connect.Response[v1.GetSessionStatusResponse], error) {
	return c.getSessionStatus.CallUnary(ctx, req)
}

// SubmitRAV calls graph.substreams.data_service.provider.v1.PaymentGatewayService.SubmitRAV.
func (c *paymentGatewayServiceClient) SubmitRAV(ctx context.Context, req *connect.Request[v1.SubmitRAVRequest]) (*connect.Response[v1.SubmitRAVResponse], error) {
	return c.submitRAV.CallUnary(ctx, req)
}

// PaymentSession calls
// graph.substreams.data_service.provider.v1.PaymentGatewayService.PaymentSession.
func (c *paymentGatewayServiceClient) PaymentSession(ctx context.Context) *connect.BidiStreamForClient[v1.PaymentSessionRequest, v1.PaymentSessionResponse] {
	return c.paymentSession.CallBidiStream(ctx)
}

// PaymentGatewayServiceHandler is an implementation of the
// graph.substreams.data_service.provider.v1.PaymentGatewayService service.
type PaymentGatewayServiceHandler interface {
	// StartSession initiates a payment session with the provider.
	// The consumer sidecar calls this to establish a session before
	// the substreams client connects to the provider.
	StartSession(context.Context, *connect.Request[v1.StartSessionRequest]) (*connect.Response[v1.StartSessionResponse], error)
	// GetSessionStatus returns basic status for a session, intended for operator
	// tooling and demo/integration flows.
	GetSessionStatus(context.Context, *connect.Request[v1.GetSessionStatusRequest]) (*connect.Response[v1.GetSessionStatusResponse], error)
	// SubmitRAV submits a signed RAV to the provider gateway.
	// Called when the provider requests a new RAV for continued service.
	SubmitRAV(context.Context, *connect.Request[v1.SubmitRAVRequest]) (*connect.Response[v1.SubmitRAVResponse], error)
	// PaymentSession is a bidirectional stream for ongoing payment negotiation.
	// This allows the provider gateway to request RAVs and notify about
	// funding requirements in real-time.
	PaymentSession(context.Context, *connect.BidiStream[v1.PaymentSessionRequest, v1.PaymentSessionResponse]) error
}

// NewPaymentGatewayServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPaymentGatewayServiceHandler(svc PaymentGatewayServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	paymentGatewayServiceMethods := v1.File_graph_substreams_data_service_provider_v1_gateway_proto.Services().ByName("PaymentGatewayService").Methods()
	paymentGatewayServiceStartSessionHandler := connect.NewUnaryHandler(
		PaymentGatewayServiceStartSessionProcedure,
		svc.StartSession,
		connect.WithSchema(paymentGatewayServiceMethods.ByName("StartSession")),
		connect.WithHandlerOptions(opts...),
	)
	paymentGatewayServiceGetSessionStatusHandler := connect.NewUnaryHandler(
		PaymentGatewayServiceGetSessionStatusProcedure,
		svc.GetSessionStatus,
		connect.WithSchema(paymentGatewayServiceMethods.ByName("GetSessionStatus")),
		connect.WithHandlerOptions(opts...),
	)
	paymentGatewayServiceSubmitRAVHandler := connect.NewUnaryHandler(
		PaymentGatewayServiceSubmitRAVProcedure,
		svc.SubmitRAV,
		connect.WithSchema(paymentGatewayServiceMethods.ByName("SubmitRAV")),
		connect.WithHandlerOptions(opts...),
	)
	paymentGatewayServicePaymentSessionHandler := connect.NewBidiStreamHandler(
		PaymentGatewayServicePaymentSessionProcedure,
		svc.PaymentSession,
		connect.WithSchema(paymentGatewayServiceMethods.ByName("PaymentSession")),
		connect.WithHandlerOptions(opts...),
	)
	return "/graph.substreams.data_service.provider.v1.PaymentGatewayService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PaymentGatewayServiceStartSessionProcedure:
			paymentGatewayServiceStartSessionHandler.ServeHTTP(w, r)
		case PaymentGatewayServiceGetSessionStatusProcedure:
			paymentGatewayServiceGetSessionStatusHandler.ServeHTTP(w, r)
		case PaymentGatewayServiceSubmitRAVProcedure:
			paymentGatewayServiceSubmitRAVHandler.ServeHTTP(w, r)
		case PaymentGatewayServicePaymentSessionProcedure:
			paymentGatewayServicePaymentSessionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPaymentGatewayServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPaymentGatewayServiceHandler struct{}

func (UnimplementedPaymentGatewayServiceHandler) StartSession(context.Context, *connect.Request[v1.StartSessionRequest]) (*connect.Response[v1.StartSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.provider.v1.PaymentGatewayService.StartSession is not implemented"))
}

func (UnimplementedPaymentGatewayServiceHandler) GetSessionStatus(context.Context, *connect.Request[v1.GetSessionStatusRequest]) (*connect.Response[v1.GetSessionStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.provider.v1.PaymentGatewayService.GetSessionStatus is not implemented"))
}

func (UnimplementedPaymentGatewayServiceHandler) SubmitRAV(context.Context, *connect.Request[v1.SubmitRAVRequest]) (*connect.Response[v1.SubmitRAVResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.provider.v1.PaymentGatewayService.SubmitRAV is not implemented"))
}

func (UnimplementedPaymentGatewayServiceHandler) PaymentSession(context.Context, *connect.BidiStream[v1.PaymentSessionRequest, v1.PaymentSessionResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.provider.v1.PaymentGatewayService.PaymentSession is not implemented"))
}
