// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: graph/substreams/data_service/provider/v1/operator.proto

package providerv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/provider/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProviderOperatorServiceName is the fully-qualified name of the ProviderOperatorService service.
	ProviderOperatorServiceName = "graph.substreams.data_service.provider.v1.ProviderOperatorService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProviderOperatorServiceListSessionsProcedure is the fully-qualified name of the
	// ProviderOperatorService's ListSessions RPC.
	ProviderOperatorServiceListSessionsProcedure = "/graph.substreams.data_service.provider.v1.ProviderOperatorService/ListSessions"
	// ProviderOperatorServiceGetSessionProcedure is the fully-qualified name of the
	// ProviderOperatorService's GetSession RPC.
	ProviderOperatorServiceGetSessionProcedure = "/graph.substreams.data_service.provider.v1.ProviderOperatorService/GetSession"
	// ProviderOperatorServiceListAcceptedRAVsProcedure is the fully-qualified name of the
	// ProviderOperatorService's ListAcceptedRAVs RPC.
	ProviderOperatorServiceListAcceptedRAVsProcedure = "/graph.substreams.data_service.provider.v1.ProviderOperatorService/ListAcceptedRAVs"
	// ProviderOperatorServiceGetAcceptedRAVProcedure is the fully-qualified name of the
	// ProviderOperatorService's GetAcceptedRAV RPC.
	ProviderOperatorServiceGetAcceptedRAVProcedure = "/graph.substreams.data_service.provider.v1.ProviderOperatorService/GetAcceptedRAV"
	// ProviderOperatorServiceListCollectionsProcedure is the fully-qualified name of the
	// ProviderOperatorService's ListCollections RPC.
	ProviderOperatorServiceListCollectionsProcedure = "/graph.substreams.data_service.provider.v1.ProviderOperatorService/ListCollections"
	// ProviderOperatorServiceGetCollectionProcedure is the fully-qualified name of the
	// ProviderOperatorService's GetCollection RPC.
	ProviderOperatorServiceGetCollectionProcedure = "/graph.substreams.data_service.provider.v1.ProviderOperatorService/GetCollection"
	// ProviderOperatorServiceMarkCollectionPendingProcedure is the fully-qualified name of the
	// ProviderOperatorService's MarkCollectionPending RPC.
	ProviderOperatorServiceMarkCollectionPendingProcedure = "/graph.substreams.data_service.provider.v1.ProviderOperatorService/MarkCollectionPending"
	// ProviderOperatorServiceMarkCollectionCollectedProcedure is the fully-qualified name of the
	// ProviderOperatorService's MarkCollectionCollected RPC.
	ProviderOperatorServiceMarkCollectionCollectedProcedure = "/graph.substreams.data_service.provider.v1.ProviderOperatorService/MarkCollectionCollected"
	// ProviderOperatorServiceMarkCollectionRetryableProcedure is the fully-qualified name of the
	// ProviderOperatorService's MarkCollectionRetryable RPC.
	ProviderOperatorServiceMarkCollectionRetryableProcedure = "/graph.substreams.data_service.provider.v1.ProviderOperatorService/MarkCollectionRetryable"
)

// ProviderOperatorServiceClient is a client for the
// graph.substreams.data_service.provider.v1.ProviderOperatorService service.
type ProviderOperatorServiceClient interface {
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error)
	GetSession(context.Context, *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error)
	ListAcceptedRAVs(context.Context, *connect.Request[v1.ListAcceptedRAVsRequest]) (*connect.Response[v1.ListAcceptedRAVsResponse], error)
	GetAcceptedRAV(context.Context, *connect.Request[v1.GetAcceptedRAVRequest]) (*connect.Response[v1.GetAcceptedRAVResponse], error)
	ListCollections(context.Context, *connect.Request[v1.ListCollectionsRequest]) (*connect.Response[v1.ListCollectionsResponse], error)
	GetCollection(context.Context, *connect.Request[v1.GetCollectionRequest]) (*connect.Response[v1.GetCollectionResponse], error)
	MarkCollectionPending(context.Context, *connect.Request[v1.MarkCollectionPendingRequest]) (*connect.Response[v1.MarkCollectionPendingResponse], error)
	MarkCollectionCollected(context.Context, *connect.Request[v1.MarkCollectionCollectedRequest]) (*connect.Response[v1.MarkCollectionCollectedResponse], error)
	MarkCollectionRetryable(context.Context, *connect.Request[v1.MarkCollectionRetryableRequest]) (*connect.Response[v1.MarkCollectionRetryableResponse], error)
}

// NewProviderOperatorServiceClient constructs a client for the
// graph.substreams.data_service.provider.v1.ProviderOperatorService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProviderOperatorServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProviderOperatorServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	providerOperatorServiceMethods := v1.File_graph_substreams_data_service_provider_v1_operator_proto.Services().ByName("ProviderOperatorService").Methods()
	return &providerOperatorServiceClient{
		listSessions: connect.NewClient[v1.ListSessionsRequest, v1.ListSessionsResponse](
			httpClient,
			baseURL+ProviderOperatorServiceListSessionsProcedure,
			connect.WithSchema(providerOperatorServiceMethods.ByName("ListSessions")),
			connect.WithClientOptions(opts...),
		),
		getSession: connect.NewClient[v1.GetSessionRequest, v1.GetSessionResponse](
			httpClient,
			baseURL+ProviderOperatorServiceGetSessionProcedure,
			connect.WithSchema(providerOperatorServiceMethods.ByName("GetSession")),
			connect.WithClientOptions(opts...),
		),
		listAcceptedRAVs: connect.NewClient[v1.ListAcceptedRAVsRequest, v1.ListAcceptedRAVsResponse](
			httpClient,
			baseURL+ProviderOperatorServiceListAcceptedRAVsProcedure,
			connect.WithSchema(providerOperatorServiceMethods.ByName("ListAcceptedRAVs")),
			connect.WithClientOptions(opts...),
		),
		getAcceptedRAV: connect.NewClient[v1.GetAcceptedRAVRequest, v1.GetAcceptedRAVResponse](
			httpClient,
			baseURL+ProviderOperatorServiceGetAcceptedRAVProcedure,
			connect.WithSchema(providerOperatorServiceMethods.ByName("GetAcceptedRAV")),
			connect.WithClientOptions(opts...),
		),
		listCollections: connect.NewClient[v1.ListCollectionsRequest, v1.ListCollectionsResponse](
			httpClient,
			baseURL+ProviderOperatorServiceListCollectionsProcedure,
			connect.WithSchema(providerOperatorServiceMethods.ByName("ListCollections")),
			connect.WithClientOptions(opts...),
		),
		getCollection: connect.NewClient[v1.GetCollectionRequest, v1.GetCollectionResponse](
			httpClient,
			baseURL+ProviderOperatorServiceGetCollectionProcedure,
			connect.WithSchema(providerOperatorServiceMethods.ByName("GetCollection")),
			connect.WithClientOptions(opts...),
		),
		markCollectionPending: connect.NewClient[v1.MarkCollectionPendingRequest, v1.MarkCollectionPendingResponse](
			httpClient,
			baseURL+ProviderOperatorServiceMarkCollectionPendingProcedure,
			connect.WithSchema(providerOperatorServiceMethods.ByName("MarkCollectionPending")),
			connect.WithClientOptions(opts...),
		),
		markCollectionCollected: connect.NewClient[v1.MarkCollectionCollectedRequest, v1.MarkCollectionCollectedResponse](
			httpClient,
			baseURL+ProviderOperatorServiceMarkCollectionCollectedProcedure,
			connect.WithSchema(providerOperatorServiceMethods.ByName("MarkCollectionCollected")),
			connect.WithClientOptions(opts...),
		),
		markCollectionRetryable: connect.NewClient[v1.MarkCollectionRetryableRequest, v1.MarkCollectionRetryableResponse](
			httpClient,
			baseURL+ProviderOperatorServiceMarkCollectionRetryableProcedure,
			connect.WithSchema(providerOperatorServiceMethods.ByName("MarkCollectionRetryable")),
			connect.WithClientOptions(opts...),
		),
	}
}

// providerOperatorServiceClient implements ProviderOperatorServiceClient.
type providerOperatorServiceClient struct {
	listSessions            *connect.Client[v1.ListSessionsRequest, v1.ListSessionsResponse]
	getSession              *connect.Client[v1.GetSessionRequest, v1.GetSessionResponse]
	listAcceptedRAVs        *connect.Client[v1.ListAcceptedRAVsRequest, v1.ListAcceptedRAVsResponse]
	getAcceptedRAV          *connect.Client[v1.GetAcceptedRAVRequest, v1.GetAcceptedRAVResponse]
	listCollections         *connect.Client[v1.ListCollectionsRequest, v1.ListCollectionsResponse]
	getCollection           *connect.Client[v1.GetCollectionRequest, v1.GetCollectionResponse]
	markCollectionPending   *connect.Client[v1.MarkCollectionPendingRequest, v1.MarkCollectionPendingResponse]
	markCollectionCollected *connect.Client[v1.MarkCollectionCollectedRequest, v1.MarkCollectionCollectedResponse]
	markCollectionRetryable *connect.Client[v1.MarkCollectionRetryableRequest, v1.MarkCollectionRetryableResponse]
}

// ListSessions calls
// graph.substreams.data_service.provider.v1.ProviderOperatorService.ListSessions.
func (c *providerOperatorServiceClient) ListSessions(ctx context.Context, req *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error) {
	return c.listSessions.CallUnary(ctx, req)
}

// GetSession calls graph.substreams.data_service.provider.v1.ProviderOperatorService.GetSession.
func (c *providerOperatorServiceClient) GetSession(ctx context.Context, req *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error) {
	return c.getSession.CallUnary(ctx, req)
}

// ListAcceptedRAVs calls
// graph.substreams.data_service.provider.v1.ProviderOperatorService.ListAcceptedRAVs.
func (c *providerOperatorServiceClient) ListAcceptedRAVs(ctx context.Context, req *connect.Request[v1.ListAcceptedRAVsRequest]) (*connect.Response[v1.ListAcceptedRAVsResponse], error) {
	return c.listAcceptedRAVs.CallUnary(ctx, req)
}

// GetAcceptedRAV calls
// graph.substreams.data_service.provider.v1.ProviderOperatorService.GetAcceptedRAV.
func (c *providerOperatorServiceClient) GetAcceptedRAV(ctx context.Context, req *connect.Request[v1.GetAcceptedRAVRequest]) (*connect.Response[v1.GetAcceptedRAVResponse], error) {
	return c.getAcceptedRAV.CallUnary(ctx, req)
}

// ListCollections calls
// graph.substreams.data_service.provider.v1.ProviderOperatorService.ListCollections.
func (c *providerOperatorServiceClient) ListCollections(ctx context.Context, req *connect.Request[v1.ListCollectionsRequest]) (*connect.Response[v1.ListCollectionsResponse], error) {
	return c.listCollections.CallUnary(ctx, req)
}

// GetCollection calls
// graph.substreams.data_service.provider.v1.ProviderOperatorService.GetCollection.
func (c *providerOperatorServiceClient) GetCollection(ctx context.Context, req *connect.Request[v1.GetCollectionRequest]) (*connect.Response[v1.GetCollectionResponse], error) {
	return c.getCollection.CallUnary(ctx, req)
}

// MarkCollectionPending calls
// graph.substreams.data_service.provider.v1.ProviderOperatorService.MarkCollectionPending.
func (c *providerOperatorServiceClient) MarkCollectionPending(ctx context.Context, req *connect.Request[v1.MarkCollectionPendingRequest]) (*connect.Response[v1.MarkCollectionPendingResponse], error) {
	return c.markCollectionPending.CallUnary(ctx, req)
}

// MarkCollectionCollected calls
// graph.substreams.data_service.provider.v1.ProviderOperatorService.MarkCollectionCollected.
func (c *providerOperatorServiceClient) MarkCollectionCollected(ctx context.Context, req *connect.Request[v1.MarkCollectionCollectedRequest]) (*connect.Response[v1.MarkCollectionCollectedResponse], error) {
	return c.markCollectionCollected.CallUnary(ctx, req)
}

// MarkCollectionRetryable calls
// graph.substreams.data_service.provider.v1.ProviderOperatorService.MarkCollectionRetryable.
func (c *providerOperatorServiceClient) MarkCollectionRetryable(ctx context.Context, req *connect.Request[v1.MarkCollectionRetryableRequest]) (*connect.Response[v1.MarkCollectionRetryableResponse], error) {
	return c.markCollectionRetryable.CallUnary(ctx, req)
}

// ProviderOperatorServiceHandler is an implementation of the
// graph.substreams.data_service.provider.v1.ProviderOperatorService service.
type ProviderOperatorServiceHandler interface {
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error)
	GetSession(context.Context, *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error)
	ListAcceptedRAVs(context.Context, *connect.Request[v1.ListAcceptedRAVsRequest]) (*connect.Response[v1.ListAcceptedRAVsResponse], error)
	GetAcceptedRAV(context.Context, *connect.Request[v1.GetAcceptedRAVRequest]) (*connect.Response[v1.GetAcceptedRAVResponse], error)
	ListCollections(context.Context, *connect.Request[v1.ListCollectionsRequest]) (*connect.Response[v1.ListCollectionsResponse], error)
	GetCollection(context.Context, *connect.Request[v1.GetCollectionRequest]) (*connect.Response[v1.GetCollectionResponse], error)
	MarkCollectionPending(context.Context, *connect.Request[v1.MarkCollectionPendingRequest]) (*connect.Response[v1.MarkCollectionPendingResponse], error)
	MarkCollectionCollected(context.Context, *connect.Request[v1.MarkCollectionCollectedRequest]) (*connect.Response[v1.MarkCollectionCollectedResponse], error)
	MarkCollectionRetryable(context.Context, *connect.Request[v1.MarkCollectionRetryableRequest]) (*connect.Response[v1.MarkCollectionRetryableResponse], error)
}

// NewProviderOperatorServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProviderOperatorServiceHandler(svc ProviderOperatorServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	providerOperatorServiceMethods := v1.File_graph_substreams_data_service_provider_v1_operator_proto.Services().ByName("ProviderOperatorService").Methods()
	providerOperatorServiceListSessionsHandler := connect.NewUnaryHandler(
		ProviderOperatorServiceListSessionsProcedure,
		svc.ListSessions,
		connect.WithSchema(providerOperatorServiceMethods.ByName("ListSessions")),
		connect.WithHandlerOptions(opts...),
	)
	providerOperatorServiceGetSessionHandler := connect.NewUnaryHandler(
		ProviderOperatorServiceGetSessionProcedure,
		svc.GetSession,
		connect.WithSchema(providerOperatorServiceMethods.ByName("GetSession")),
		connect.WithHandlerOptions(opts...),
	)
	providerOperatorServiceListAcceptedRAVsHandler := connect.NewUnaryHandler(
		ProviderOperatorServiceListAcceptedRAVsProcedure,
		svc.ListAcceptedRAVs,
		connect.WithSchema(providerOperatorServiceMethods.ByName("ListAcceptedRAVs")),
		connect.WithHandlerOptions(opts...),
	)
	providerOperatorServiceGetAcceptedRAVHandler := connect.NewUnaryHandler(
		ProviderOperatorServiceGetAcceptedRAVProcedure,
		svc.GetAcceptedRAV,
		connect.WithSchema(providerOperatorServiceMethods.ByName("GetAcceptedRAV")),
		connect.WithHandlerOptions(opts...),
	)
	providerOperatorServiceListCollectionsHandler := connect.NewUnaryHandler(
		ProviderOperatorServiceListCollectionsProcedure,
		svc.ListCollections,
		connect.WithSchema(providerOperatorServiceMethods.ByName("ListCollections")),
		connect.WithHandlerOptions(opts...),
	)
	providerOperatorServiceGetCollectionHandler := connect.NewUnaryHandler(
		ProviderOperatorServiceGetCollectionProcedure,
		svc.GetCollection,
		connect.WithSchema(providerOperatorServiceMethods.ByName("GetCollection")),
		connect.WithHandlerOptions(opts...),
	)
	providerOperatorServiceMarkCollectionPendingHandler := connect.NewUnaryHandler(
		ProviderOperatorServiceMarkCollectionPendingProcedure,
		svc.MarkCollectionPending,
		connect.WithSchema(providerOperatorServiceMethods.ByName("MarkCollectionPending")),
		connect.WithHandlerOptions(opts...),
	)
	providerOperatorServiceMarkCollectionCollectedHandler := connect.NewUnaryHandler(
		ProviderOperatorServiceMarkCollectionCollectedProcedure,
		svc.MarkCollectionCollected,
		connect.WithSchema(providerOperatorServiceMethods.ByName("MarkCollectionCollected")),
		connect.WithHandlerOptions(opts...),
	)
	providerOperatorServiceMarkCollectionRetryableHandler := connect.NewUnaryHandler(
		ProviderOperatorServiceMarkCollectionRetryableProcedure,
		svc.MarkCollectionRetryable,
		connect.WithSchema(providerOperatorServiceMethods.ByName("MarkCollectionRetryable")),
		connect.WithHandlerOptions(opts...),
	)
	return "/graph.substreams.data_service.provider.v1.ProviderOperatorService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProviderOperatorServiceListSessionsProcedure:
			providerOperatorServiceListSessionsHandler.ServeHTTP(w, r)
		case ProviderOperatorServiceGetSessionProcedure:
			providerOperatorServiceGetSessionHandler.ServeHTTP(w, r)
		case ProviderOperatorServiceListAcceptedRAVsProcedure:
			providerOperatorServiceListAcceptedRAVsHandler.ServeHTTP(w, r)
		case ProviderOperatorServiceGetAcceptedRAVProcedure:
			providerOperatorServiceGetAcceptedRAVHandler.ServeHTTP(w, r)
		case ProviderOperatorServiceListCollectionsProcedure:
			providerOperatorServiceListCollectionsHandler.ServeHTTP(w, r)
		case ProviderOperatorServiceGetCollectionProcedure:
			providerOperatorServiceGetCollectionHandler.ServeHTTP(w, r)
		case ProviderOperatorServiceMarkCollectionPendingProcedure:
			providerOperatorServiceMarkCollectionPendingHandler.ServeHTTP(w, r)
		case ProviderOperatorServiceMarkCollectionCollectedProcedure:
			providerOperatorServiceMarkCollectionCollectedHandler.ServeHTTP(w, r)
		case ProviderOperatorServiceMarkCollectionRetryableProcedure:
			providerOperatorServiceMarkCollectionRetryableHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProviderOperatorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProviderOperatorServiceHandler struct{}

func (UnimplementedProviderOperatorServiceHandler) ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.provider.v1.ProviderOperatorService.ListSessions is not implemented"))
}

func (UnimplementedProviderOperatorServiceHandler) GetSession(context.Context, *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.provider.v1.ProviderOperatorService.GetSession is not implemented"))
}

func (UnimplementedProviderOperatorServiceHandler) ListAcceptedRAVs(context.Context, *connect.Request[v1.ListAcceptedRAVsRequest]) (*connect.Response[v1.ListAcceptedRAVsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.provider.v1.ProviderOperatorService.ListAcceptedRAVs is not implemented"))
}

func (UnimplementedProviderOperatorServiceHandler) GetAcceptedRAV(context.Context, *connect.Request[v1.GetAcceptedRAVRequest]) (*connect.Response[v1.GetAcceptedRAVResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.provider.v1.ProviderOperatorService.GetAcceptedRAV is not implemented"))
}

func (UnimplementedProviderOperatorServiceHandler) ListCollections(context.Context, *connect.Request[v1.ListCollectionsRequest]) (*connect.Response[v1.ListCollectionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.provider.v1.ProviderOperatorService.ListCollections is not implemented"))
}

func (UnimplementedProviderOperatorServiceHandler) GetCollection(context.Context, *connect.Request[v1.GetCollectionRequest]) (*connect.Response[v1.GetCollectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.provider.v1.ProviderOperatorService.GetCollection is not implemented"))
}

func (UnimplementedProviderOperatorServiceHandler) MarkCollectionPending(context.Context, *connect.Request[v1.MarkCollectionPendingRequest]) (*connect.Response[v1.MarkCollectionPendingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.provider.v1.ProviderOperatorService.MarkCollectionPending is not implemented"))
}

func (UnimplementedProviderOperatorServiceHandler) MarkCollectionCollected(context.Context, *connect.Request[v1.MarkCollectionCollectedRequest]) (*connect.Response[v1.MarkCollectionCollectedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.provider.v1.ProviderOperatorService.MarkCollectionCollected is not implemented"))
}

func (UnimplementedProviderOperatorServiceHandler) MarkCollectionRetryable(context.Context, *connect.Request[v1.MarkCollectionRetryableRequest]) (*connect.Response[v1.MarkCollectionRetryableResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.provider.v1.ProviderOperatorService.MarkCollectionRetryable is not implemented"))
}
