// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: graph/substreams/data_service/provider/v1/gateway.proto

package providerv1

import (
	v1 "github.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Control action
type SessionControl_Action int32

const (
	SessionControl_ACTION_UNSPECIFIED SessionControl_Action = 0
	// Continue the session
	SessionControl_ACTION_CONTINUE SessionControl_Action = 1
	// Stop the session gracefully
	SessionControl_ACTION_STOP SessionControl_Action = 2
	// Pause the session (temporary)
	SessionControl_ACTION_PAUSE SessionControl_Action = 3
)

// Enum value maps for SessionControl_Action.
var (
	SessionControl_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_CONTINUE",
		2: "ACTION_STOP",
		3: "ACTION_PAUSE",
	}
	SessionControl_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_CONTINUE":    1,
		"ACTION_STOP":        2,
		"ACTION_PAUSE":       3,
	}
)

func (x SessionControl_Action) Enum() *SessionControl_Action {
	p := new(SessionControl_Action)
	*p = x
	return p
}

func (x SessionControl_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionControl_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_graph_substreams_data_service_provider_v1_gateway_proto_enumTypes[0].Descriptor()
}

func (SessionControl_Action) Type() protoreflect.EnumType {
	return &file_graph_substreams_data_service_provider_v1_gateway_proto_enumTypes[0]
}

func (x SessionControl_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionControl_Action.Descriptor instead.
func (SessionControl_Action) EnumDescriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_gateway_proto_rawDescGZIP(), []int{12, 0}
}

type GetSessionStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session ID
	SessionId     string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionStatusRequest) Reset() {
	*x = GetSessionStatusRequest{}
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionStatusRequest) ProtoMessage() {}

func (x *GetSessionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSessionStatusRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GetSessionStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the session is active.
	Active bool `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	// Payment status snapshot (best-effort).
	PaymentStatus *v1.PaymentStatus `protobuf:"bytes,2,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	// Persisted terminal reason once the session is no longer active.
	EndReason v1.EndReason `protobuf:"varint,3,opt,name=end_reason,json=endReason,proto3,enum=graph.substreams.data_service.common.v1.EndReason" json:"end_reason,omitempty"`
	// Whether provider-side runtime state has payment control work that should be
	// resolved before a finite consumer ingress returns cleanly.
	PaymentControlPending bool `protobuf:"varint,4,opt,name=payment_control_pending,json=paymentControlPending,proto3" json:"payment_control_pending,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetSessionStatusResponse) Reset() {
	*x = GetSessionStatusResponse{}
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionStatusResponse) ProtoMessage() {}

func (x *GetSessionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSessionStatusResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *GetSessionStatusResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *GetSessionStatusResponse) GetPaymentStatus() *v1.PaymentStatus {
	if x != nil {
		return x.PaymentStatus
	}
	return nil
}

func (x *GetSessionStatusResponse) GetEndReason() v1.EndReason {
	if x != nil {
		return x.EndReason
	}
	return v1.EndReason(0)
}

func (x *GetSessionStatusResponse) GetPaymentControlPending() bool {
	if x != nil {
		return x.PaymentControlPending
	}
	return false
}

type StartSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The escrow account funding this session
	EscrowAccount *v1.EscrowAccount `protobuf:"bytes,1,opt,name=escrow_account,json=escrowAccount,proto3" json:"escrow_account,omitempty"`
	// Initial RAV (can be a zero-value RAV for new sessions)
	InitialRav    *v1.SignedRAV `protobuf:"bytes,2,opt,name=initial_rav,json=initialRav,proto3" json:"initial_rav,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *StartSessionRequest) GetEscrowAccount() *v1.EscrowAccount {
	if x != nil {
		return x.EscrowAccount
	}
	return nil
}

func (x *StartSessionRequest) GetInitialRav() *v1.SignedRAV {
	if x != nil {
		return x.InitialRav
	}
	return nil
}

type StartSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique session identifier assigned by the provider
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// The RAV to use for authentication (may be the same or different from initial)
	UseRav *v1.SignedRAV `protobuf:"bytes,2,opt,name=use_rav,json=useRav,proto3" json:"use_rav,omitempty"`
	// Whether the session was accepted
	Accepted bool `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// If not accepted, the reason for rejection
	RejectionReason string `protobuf:"bytes,4,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	// The provider's pricing configuration for this session.
	// For MVP this is confirmatory/observational only, not a negotiation surface.
	PricingConfig *v1.PricingConfig `protobuf:"bytes,5,opt,name=pricing_config,json=pricingConfig,proto3" json:"pricing_config,omitempty"`
	// The session-specific data-plane endpoint for Substreams traffic.
	DataPlaneEndpoint string `protobuf:"bytes,6,opt,name=data_plane_endpoint,json=dataPlaneEndpoint,proto3" json:"data_plane_endpoint,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StartSessionResponse) Reset() {
	*x = StartSessionResponse{}
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionResponse) ProtoMessage() {}

func (x *StartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionResponse.ProtoReflect.Descriptor instead.
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *StartSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartSessionResponse) GetUseRav() *v1.SignedRAV {
	if x != nil {
		return x.UseRav
	}
	return nil
}

func (x *StartSessionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *StartSessionResponse) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *StartSessionResponse) GetPricingConfig() *v1.PricingConfig {
	if x != nil {
		return x.PricingConfig
	}
	return nil
}

func (x *StartSessionResponse) GetDataPlaneEndpoint() string {
	if x != nil {
		return x.DataPlaneEndpoint
	}
	return ""
}

type SubmitRAVRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session ID
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// The signed RAV being submitted.
	// Deprecated for provider-managed runtime sessions when a live provider-issued
	// rav_request is already outstanding on PaymentSession.
	SignedRav *v1.SignedRAV `protobuf:"bytes,2,opt,name=signed_rav,json=signedRav,proto3" json:"signed_rav,omitempty"`
	// The usage this RAV covers.
	Usage         *v1.Usage `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRAVRequest) Reset() {
	*x = SubmitRAVRequest{}
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRAVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRAVRequest) ProtoMessage() {}

func (x *SubmitRAVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRAVRequest.ProtoReflect.Descriptor instead.
func (*SubmitRAVRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitRAVRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SubmitRAVRequest) GetSignedRav() *v1.SignedRAV {
	if x != nil {
		return x.SignedRav
	}
	return nil
}

func (x *SubmitRAVRequest) GetUsage() *v1.Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type SubmitRAVResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the RAV was accepted
	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// If not accepted, the reason for rejection
	RejectionReason string `protobuf:"bytes,2,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	// Whether the session should continue
	ShouldContinue bool `protobuf:"varint,3,opt,name=should_continue,json=shouldContinue,proto3" json:"should_continue,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitRAVResponse) Reset() {
	*x = SubmitRAVResponse{}
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRAVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRAVResponse) ProtoMessage() {}

func (x *SubmitRAVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRAVResponse.ProtoReflect.Descriptor instead.
func (*SubmitRAVResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitRAVResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SubmitRAVResponse) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *SubmitRAVResponse) GetShouldContinue() bool {
	if x != nil {
		return x.ShouldContinue
	}
	return false
}

// Messages from consumer sidecar to provider gateway in the bidirectional stream
type PaymentSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session ID this stream message applies to.
	// Required: the provider binds a PaymentSession stream to exactly one session.
	SessionId string `protobuf:"bytes,10,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*PaymentSessionRequest_RavSubmission
	//	*PaymentSessionRequest_FundsAck
	Message       isPaymentSessionRequest_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentSessionRequest) Reset() {
	*x = PaymentSessionRequest{}
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentSessionRequest) ProtoMessage() {}

func (x *PaymentSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentSessionRequest.ProtoReflect.Descriptor instead.
func (*PaymentSessionRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *PaymentSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PaymentSessionRequest) GetMessage() isPaymentSessionRequest_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *PaymentSessionRequest) GetRavSubmission() *SignedRAVSubmission {
	if x != nil {
		if x, ok := x.Message.(*PaymentSessionRequest_RavSubmission); ok {
			return x.RavSubmission
		}
	}
	return nil
}

func (x *PaymentSessionRequest) GetFundsAck() *FundsAcknowledgment {
	if x != nil {
		if x, ok := x.Message.(*PaymentSessionRequest_FundsAck); ok {
			return x.FundsAck
		}
	}
	return nil
}

type isPaymentSessionRequest_Message interface {
	isPaymentSessionRequest_Message()
}

type PaymentSessionRequest_RavSubmission struct {
	// Signed RAV in response to a live provider-issued rav_request.
	// This is the authoritative runtime response path for managed sessions.
	RavSubmission *SignedRAVSubmission `protobuf:"bytes,1,opt,name=rav_submission,json=ravSubmission,proto3,oneof"`
}

type PaymentSessionRequest_FundsAck struct {
	// Acknowledgment of a funds request
	FundsAck *FundsAcknowledgment `protobuf:"bytes,2,opt,name=funds_ack,json=fundsAck,proto3,oneof"`
}

func (*PaymentSessionRequest_RavSubmission) isPaymentSessionRequest_Message() {}

func (*PaymentSessionRequest_FundsAck) isPaymentSessionRequest_Message() {}

// Messages from provider gateway to consumer sidecar in the bidirectional stream
type PaymentSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*PaymentSessionResponse_RavRequest
	//	*PaymentSessionResponse_NeedMoreFunds
	//	*PaymentSessionResponse_SessionControl
	Message       isPaymentSessionResponse_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentSessionResponse) Reset() {
	*x = PaymentSessionResponse{}
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentSessionResponse) ProtoMessage() {}

func (x *PaymentSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentSessionResponse.ProtoReflect.Descriptor instead.
func (*PaymentSessionResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *PaymentSessionResponse) GetMessage() isPaymentSessionResponse_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *PaymentSessionResponse) GetRavRequest() *RAVRequest {
	if x != nil {
		if x, ok := x.Message.(*PaymentSessionResponse_RavRequest); ok {
			return x.RavRequest
		}
	}
	return nil
}

func (x *PaymentSessionResponse) GetNeedMoreFunds() *NeedMoreFunds {
	if x != nil {
		if x, ok := x.Message.(*PaymentSessionResponse_NeedMoreFunds); ok {
			return x.NeedMoreFunds
		}
	}
	return nil
}

func (x *PaymentSessionResponse) GetSessionControl() *SessionControl {
	if x != nil {
		if x, ok := x.Message.(*PaymentSessionResponse_SessionControl); ok {
			return x.SessionControl
		}
	}
	return nil
}

type isPaymentSessionResponse_Message interface {
	isPaymentSessionResponse_Message()
}

type PaymentSessionResponse_RavRequest struct {
	// Request for a new signed RAV
	RavRequest *RAVRequest `protobuf:"bytes,1,opt,name=rav_request,json=ravRequest,proto3,oneof"`
}

type PaymentSessionResponse_NeedMoreFunds struct {
	// Notification that more escrow funds are needed
	NeedMoreFunds *NeedMoreFunds `protobuf:"bytes,2,opt,name=need_more_funds,json=needMoreFunds,proto3,oneof"`
}

type PaymentSessionResponse_SessionControl struct {
	// Session control message
	SessionControl *SessionControl `protobuf:"bytes,3,opt,name=session_control,json=sessionControl,proto3,oneof"`
}

func (*PaymentSessionResponse_RavRequest) isPaymentSessionResponse_Message() {}

func (*PaymentSessionResponse_NeedMoreFunds) isPaymentSessionResponse_Message() {}

func (*PaymentSessionResponse_SessionControl) isPaymentSessionResponse_Message() {}

type SignedRAVSubmission struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The signed RAV. For provider-managed runtime sessions this must satisfy the
	// exact in-flight rav_request snapshot, not a later live usage total.
	SignedRav *v1.SignedRAV `protobuf:"bytes,1,opt,name=signed_rav,json=signedRav,proto3" json:"signed_rav,omitempty"`
	// The usage snapshot this response is satisfying. For provider-managed runtime
	// sessions this must exactly match the in-flight rav_request usage.
	Usage         *v1.Usage `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedRAVSubmission) Reset() {
	*x = SignedRAVSubmission{}
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedRAVSubmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedRAVSubmission) ProtoMessage() {}

func (x *SignedRAVSubmission) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedRAVSubmission.ProtoReflect.Descriptor instead.
func (*SignedRAVSubmission) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *SignedRAVSubmission) GetSignedRav() *v1.SignedRAV {
	if x != nil {
		return x.SignedRav
	}
	return nil
}

func (x *SignedRAVSubmission) GetUsage() *v1.Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type FundsAcknowledgment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether more funds will be deposited
	WillDeposit bool `protobuf:"varint,1,opt,name=will_deposit,json=willDeposit,proto3" json:"will_deposit,omitempty"`
	// Expected deposit amount in GRT
	DepositAmount *v1.GRT `protobuf:"bytes,2,opt,name=deposit_amount,json=depositAmount,proto3" json:"deposit_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FundsAcknowledgment) Reset() {
	*x = FundsAcknowledgment{}
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundsAcknowledgment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundsAcknowledgment) ProtoMessage() {}

func (x *FundsAcknowledgment) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundsAcknowledgment.ProtoReflect.Descriptor instead.
func (*FundsAcknowledgment) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *FundsAcknowledgment) GetWillDeposit() bool {
	if x != nil {
		return x.WillDeposit
	}
	return false
}

func (x *FundsAcknowledgment) GetDepositAmount() *v1.GRT {
	if x != nil {
		return x.DepositAmount
	}
	return nil
}

type RAVRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current RAV to extend.
	CurrentRav *v1.SignedRAV `protobuf:"bytes,1,opt,name=current_rav,json=currentRav,proto3" json:"current_rav,omitempty"`
	// The authoritative usage snapshot being requested. For provider-managed
	// runtime sessions the client must answer this exact snapshot on PaymentSession.
	Usage *v1.Usage `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	// Deadline for the RAV response (Unix timestamp)
	Deadline      uint64 `protobuf:"varint,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAVRequest) Reset() {
	*x = RAVRequest{}
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAVRequest) ProtoMessage() {}

func (x *RAVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAVRequest.ProtoReflect.Descriptor instead.
func (*RAVRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *RAVRequest) GetCurrentRav() *v1.SignedRAV {
	if x != nil {
		return x.CurrentRav
	}
	return nil
}

func (x *RAVRequest) GetUsage() *v1.Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *RAVRequest) GetDeadline() uint64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

type NeedMoreFunds struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current outstanding RAVs that will be collected
	OutstandingRavs []*v1.SignedRAV `protobuf:"bytes,1,rep,name=outstanding_ravs,json=outstandingRavs,proto3" json:"outstanding_ravs,omitempty"`
	// Total outstanding value in GRT
	TotalOutstanding *v1.GRT `protobuf:"bytes,2,opt,name=total_outstanding,json=totalOutstanding,proto3" json:"total_outstanding,omitempty"`
	// Current escrow balance in GRT
	EscrowBalance *v1.GRT `protobuf:"bytes,3,opt,name=escrow_balance,json=escrowBalance,proto3" json:"escrow_balance,omitempty"`
	// Minimum additional funds needed in GRT
	MinimumNeeded *v1.GRT `protobuf:"bytes,4,opt,name=minimum_needed,json=minimumNeeded,proto3" json:"minimum_needed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeedMoreFunds) Reset() {
	*x = NeedMoreFunds{}
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeedMoreFunds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeedMoreFunds) ProtoMessage() {}

func (x *NeedMoreFunds) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeedMoreFunds.ProtoReflect.Descriptor instead.
func (*NeedMoreFunds) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *NeedMoreFunds) GetOutstandingRavs() []*v1.SignedRAV {
	if x != nil {
		return x.OutstandingRavs
	}
	return nil
}

func (x *NeedMoreFunds) GetTotalOutstanding() *v1.GRT {
	if x != nil {
		return x.TotalOutstanding
	}
	return nil
}

func (x *NeedMoreFunds) GetEscrowBalance() *v1.GRT {
	if x != nil {
		return x.EscrowBalance
	}
	return nil
}

func (x *NeedMoreFunds) GetMinimumNeeded() *v1.GRT {
	if x != nil {
		return x.MinimumNeeded
	}
	return nil
}

type SessionControl struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Action SessionControl_Action  `protobuf:"varint,1,opt,name=action,proto3,enum=graph.substreams.data_service.provider.v1.SessionControl_Action" json:"action,omitempty"`
	// Reason for the action
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionControl) Reset() {
	*x = SessionControl{}
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionControl) ProtoMessage() {}

func (x *SessionControl) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionControl.ProtoReflect.Descriptor instead.
func (*SessionControl) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *SessionControl) GetAction() SessionControl_Action {
	if x != nil {
		return x.Action
	}
	return SessionControl_ACTION_UNSPECIFIED
}

func (x *SessionControl) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_graph_substreams_data_service_provider_v1_gateway_proto protoreflect.FileDescriptor

const file_graph_substreams_data_service_provider_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"7graph/substreams/data_service/provider/v1/gateway.proto\x12)graph.substreams.data_service.provider.v1\x1a3graph/substreams/data_service/common/v1/types.proto\"8\n" +
	"\x17GetSessionStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x9c\x02\n" +
	"\x18GetSessionStatusResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12]\n" +
	"\x0epayment_status\x18\x02 \x01(\v26.graph.substreams.data_service.common.v1.PaymentStatusR\rpaymentStatus\x12Q\n" +
	"\n" +
	"end_reason\x18\x03 \x01(\x0e22.graph.substreams.data_service.common.v1.EndReasonR\tendReason\x126\n" +
	"\x17payment_control_pending\x18\x04 \x01(\bR\x15paymentControlPending\"\xc9\x01\n" +
	"\x13StartSessionRequest\x12]\n" +
	"\x0eescrow_account\x18\x01 \x01(\v26.graph.substreams.data_service.common.v1.EscrowAccountR\rescrowAccount\x12S\n" +
	"\vinitial_rav\x18\x02 \x01(\v22.graph.substreams.data_service.common.v1.SignedRAVR\n" +
	"initialRav\"\xd8\x02\n" +
	"\x14StartSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12K\n" +
	"\ause_rav\x18\x02 \x01(\v22.graph.substreams.data_service.common.v1.SignedRAVR\x06useRav\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted\x12)\n" +
	"\x10rejection_reason\x18\x04 \x01(\tR\x0frejectionReason\x12]\n" +
	"\x0epricing_config\x18\x05 \x01(\v26.graph.substreams.data_service.common.v1.PricingConfigR\rpricingConfig\x12.\n" +
	"\x13data_plane_endpoint\x18\x06 \x01(\tR\x11dataPlaneEndpoint\"\xca\x01\n" +
	"\x10SubmitRAVRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12Q\n" +
	"\n" +
	"signed_rav\x18\x02 \x01(\v22.graph.substreams.data_service.common.v1.SignedRAVR\tsignedRav\x12D\n" +
	"\x05usage\x18\x03 \x01(\v2..graph.substreams.data_service.common.v1.UsageR\x05usage\"\x83\x01\n" +
	"\x11SubmitRAVResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12)\n" +
	"\x10rejection_reason\x18\x02 \x01(\tR\x0frejectionReason\x12'\n" +
	"\x0fshould_continue\x18\x03 \x01(\bR\x0eshouldContinue\"\x89\x02\n" +
	"\x15PaymentSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\n" +
	" \x01(\tR\tsessionId\x12g\n" +
	"\x0erav_submission\x18\x01 \x01(\v2>.graph.substreams.data_service.provider.v1.SignedRAVSubmissionH\x00R\rravSubmission\x12]\n" +
	"\tfunds_ack\x18\x02 \x01(\v2>.graph.substreams.data_service.provider.v1.FundsAcknowledgmentH\x00R\bfundsAckB\t\n" +
	"\amessage\"\xc7\x02\n" +
	"\x16PaymentSessionResponse\x12X\n" +
	"\vrav_request\x18\x01 \x01(\v25.graph.substreams.data_service.provider.v1.RAVRequestH\x00R\n" +
	"ravRequest\x12b\n" +
	"\x0fneed_more_funds\x18\x02 \x01(\v28.graph.substreams.data_service.provider.v1.NeedMoreFundsH\x00R\rneedMoreFunds\x12d\n" +
	"\x0fsession_control\x18\x03 \x01(\v29.graph.substreams.data_service.provider.v1.SessionControlH\x00R\x0esessionControlB\t\n" +
	"\amessage\"\xae\x01\n" +
	"\x13SignedRAVSubmission\x12Q\n" +
	"\n" +
	"signed_rav\x18\x01 \x01(\v22.graph.substreams.data_service.common.v1.SignedRAVR\tsignedRav\x12D\n" +
	"\x05usage\x18\x02 \x01(\v2..graph.substreams.data_service.common.v1.UsageR\x05usage\"\x8d\x01\n" +
	"\x13FundsAcknowledgment\x12!\n" +
	"\fwill_deposit\x18\x01 \x01(\bR\vwillDeposit\x12S\n" +
	"\x0edeposit_amount\x18\x02 \x01(\v2,.graph.substreams.data_service.common.v1.GRTR\rdepositAmount\"\xc3\x01\n" +
	"\n" +
	"RAVRequest\x12S\n" +
	"\vcurrent_rav\x18\x01 \x01(\v22.graph.substreams.data_service.common.v1.SignedRAVR\n" +
	"currentRav\x12D\n" +
	"\x05usage\x18\x02 \x01(\v2..graph.substreams.data_service.common.v1.UsageR\x05usage\x12\x1a\n" +
	"\bdeadline\x18\x03 \x01(\x04R\bdeadline\"\xf3\x02\n" +
	"\rNeedMoreFunds\x12]\n" +
	"\x10outstanding_ravs\x18\x01 \x03(\v22.graph.substreams.data_service.common.v1.SignedRAVR\x0foutstandingRavs\x12Y\n" +
	"\x11total_outstanding\x18\x02 \x01(\v2,.graph.substreams.data_service.common.v1.GRTR\x10totalOutstanding\x12S\n" +
	"\x0eescrow_balance\x18\x03 \x01(\v2,.graph.substreams.data_service.common.v1.GRTR\rescrowBalance\x12S\n" +
	"\x0eminimum_needed\x18\x04 \x01(\v2,.graph.substreams.data_service.common.v1.GRTR\rminimumNeeded\"\xdc\x01\n" +
	"\x0eSessionControl\x12X\n" +
	"\x06action\x18\x01 \x01(\x0e2@.graph.substreams.data_service.provider.v1.SessionControl.ActionR\x06action\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"X\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fACTION_CONTINUE\x10\x01\x12\x0f\n" +
	"\vACTION_STOP\x10\x02\x12\x10\n" +
	"\fACTION_PAUSE\x10\x032\xec\x04\n" +
	"\x15PaymentGatewayService\x12\x8f\x01\n" +
	"\fStartSession\x12>.graph.substreams.data_service.provider.v1.StartSessionRequest\x1a?.graph.substreams.data_service.provider.v1.StartSessionResponse\x12\x9b\x01\n" +
	"\x10GetSessionStatus\x12B.graph.substreams.data_service.provider.v1.GetSessionStatusRequest\x1aC.graph.substreams.data_service.provider.v1.GetSessionStatusResponse\x12\x86\x01\n" +
	"\tSubmitRAV\x12;.graph.substreams.data_service.provider.v1.SubmitRAVRequest\x1a<.graph.substreams.data_service.provider.v1.SubmitRAVResponse\x12\x99\x01\n" +
	"\x0ePaymentSession\x12@.graph.substreams.data_service.provider.v1.PaymentSessionRequest\x1aA.graph.substreams.data_service.provider.v1.PaymentSessionResponse(\x010\x01B\xec\x02\n" +
	"-com.graph.substreams.data_service.provider.v1B\fGatewayProtoP\x01Zhgithub.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/provider/v1;providerv1\xa2\x02\x04GSDP\xaa\x02(Graph.Substreams.DataService.Provider.V1\xca\x02(Graph\\Substreams\\DataService\\Provider\\V1\xe2\x024Graph\\Substreams\\DataService\\Provider\\V1\\GPBMetadata\xea\x02,Graph::Substreams::DataService::Provider::V1b\x06proto3"

var (
	file_graph_substreams_data_service_provider_v1_gateway_proto_rawDescOnce sync.Once
	file_graph_substreams_data_service_provider_v1_gateway_proto_rawDescData []byte
)

func file_graph_substreams_data_service_provider_v1_gateway_proto_rawDescGZIP() []byte {
	file_graph_substreams_data_service_provider_v1_gateway_proto_rawDescOnce.Do(func() {
		file_graph_substreams_data_service_provider_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_substreams_data_service_provider_v1_gateway_proto_rawDesc), len(file_graph_substreams_data_service_provider_v1_gateway_proto_rawDesc)))
	})
	return file_graph_substreams_data_service_provider_v1_gateway_proto_rawDescData
}

var file_graph_substreams_data_service_provider_v1_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_graph_substreams_data_service_provider_v1_gateway_proto_goTypes = []any{
	(SessionControl_Action)(0),       // 0: graph.substreams.data_service.provider.v1.SessionControl.Action
	(*GetSessionStatusRequest)(nil),  // 1: graph.substreams.data_service.provider.v1.GetSessionStatusRequest
	(*GetSessionStatusResponse)(nil), // 2: graph.substreams.data_service.provider.v1.GetSessionStatusResponse
	(*StartSessionRequest)(nil),      // 3: graph.substreams.data_service.provider.v1.StartSessionRequest
	(*StartSessionResponse)(nil),     // 4: graph.substreams.data_service.provider.v1.StartSessionResponse
	(*SubmitRAVRequest)(nil),         // 5: graph.substreams.data_service.provider.v1.SubmitRAVRequest
	(*SubmitRAVResponse)(nil),        // 6: graph.substreams.data_service.provider.v1.SubmitRAVResponse
	(*PaymentSessionRequest)(nil),    // 7: graph.substreams.data_service.provider.v1.PaymentSessionRequest
	(*PaymentSessionResponse)(nil),   // 8: graph.substreams.data_service.provider.v1.PaymentSessionResponse
	(*SignedRAVSubmission)(nil),      // 9: graph.substreams.data_service.provider.v1.SignedRAVSubmission
	(*FundsAcknowledgment)(nil),      // 10: graph.substreams.data_service.provider.v1.FundsAcknowledgment
	(*RAVRequest)(nil),               // 11: graph.substreams.data_service.provider.v1.RAVRequest
	(*NeedMoreFunds)(nil),            // 12: graph.substreams.data_service.provider.v1.NeedMoreFunds
	(*SessionControl)(nil),           // 13: graph.substreams.data_service.provider.v1.SessionControl
	(*v1.PaymentStatus)(nil),         // 14: graph.substreams.data_service.common.v1.PaymentStatus
	(v1.EndReason)(0),                // 15: graph.substreams.data_service.common.v1.EndReason
	(*v1.EscrowAccount)(nil),         // 16: graph.substreams.data_service.common.v1.EscrowAccount
	(*v1.SignedRAV)(nil),             // 17: graph.substreams.data_service.common.v1.SignedRAV
	(*v1.PricingConfig)(nil),         // 18: graph.substreams.data_service.common.v1.PricingConfig
	(*v1.Usage)(nil),                 // 19: graph.substreams.data_service.common.v1.Usage
	(*v1.GRT)(nil),                   // 20: graph.substreams.data_service.common.v1.GRT
}
var file_graph_substreams_data_service_provider_v1_gateway_proto_depIdxs = []int32{
	14, // 0: graph.substreams.data_service.provider.v1.GetSessionStatusResponse.payment_status:type_name -> graph.substreams.data_service.common.v1.PaymentStatus
	15, // 1: graph.substreams.data_service.provider.v1.GetSessionStatusResponse.end_reason:type_name -> graph.substreams.data_service.common.v1.EndReason
	16, // 2: graph.substreams.data_service.provider.v1.StartSessionRequest.escrow_account:type_name -> graph.substreams.data_service.common.v1.EscrowAccount
	17, // 3: graph.substreams.data_service.provider.v1.StartSessionRequest.initial_rav:type_name -> graph.substreams.data_service.common.v1.SignedRAV
	17, // 4: graph.substreams.data_service.provider.v1.StartSessionResponse.use_rav:type_name -> graph.substreams.data_service.common.v1.SignedRAV
	18, // 5: graph.substreams.data_service.provider.v1.StartSessionResponse.pricing_config:type_name -> graph.substreams.data_service.common.v1.PricingConfig
	17, // 6: graph.substreams.data_service.provider.v1.SubmitRAVRequest.signed_rav:type_name -> graph.substreams.data_service.common.v1.SignedRAV
	19, // 7: graph.substreams.data_service.provider.v1.SubmitRAVRequest.usage:type_name -> graph.substreams.data_service.common.v1.Usage
	9,  // 8: graph.substreams.data_service.provider.v1.PaymentSessionRequest.rav_submission:type_name -> graph.substreams.data_service.provider.v1.SignedRAVSubmission
	10, // 9: graph.substreams.data_service.provider.v1.PaymentSessionRequest.funds_ack:type_name -> graph.substreams.data_service.provider.v1.FundsAcknowledgment
	11, // 10: graph.substreams.data_service.provider.v1.PaymentSessionResponse.rav_request:type_name -> graph.substreams.data_service.provider.v1.RAVRequest
	12, // 11: graph.substreams.data_service.provider.v1.PaymentSessionResponse.need_more_funds:type_name -> graph.substreams.data_service.provider.v1.NeedMoreFunds
	13, // 12: graph.substreams.data_service.provider.v1.PaymentSessionResponse.session_control:type_name -> graph.substreams.data_service.provider.v1.SessionControl
	17, // 13: graph.substreams.data_service.provider.v1.SignedRAVSubmission.signed_rav:type_name -> graph.substreams.data_service.common.v1.SignedRAV
	19, // 14: graph.substreams.data_service.provider.v1.SignedRAVSubmission.usage:type_name -> graph.substreams.data_service.common.v1.Usage
	20, // 15: graph.substreams.data_service.provider.v1.FundsAcknowledgment.deposit_amount:type_name -> graph.substreams.data_service.common.v1.GRT
	17, // 16: graph.substreams.data_service.provider.v1.RAVRequest.current_rav:type_name -> graph.substreams.data_service.common.v1.SignedRAV
	19, // 17: graph.substreams.data_service.provider.v1.RAVRequest.usage:type_name -> graph.substreams.data_service.common.v1.Usage
	17, // 18: graph.substreams.data_service.provider.v1.NeedMoreFunds.outstanding_ravs:type_name -> graph.substreams.data_service.common.v1.SignedRAV
	20, // 19: graph.substreams.data_service.provider.v1.NeedMoreFunds.total_outstanding:type_name -> graph.substreams.data_service.common.v1.GRT
	20, // 20: graph.substreams.data_service.provider.v1.NeedMoreFunds.escrow_balance:type_name -> graph.substreams.data_service.common.v1.GRT
	20, // 21: graph.substreams.data_service.provider.v1.NeedMoreFunds.minimum_needed:type_name -> graph.substreams.data_service.common.v1.GRT
	0,  // 22: graph.substreams.data_service.provider.v1.SessionControl.action:type_name -> graph.substreams.data_service.provider.v1.SessionControl.Action
	3,  // 23: graph.substreams.data_service.provider.v1.PaymentGatewayService.StartSession:input_type -> graph.substreams.data_service.provider.v1.StartSessionRequest
	1,  // 24: graph.substreams.data_service.provider.v1.PaymentGatewayService.GetSessionStatus:input_type -> graph.substreams.data_service.provider.v1.GetSessionStatusRequest
	5,  // 25: graph.substreams.data_service.provider.v1.PaymentGatewayService.SubmitRAV:input_type -> graph.substreams.data_service.provider.v1.SubmitRAVRequest
	7,  // 26: graph.substreams.data_service.provider.v1.PaymentGatewayService.PaymentSession:input_type -> graph.substreams.data_service.provider.v1.PaymentSessionRequest
	4,  // 27: graph.substreams.data_service.provider.v1.PaymentGatewayService.StartSession:output_type -> graph.substreams.data_service.provider.v1.StartSessionResponse
	2,  // 28: graph.substreams.data_service.provider.v1.PaymentGatewayService.GetSessionStatus:output_type -> graph.substreams.data_service.provider.v1.GetSessionStatusResponse
	6,  // 29: graph.substreams.data_service.provider.v1.PaymentGatewayService.SubmitRAV:output_type -> graph.substreams.data_service.provider.v1.SubmitRAVResponse
	8,  // 30: graph.substreams.data_service.provider.v1.PaymentGatewayService.PaymentSession:output_type -> graph.substreams.data_service.provider.v1.PaymentSessionResponse
	27, // [27:31] is the sub-list for method output_type
	23, // [23:27] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_graph_substreams_data_service_provider_v1_gateway_proto_init() }
func file_graph_substreams_data_service_provider_v1_gateway_proto_init() {
	if File_graph_substreams_data_service_provider_v1_gateway_proto != nil {
		return
	}
	file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[6].OneofWrappers = []any{
		(*PaymentSessionRequest_RavSubmission)(nil),
		(*PaymentSessionRequest_FundsAck)(nil),
	}
	file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes[7].OneofWrappers = []any{
		(*PaymentSessionResponse_RavRequest)(nil),
		(*PaymentSessionResponse_NeedMoreFunds)(nil),
		(*PaymentSessionResponse_SessionControl)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_substreams_data_service_provider_v1_gateway_proto_rawDesc), len(file_graph_substreams_data_service_provider_v1_gateway_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graph_substreams_data_service_provider_v1_gateway_proto_goTypes,
		DependencyIndexes: file_graph_substreams_data_service_provider_v1_gateway_proto_depIdxs,
		EnumInfos:         file_graph_substreams_data_service_provider_v1_gateway_proto_enumTypes,
		MessageInfos:      file_graph_substreams_data_service_provider_v1_gateway_proto_msgTypes,
	}.Build()
	File_graph_substreams_data_service_provider_v1_gateway_proto = out.File
	file_graph_substreams_data_service_provider_v1_gateway_proto_goTypes = nil
	file_graph_substreams_data_service_provider_v1_gateway_proto_depIdxs = nil
}
