// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: graph/substreams/data_service/provider/v1/operator.proto

package providerv1

import (
	v1 "github.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperatorSessionStatus int32

const (
	OperatorSessionStatus_OPERATOR_SESSION_STATUS_UNSPECIFIED OperatorSessionStatus = 0
	OperatorSessionStatus_OPERATOR_SESSION_STATUS_ACTIVE      OperatorSessionStatus = 1
	OperatorSessionStatus_OPERATOR_SESSION_STATUS_PAUSED      OperatorSessionStatus = 2
	OperatorSessionStatus_OPERATOR_SESSION_STATUS_TERMINATED  OperatorSessionStatus = 3
)

// Enum value maps for OperatorSessionStatus.
var (
	OperatorSessionStatus_name = map[int32]string{
		0: "OPERATOR_SESSION_STATUS_UNSPECIFIED",
		1: "OPERATOR_SESSION_STATUS_ACTIVE",
		2: "OPERATOR_SESSION_STATUS_PAUSED",
		3: "OPERATOR_SESSION_STATUS_TERMINATED",
	}
	OperatorSessionStatus_value = map[string]int32{
		"OPERATOR_SESSION_STATUS_UNSPECIFIED": 0,
		"OPERATOR_SESSION_STATUS_ACTIVE":      1,
		"OPERATOR_SESSION_STATUS_PAUSED":      2,
		"OPERATOR_SESSION_STATUS_TERMINATED":  3,
	}
)

func (x OperatorSessionStatus) Enum() *OperatorSessionStatus {
	p := new(OperatorSessionStatus)
	*p = x
	return p
}

func (x OperatorSessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperatorSessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_graph_substreams_data_service_provider_v1_operator_proto_enumTypes[0].Descriptor()
}

func (OperatorSessionStatus) Type() protoreflect.EnumType {
	return &file_graph_substreams_data_service_provider_v1_operator_proto_enumTypes[0]
}

func (x OperatorSessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperatorSessionStatus.Descriptor instead.
func (OperatorSessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{0}
}

type CollectionState int32

const (
	CollectionState_COLLECTION_STATE_UNSPECIFIED              CollectionState = 0
	CollectionState_COLLECTION_STATE_COLLECTIBLE              CollectionState = 1
	CollectionState_COLLECTION_STATE_COLLECT_PENDING          CollectionState = 2
	CollectionState_COLLECTION_STATE_COLLECTED                CollectionState = 3
	CollectionState_COLLECTION_STATE_COLLECT_FAILED_RETRYABLE CollectionState = 4
)

// Enum value maps for CollectionState.
var (
	CollectionState_name = map[int32]string{
		0: "COLLECTION_STATE_UNSPECIFIED",
		1: "COLLECTION_STATE_COLLECTIBLE",
		2: "COLLECTION_STATE_COLLECT_PENDING",
		3: "COLLECTION_STATE_COLLECTED",
		4: "COLLECTION_STATE_COLLECT_FAILED_RETRYABLE",
	}
	CollectionState_value = map[string]int32{
		"COLLECTION_STATE_UNSPECIFIED":              0,
		"COLLECTION_STATE_COLLECTIBLE":              1,
		"COLLECTION_STATE_COLLECT_PENDING":          2,
		"COLLECTION_STATE_COLLECTED":                3,
		"COLLECTION_STATE_COLLECT_FAILED_RETRYABLE": 4,
	}
)

func (x CollectionState) Enum() *CollectionState {
	p := new(CollectionState)
	*p = x
	return p
}

func (x CollectionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CollectionState) Descriptor() protoreflect.EnumDescriptor {
	return file_graph_substreams_data_service_provider_v1_operator_proto_enumTypes[1].Descriptor()
}

func (CollectionState) Type() protoreflect.EnumType {
	return &file_graph_substreams_data_service_provider_v1_operator_proto_enumTypes[1]
}

func (x CollectionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CollectionState.Descriptor instead.
func (CollectionState) EnumDescriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{1}
}

type OperatorFundsStatus int32

const (
	OperatorFundsStatus_OPERATOR_FUNDS_STATUS_UNSPECIFIED  OperatorFundsStatus = 0
	OperatorFundsStatus_OPERATOR_FUNDS_STATUS_OK           OperatorFundsStatus = 1
	OperatorFundsStatus_OPERATOR_FUNDS_STATUS_INSUFFICIENT OperatorFundsStatus = 2
	OperatorFundsStatus_OPERATOR_FUNDS_STATUS_UNKNOWN      OperatorFundsStatus = 3
)

// Enum value maps for OperatorFundsStatus.
var (
	OperatorFundsStatus_name = map[int32]string{
		0: "OPERATOR_FUNDS_STATUS_UNSPECIFIED",
		1: "OPERATOR_FUNDS_STATUS_OK",
		2: "OPERATOR_FUNDS_STATUS_INSUFFICIENT",
		3: "OPERATOR_FUNDS_STATUS_UNKNOWN",
	}
	OperatorFundsStatus_value = map[string]int32{
		"OPERATOR_FUNDS_STATUS_UNSPECIFIED":  0,
		"OPERATOR_FUNDS_STATUS_OK":           1,
		"OPERATOR_FUNDS_STATUS_INSUFFICIENT": 2,
		"OPERATOR_FUNDS_STATUS_UNKNOWN":      3,
	}
)

func (x OperatorFundsStatus) Enum() *OperatorFundsStatus {
	p := new(OperatorFundsStatus)
	*p = x
	return p
}

func (x OperatorFundsStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperatorFundsStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_graph_substreams_data_service_provider_v1_operator_proto_enumTypes[2].Descriptor()
}

func (OperatorFundsStatus) Type() protoreflect.EnumType {
	return &file_graph_substreams_data_service_provider_v1_operator_proto_enumTypes[2]
}

func (x OperatorFundsStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperatorFundsStatus.Descriptor instead.
func (OperatorFundsStatus) EnumDescriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{2}
}

type CollectionKey struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CollectionId    []byte                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Payer           *v1.Address            `protobuf:"bytes,3,opt,name=payer,proto3" json:"payer,omitempty"`
	ServiceProvider *v1.Address            `protobuf:"bytes,4,opt,name=service_provider,json=serviceProvider,proto3" json:"service_provider,omitempty"`
	DataService     *v1.Address            `protobuf:"bytes,5,opt,name=data_service,json=dataService,proto3" json:"data_service,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CollectionKey) Reset() {
	*x = CollectionKey{}
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionKey) ProtoMessage() {}

func (x *CollectionKey) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionKey.ProtoReflect.Descriptor instead.
func (*CollectionKey) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{0}
}

func (x *CollectionKey) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CollectionKey) GetCollectionId() []byte {
	if x != nil {
		return x.CollectionId
	}
	return nil
}

func (x *CollectionKey) GetPayer() *v1.Address {
	if x != nil {
		return x.Payer
	}
	return nil
}

func (x *CollectionKey) GetServiceProvider() *v1.Address {
	if x != nil {
		return x.ServiceProvider
	}
	return nil
}

func (x *CollectionKey) GetDataService() *v1.Address {
	if x != nil {
		return x.DataService
	}
	return nil
}

type OperatorPaymentState struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PaymentStatus        *v1.PaymentStatus      `protobuf:"bytes,1,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	FundsStatus          OperatorFundsStatus    `protobuf:"varint,2,opt,name=funds_status,json=fundsStatus,proto3,enum=graph.substreams.data_service.provider.v1.OperatorFundsStatus" json:"funds_status,omitempty"`
	CurrentOutstanding   *v1.GRT                `protobuf:"bytes,3,opt,name=current_outstanding,json=currentOutstanding,proto3" json:"current_outstanding,omitempty"`
	ProjectedOutstanding *v1.GRT                `protobuf:"bytes,4,opt,name=projected_outstanding,json=projectedOutstanding,proto3" json:"projected_outstanding,omitempty"`
	MinimumNeeded        *v1.GRT                `protobuf:"bytes,5,opt,name=minimum_needed,json=minimumNeeded,proto3" json:"minimum_needed,omitempty"`
	FundsCheckError      string                 `protobuf:"bytes,6,opt,name=funds_check_error,json=fundsCheckError,proto3" json:"funds_check_error,omitempty"`
	OperatorHint         string                 `protobuf:"bytes,7,opt,name=operator_hint,json=operatorHint,proto3" json:"operator_hint,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OperatorPaymentState) Reset() {
	*x = OperatorPaymentState{}
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorPaymentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorPaymentState) ProtoMessage() {}

func (x *OperatorPaymentState) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorPaymentState.ProtoReflect.Descriptor instead.
func (*OperatorPaymentState) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{1}
}

func (x *OperatorPaymentState) GetPaymentStatus() *v1.PaymentStatus {
	if x != nil {
		return x.PaymentStatus
	}
	return nil
}

func (x *OperatorPaymentState) GetFundsStatus() OperatorFundsStatus {
	if x != nil {
		return x.FundsStatus
	}
	return OperatorFundsStatus_OPERATOR_FUNDS_STATUS_UNSPECIFIED
}

func (x *OperatorPaymentState) GetCurrentOutstanding() *v1.GRT {
	if x != nil {
		return x.CurrentOutstanding
	}
	return nil
}

func (x *OperatorPaymentState) GetProjectedOutstanding() *v1.GRT {
	if x != nil {
		return x.ProjectedOutstanding
	}
	return nil
}

func (x *OperatorPaymentState) GetMinimumNeeded() *v1.GRT {
	if x != nil {
		return x.MinimumNeeded
	}
	return nil
}

func (x *OperatorPaymentState) GetFundsCheckError() string {
	if x != nil {
		return x.FundsCheckError
	}
	return ""
}

func (x *OperatorPaymentState) GetOperatorHint() string {
	if x != nil {
		return x.OperatorHint
	}
	return ""
}

type OperatorSession struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SessionId             string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status                OperatorSessionStatus  `protobuf:"varint,2,opt,name=status,proto3,enum=graph.substreams.data_service.provider.v1.OperatorSessionStatus" json:"status,omitempty"`
	Payer                 *v1.Address            `protobuf:"bytes,3,opt,name=payer,proto3" json:"payer,omitempty"`
	Receiver              *v1.Address            `protobuf:"bytes,4,opt,name=receiver,proto3" json:"receiver,omitempty"`
	DataService           *v1.Address            `protobuf:"bytes,5,opt,name=data_service,json=dataService,proto3" json:"data_service,omitempty"`
	CreatedAtNs           uint64                 `protobuf:"varint,6,opt,name=created_at_ns,json=createdAtNs,proto3" json:"created_at_ns,omitempty"`
	UpdatedAtNs           uint64                 `protobuf:"varint,7,opt,name=updated_at_ns,json=updatedAtNs,proto3" json:"updated_at_ns,omitempty"`
	EndedAtNs             uint64                 `protobuf:"varint,8,opt,name=ended_at_ns,json=endedAtNs,proto3" json:"ended_at_ns,omitempty"`
	EndReason             v1.EndReason           `protobuf:"varint,9,opt,name=end_reason,json=endReason,proto3,enum=graph.substreams.data_service.common.v1.EndReason" json:"end_reason,omitempty"`
	AccumulatedUsage      *v1.Usage              `protobuf:"bytes,10,opt,name=accumulated_usage,json=accumulatedUsage,proto3" json:"accumulated_usage,omitempty"`
	BaselineUsage         *v1.Usage              `protobuf:"bytes,11,opt,name=baseline_usage,json=baselineUsage,proto3" json:"baseline_usage,omitempty"`
	PaymentControlPending bool                   `protobuf:"varint,12,opt,name=payment_control_pending,json=paymentControlPending,proto3" json:"payment_control_pending,omitempty"`
	AcceptedRav           *AcceptedRAV           `protobuf:"bytes,13,opt,name=accepted_rav,json=acceptedRav,proto3" json:"accepted_rav,omitempty"`
	PaymentState          *OperatorPaymentState  `protobuf:"bytes,14,opt,name=payment_state,json=paymentState,proto3" json:"payment_state,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *OperatorSession) Reset() {
	*x = OperatorSession{}
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorSession) ProtoMessage() {}

func (x *OperatorSession) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorSession.ProtoReflect.Descriptor instead.
func (*OperatorSession) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{2}
}

func (x *OperatorSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *OperatorSession) GetStatus() OperatorSessionStatus {
	if x != nil {
		return x.Status
	}
	return OperatorSessionStatus_OPERATOR_SESSION_STATUS_UNSPECIFIED
}

func (x *OperatorSession) GetPayer() *v1.Address {
	if x != nil {
		return x.Payer
	}
	return nil
}

func (x *OperatorSession) GetReceiver() *v1.Address {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *OperatorSession) GetDataService() *v1.Address {
	if x != nil {
		return x.DataService
	}
	return nil
}

func (x *OperatorSession) GetCreatedAtNs() uint64 {
	if x != nil {
		return x.CreatedAtNs
	}
	return 0
}

func (x *OperatorSession) GetUpdatedAtNs() uint64 {
	if x != nil {
		return x.UpdatedAtNs
	}
	return 0
}

func (x *OperatorSession) GetEndedAtNs() uint64 {
	if x != nil {
		return x.EndedAtNs
	}
	return 0
}

func (x *OperatorSession) GetEndReason() v1.EndReason {
	if x != nil {
		return x.EndReason
	}
	return v1.EndReason(0)
}

func (x *OperatorSession) GetAccumulatedUsage() *v1.Usage {
	if x != nil {
		return x.AccumulatedUsage
	}
	return nil
}

func (x *OperatorSession) GetBaselineUsage() *v1.Usage {
	if x != nil {
		return x.BaselineUsage
	}
	return nil
}

func (x *OperatorSession) GetPaymentControlPending() bool {
	if x != nil {
		return x.PaymentControlPending
	}
	return false
}

func (x *OperatorSession) GetAcceptedRav() *AcceptedRAV {
	if x != nil {
		return x.AcceptedRav
	}
	return nil
}

func (x *OperatorSession) GetPaymentState() *OperatorPaymentState {
	if x != nil {
		return x.PaymentState
	}
	return nil
}

type AcceptedRAV struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CollectionId    []byte                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Payer           *v1.Address            `protobuf:"bytes,3,opt,name=payer,proto3" json:"payer,omitempty"`
	ServiceProvider *v1.Address            `protobuf:"bytes,4,opt,name=service_provider,json=serviceProvider,proto3" json:"service_provider,omitempty"`
	DataService     *v1.Address            `protobuf:"bytes,5,opt,name=data_service,json=dataService,proto3" json:"data_service,omitempty"`
	TimestampNs     uint64                 `protobuf:"varint,6,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	ValueAggregate  *v1.GRT                `protobuf:"bytes,7,opt,name=value_aggregate,json=valueAggregate,proto3" json:"value_aggregate,omitempty"`
	SignedRav       *v1.SignedRAV          `protobuf:"bytes,8,opt,name=signed_rav,json=signedRav,proto3" json:"signed_rav,omitempty"`
	CollectionState CollectionState        `protobuf:"varint,9,opt,name=collection_state,json=collectionState,proto3,enum=graph.substreams.data_service.provider.v1.CollectionState" json:"collection_state,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AcceptedRAV) Reset() {
	*x = AcceptedRAV{}
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptedRAV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedRAV) ProtoMessage() {}

func (x *AcceptedRAV) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedRAV.ProtoReflect.Descriptor instead.
func (*AcceptedRAV) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptedRAV) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AcceptedRAV) GetCollectionId() []byte {
	if x != nil {
		return x.CollectionId
	}
	return nil
}

func (x *AcceptedRAV) GetPayer() *v1.Address {
	if x != nil {
		return x.Payer
	}
	return nil
}

func (x *AcceptedRAV) GetServiceProvider() *v1.Address {
	if x != nil {
		return x.ServiceProvider
	}
	return nil
}

func (x *AcceptedRAV) GetDataService() *v1.Address {
	if x != nil {
		return x.DataService
	}
	return nil
}

func (x *AcceptedRAV) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *AcceptedRAV) GetValueAggregate() *v1.GRT {
	if x != nil {
		return x.ValueAggregate
	}
	return nil
}

func (x *AcceptedRAV) GetSignedRav() *v1.SignedRAV {
	if x != nil {
		return x.SignedRav
	}
	return nil
}

func (x *AcceptedRAV) GetCollectionState() CollectionState {
	if x != nil {
		return x.CollectionState
	}
	return CollectionState_COLLECTION_STATE_UNSPECIFIED
}

type CollectionRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Key             *CollectionKey         `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	State           CollectionState        `protobuf:"varint,2,opt,name=state,proto3,enum=graph.substreams.data_service.provider.v1.CollectionState" json:"state,omitempty"`
	SignedRav       *v1.SignedRAV          `protobuf:"bytes,3,opt,name=signed_rav,json=signedRav,proto3" json:"signed_rav,omitempty"`
	ValueAggregate  *v1.GRT                `protobuf:"bytes,4,opt,name=value_aggregate,json=valueAggregate,proto3" json:"value_aggregate,omitempty"`
	AttemptCount    uint64                 `protobuf:"varint,5,opt,name=attempt_count,json=attemptCount,proto3" json:"attempt_count,omitempty"`
	LastTxHash      string                 `protobuf:"bytes,6,opt,name=last_tx_hash,json=lastTxHash,proto3" json:"last_tx_hash,omitempty"`
	LastError       string                 `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	CollectedAmount *v1.GRT                `protobuf:"bytes,8,opt,name=collected_amount,json=collectedAmount,proto3" json:"collected_amount,omitempty"`
	CreatedAtNs     uint64                 `protobuf:"varint,9,opt,name=created_at_ns,json=createdAtNs,proto3" json:"created_at_ns,omitempty"`
	UpdatedAtNs     uint64                 `protobuf:"varint,10,opt,name=updated_at_ns,json=updatedAtNs,proto3" json:"updated_at_ns,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CollectionRecord) Reset() {
	*x = CollectionRecord{}
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionRecord) ProtoMessage() {}

func (x *CollectionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionRecord.ProtoReflect.Descriptor instead.
func (*CollectionRecord) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{4}
}

func (x *CollectionRecord) GetKey() *CollectionKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CollectionRecord) GetState() CollectionState {
	if x != nil {
		return x.State
	}
	return CollectionState_COLLECTION_STATE_UNSPECIFIED
}

func (x *CollectionRecord) GetSignedRav() *v1.SignedRAV {
	if x != nil {
		return x.SignedRav
	}
	return nil
}

func (x *CollectionRecord) GetValueAggregate() *v1.GRT {
	if x != nil {
		return x.ValueAggregate
	}
	return nil
}

func (x *CollectionRecord) GetAttemptCount() uint64 {
	if x != nil {
		return x.AttemptCount
	}
	return 0
}

func (x *CollectionRecord) GetLastTxHash() string {
	if x != nil {
		return x.LastTxHash
	}
	return ""
}

func (x *CollectionRecord) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *CollectionRecord) GetCollectedAmount() *v1.GRT {
	if x != nil {
		return x.CollectedAmount
	}
	return nil
}

func (x *CollectionRecord) GetCreatedAtNs() uint64 {
	if x != nil {
		return x.CreatedAtNs
	}
	return 0
}

func (x *CollectionRecord) GetUpdatedAtNs() uint64 {
	if x != nil {
		return x.UpdatedAtNs
	}
	return 0
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Status        OperatorSessionStatus  `protobuf:"varint,2,opt,name=status,proto3,enum=graph.substreams.data_service.provider.v1.OperatorSessionStatus" json:"status,omitempty"`
	Payer         *v1.Address            `protobuf:"bytes,3,opt,name=payer,proto3" json:"payer,omitempty"`
	Receiver      *v1.Address            `protobuf:"bytes,4,opt,name=receiver,proto3" json:"receiver,omitempty"`
	DataService   *v1.Address            `protobuf:"bytes,5,opt,name=data_service,json=dataService,proto3" json:"data_service,omitempty"`
	IncludeRav    bool                   `protobuf:"varint,6,opt,name=include_rav,json=includeRav,proto3" json:"include_rav,omitempty"`
	FundsStatus   OperatorFundsStatus    `protobuf:"varint,7,opt,name=funds_status,json=fundsStatus,proto3,enum=graph.substreams.data_service.provider.v1.OperatorFundsStatus" json:"funds_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{5}
}

func (x *ListSessionsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSessionsRequest) GetStatus() OperatorSessionStatus {
	if x != nil {
		return x.Status
	}
	return OperatorSessionStatus_OPERATOR_SESSION_STATUS_UNSPECIFIED
}

func (x *ListSessionsRequest) GetPayer() *v1.Address {
	if x != nil {
		return x.Payer
	}
	return nil
}

func (x *ListSessionsRequest) GetReceiver() *v1.Address {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *ListSessionsRequest) GetDataService() *v1.Address {
	if x != nil {
		return x.DataService
	}
	return nil
}

func (x *ListSessionsRequest) GetIncludeRav() bool {
	if x != nil {
		return x.IncludeRav
	}
	return false
}

func (x *ListSessionsRequest) GetFundsStatus() OperatorFundsStatus {
	if x != nil {
		return x.FundsStatus
	}
	return OperatorFundsStatus_OPERATOR_FUNDS_STATUS_UNSPECIFIED
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*OperatorSession     `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{6}
}

func (x *ListSessionsResponse) GetSessions() []*OperatorSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	IncludeRav    bool                   `protobuf:"varint,2,opt,name=include_rav,json=includeRav,proto3" json:"include_rav,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{7}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionRequest) GetIncludeRav() bool {
	if x != nil {
		return x.IncludeRav
	}
	return false
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *OperatorSession       `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{8}
}

func (x *GetSessionResponse) GetSession() *OperatorSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type ListAcceptedRAVsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Limit           uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	SessionId       string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CollectionId    []byte                 `protobuf:"bytes,3,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Payer           *v1.Address            `protobuf:"bytes,4,opt,name=payer,proto3" json:"payer,omitempty"`
	ServiceProvider *v1.Address            `protobuf:"bytes,5,opt,name=service_provider,json=serviceProvider,proto3" json:"service_provider,omitempty"`
	DataService     *v1.Address            `protobuf:"bytes,6,opt,name=data_service,json=dataService,proto3" json:"data_service,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListAcceptedRAVsRequest) Reset() {
	*x = ListAcceptedRAVsRequest{}
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAcceptedRAVsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAcceptedRAVsRequest) ProtoMessage() {}

func (x *ListAcceptedRAVsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAcceptedRAVsRequest.ProtoReflect.Descriptor instead.
func (*ListAcceptedRAVsRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{9}
}

func (x *ListAcceptedRAVsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAcceptedRAVsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ListAcceptedRAVsRequest) GetCollectionId() []byte {
	if x != nil {
		return x.CollectionId
	}
	return nil
}

func (x *ListAcceptedRAVsRequest) GetPayer() *v1.Address {
	if x != nil {
		return x.Payer
	}
	return nil
}

func (x *ListAcceptedRAVsRequest) GetServiceProvider() *v1.Address {
	if x != nil {
		return x.ServiceProvider
	}
	return nil
}

func (x *ListAcceptedRAVsRequest) GetDataService() *v1.Address {
	if x != nil {
		return x.DataService
	}
	return nil
}

type ListAcceptedRAVsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ravs          []*AcceptedRAV         `protobuf:"bytes,1,rep,name=ravs,proto3" json:"ravs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAcceptedRAVsResponse) Reset() {
	*x = ListAcceptedRAVsResponse{}
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAcceptedRAVsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAcceptedRAVsResponse) ProtoMessage() {}

func (x *ListAcceptedRAVsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAcceptedRAVsResponse.ProtoReflect.Descriptor instead.
func (*ListAcceptedRAVsResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{10}
}

func (x *ListAcceptedRAVsResponse) GetRavs() []*AcceptedRAV {
	if x != nil {
		return x.Ravs
	}
	return nil
}

type GetAcceptedRAVRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAcceptedRAVRequest) Reset() {
	*x = GetAcceptedRAVRequest{}
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAcceptedRAVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAcceptedRAVRequest) ProtoMessage() {}

func (x *GetAcceptedRAVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAcceptedRAVRequest.ProtoReflect.Descriptor instead.
func (*GetAcceptedRAVRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{11}
}

func (x *GetAcceptedRAVRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetAcceptedRAVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rav           *AcceptedRAV           `protobuf:"bytes,1,opt,name=rav,proto3" json:"rav,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAcceptedRAVResponse) Reset() {
	*x = GetAcceptedRAVResponse{}
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAcceptedRAVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAcceptedRAVResponse) ProtoMessage() {}

func (x *GetAcceptedRAVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAcceptedRAVResponse.ProtoReflect.Descriptor instead.
func (*GetAcceptedRAVResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{12}
}

func (x *GetAcceptedRAVResponse) GetRav() *AcceptedRAV {
	if x != nil {
		return x.Rav
	}
	return nil
}

type ListCollectionsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Limit           uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	SessionId       string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	State           CollectionState        `protobuf:"varint,3,opt,name=state,proto3,enum=graph.substreams.data_service.provider.v1.CollectionState" json:"state,omitempty"`
	Payer           *v1.Address            `protobuf:"bytes,4,opt,name=payer,proto3" json:"payer,omitempty"`
	ServiceProvider *v1.Address            `protobuf:"bytes,5,opt,name=service_provider,json=serviceProvider,proto3" json:"service_provider,omitempty"`
	DataService     *v1.Address            `protobuf:"bytes,6,opt,name=data_service,json=dataService,proto3" json:"data_service,omitempty"`
	CollectionId    []byte                 `protobuf:"bytes,7,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListCollectionsRequest) Reset() {
	*x = ListCollectionsRequest{}
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsRequest) ProtoMessage() {}

func (x *ListCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{13}
}

func (x *ListCollectionsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCollectionsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ListCollectionsRequest) GetState() CollectionState {
	if x != nil {
		return x.State
	}
	return CollectionState_COLLECTION_STATE_UNSPECIFIED
}

func (x *ListCollectionsRequest) GetPayer() *v1.Address {
	if x != nil {
		return x.Payer
	}
	return nil
}

func (x *ListCollectionsRequest) GetServiceProvider() *v1.Address {
	if x != nil {
		return x.ServiceProvider
	}
	return nil
}

func (x *ListCollectionsRequest) GetDataService() *v1.Address {
	if x != nil {
		return x.DataService
	}
	return nil
}

func (x *ListCollectionsRequest) GetCollectionId() []byte {
	if x != nil {
		return x.CollectionId
	}
	return nil
}

type ListCollectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collections   []*CollectionRecord    `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResponse) Reset() {
	*x = ListCollectionsResponse{}
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResponse) ProtoMessage() {}

func (x *ListCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{14}
}

func (x *ListCollectionsResponse) GetCollections() []*CollectionRecord {
	if x != nil {
		return x.Collections
	}
	return nil
}

type GetCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *CollectionKey         `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionRequest) Reset() {
	*x = GetCollectionRequest{}
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionRequest) ProtoMessage() {}

func (x *GetCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionRequest.ProtoReflect.Descriptor instead.
func (*GetCollectionRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{15}
}

func (x *GetCollectionRequest) GetKey() *CollectionKey {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    *CollectionRecord      `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionResponse) Reset() {
	*x = GetCollectionResponse{}
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionResponse) ProtoMessage() {}

func (x *GetCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionResponse.ProtoReflect.Descriptor instead.
func (*GetCollectionResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{16}
}

func (x *GetCollectionResponse) GetCollection() *CollectionRecord {
	if x != nil {
		return x.Collection
	}
	return nil
}

type MarkCollectionPendingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *CollectionKey         `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ExpectedValue *v1.GRT                `protobuf:"bytes,2,opt,name=expected_value,json=expectedValue,proto3" json:"expected_value,omitempty"`
	TxHash        string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkCollectionPendingRequest) Reset() {
	*x = MarkCollectionPendingRequest{}
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkCollectionPendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkCollectionPendingRequest) ProtoMessage() {}

func (x *MarkCollectionPendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkCollectionPendingRequest.ProtoReflect.Descriptor instead.
func (*MarkCollectionPendingRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{17}
}

func (x *MarkCollectionPendingRequest) GetKey() *CollectionKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MarkCollectionPendingRequest) GetExpectedValue() *v1.GRT {
	if x != nil {
		return x.ExpectedValue
	}
	return nil
}

func (x *MarkCollectionPendingRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type MarkCollectionPendingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    *CollectionRecord      `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkCollectionPendingResponse) Reset() {
	*x = MarkCollectionPendingResponse{}
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkCollectionPendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkCollectionPendingResponse) ProtoMessage() {}

func (x *MarkCollectionPendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkCollectionPendingResponse.ProtoReflect.Descriptor instead.
func (*MarkCollectionPendingResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{18}
}

func (x *MarkCollectionPendingResponse) GetCollection() *CollectionRecord {
	if x != nil {
		return x.Collection
	}
	return nil
}

type MarkCollectionCollectedRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Key             *CollectionKey         `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ExpectedValue   *v1.GRT                `protobuf:"bytes,2,opt,name=expected_value,json=expectedValue,proto3" json:"expected_value,omitempty"`
	TxHash          string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	CollectedAmount *v1.GRT                `protobuf:"bytes,4,opt,name=collected_amount,json=collectedAmount,proto3" json:"collected_amount,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MarkCollectionCollectedRequest) Reset() {
	*x = MarkCollectionCollectedRequest{}
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkCollectionCollectedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkCollectionCollectedRequest) ProtoMessage() {}

func (x *MarkCollectionCollectedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkCollectionCollectedRequest.ProtoReflect.Descriptor instead.
func (*MarkCollectionCollectedRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{19}
}

func (x *MarkCollectionCollectedRequest) GetKey() *CollectionKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MarkCollectionCollectedRequest) GetExpectedValue() *v1.GRT {
	if x != nil {
		return x.ExpectedValue
	}
	return nil
}

func (x *MarkCollectionCollectedRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *MarkCollectionCollectedRequest) GetCollectedAmount() *v1.GRT {
	if x != nil {
		return x.CollectedAmount
	}
	return nil
}

type MarkCollectionCollectedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    *CollectionRecord      `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkCollectionCollectedResponse) Reset() {
	*x = MarkCollectionCollectedResponse{}
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkCollectionCollectedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkCollectionCollectedResponse) ProtoMessage() {}

func (x *MarkCollectionCollectedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkCollectionCollectedResponse.ProtoReflect.Descriptor instead.
func (*MarkCollectionCollectedResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{20}
}

func (x *MarkCollectionCollectedResponse) GetCollection() *CollectionRecord {
	if x != nil {
		return x.Collection
	}
	return nil
}

type MarkCollectionRetryableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *CollectionKey         `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ExpectedValue *v1.GRT                `protobuf:"bytes,2,opt,name=expected_value,json=expectedValue,proto3" json:"expected_value,omitempty"`
	TxHash        string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	LastError     string                 `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkCollectionRetryableRequest) Reset() {
	*x = MarkCollectionRetryableRequest{}
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkCollectionRetryableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkCollectionRetryableRequest) ProtoMessage() {}

func (x *MarkCollectionRetryableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkCollectionRetryableRequest.ProtoReflect.Descriptor instead.
func (*MarkCollectionRetryableRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{21}
}

func (x *MarkCollectionRetryableRequest) GetKey() *CollectionKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MarkCollectionRetryableRequest) GetExpectedValue() *v1.GRT {
	if x != nil {
		return x.ExpectedValue
	}
	return nil
}

func (x *MarkCollectionRetryableRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *MarkCollectionRetryableRequest) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type MarkCollectionRetryableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    *CollectionRecord      `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkCollectionRetryableResponse) Reset() {
	*x = MarkCollectionRetryableResponse{}
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkCollectionRetryableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkCollectionRetryableResponse) ProtoMessage() {}

func (x *MarkCollectionRetryableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkCollectionRetryableResponse.ProtoReflect.Descriptor instead.
func (*MarkCollectionRetryableResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP(), []int{22}
}

func (x *MarkCollectionRetryableResponse) GetCollection() *CollectionRecord {
	if x != nil {
		return x.Collection
	}
	return nil
}

var File_graph_substreams_data_service_provider_v1_operator_proto protoreflect.FileDescriptor

const file_graph_substreams_data_service_provider_v1_operator_proto_rawDesc = "" +
	"\n" +
	"8graph/substreams/data_service/provider/v1/operator.proto\x12)graph.substreams.data_service.provider.v1\x1a3graph/substreams/data_service/common/v1/types.proto\"\xcd\x02\n" +
	"\rCollectionKey\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\fR\fcollectionId\x12F\n" +
	"\x05payer\x18\x03 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\x05payer\x12[\n" +
	"\x10service_provider\x18\x04 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\x0fserviceProvider\x12S\n" +
	"\fdata_service\x18\x05 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\vdataService\"\xc0\x04\n" +
	"\x14OperatorPaymentState\x12]\n" +
	"\x0epayment_status\x18\x01 \x01(\v26.graph.substreams.data_service.common.v1.PaymentStatusR\rpaymentStatus\x12a\n" +
	"\ffunds_status\x18\x02 \x01(\x0e2>.graph.substreams.data_service.provider.v1.OperatorFundsStatusR\vfundsStatus\x12]\n" +
	"\x13current_outstanding\x18\x03 \x01(\v2,.graph.substreams.data_service.common.v1.GRTR\x12currentOutstanding\x12a\n" +
	"\x15projected_outstanding\x18\x04 \x01(\v2,.graph.substreams.data_service.common.v1.GRTR\x14projectedOutstanding\x12S\n" +
	"\x0eminimum_needed\x18\x05 \x01(\v2,.graph.substreams.data_service.common.v1.GRTR\rminimumNeeded\x12*\n" +
	"\x11funds_check_error\x18\x06 \x01(\tR\x0ffundsCheckError\x12#\n" +
	"\roperator_hint\x18\a \x01(\tR\foperatorHint\"\xdd\a\n" +
	"\x0fOperatorSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12X\n" +
	"\x06status\x18\x02 \x01(\x0e2@.graph.substreams.data_service.provider.v1.OperatorSessionStatusR\x06status\x12F\n" +
	"\x05payer\x18\x03 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\x05payer\x12L\n" +
	"\breceiver\x18\x04 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\breceiver\x12S\n" +
	"\fdata_service\x18\x05 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\vdataService\x12\"\n" +
	"\rcreated_at_ns\x18\x06 \x01(\x04R\vcreatedAtNs\x12\"\n" +
	"\rupdated_at_ns\x18\a \x01(\x04R\vupdatedAtNs\x12\x1e\n" +
	"\vended_at_ns\x18\b \x01(\x04R\tendedAtNs\x12Q\n" +
	"\n" +
	"end_reason\x18\t \x01(\x0e22.graph.substreams.data_service.common.v1.EndReasonR\tendReason\x12[\n" +
	"\x11accumulated_usage\x18\n" +
	" \x01(\v2..graph.substreams.data_service.common.v1.UsageR\x10accumulatedUsage\x12U\n" +
	"\x0ebaseline_usage\x18\v \x01(\v2..graph.substreams.data_service.common.v1.UsageR\rbaselineUsage\x126\n" +
	"\x17payment_control_pending\x18\f \x01(\bR\x15paymentControlPending\x12Y\n" +
	"\faccepted_rav\x18\r \x01(\v26.graph.substreams.data_service.provider.v1.AcceptedRAVR\vacceptedRav\x12d\n" +
	"\rpayment_state\x18\x0e \x01(\v2?.graph.substreams.data_service.provider.v1.OperatorPaymentStateR\fpaymentState\"\xff\x04\n" +
	"\vAcceptedRAV\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\fR\fcollectionId\x12F\n" +
	"\x05payer\x18\x03 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\x05payer\x12[\n" +
	"\x10service_provider\x18\x04 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\x0fserviceProvider\x12S\n" +
	"\fdata_service\x18\x05 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\vdataService\x12!\n" +
	"\ftimestamp_ns\x18\x06 \x01(\x04R\vtimestampNs\x12U\n" +
	"\x0fvalue_aggregate\x18\a \x01(\v2,.graph.substreams.data_service.common.v1.GRTR\x0evalueAggregate\x12Q\n" +
	"\n" +
	"signed_rav\x18\b \x01(\v22.graph.substreams.data_service.common.v1.SignedRAVR\tsignedRav\x12e\n" +
	"\x10collection_state\x18\t \x01(\x0e2:.graph.substreams.data_service.provider.v1.CollectionStateR\x0fcollectionState\"\xe1\x04\n" +
	"\x10CollectionRecord\x12J\n" +
	"\x03key\x18\x01 \x01(\v28.graph.substreams.data_service.provider.v1.CollectionKeyR\x03key\x12P\n" +
	"\x05state\x18\x02 \x01(\x0e2:.graph.substreams.data_service.provider.v1.CollectionStateR\x05state\x12Q\n" +
	"\n" +
	"signed_rav\x18\x03 \x01(\v22.graph.substreams.data_service.common.v1.SignedRAVR\tsignedRav\x12U\n" +
	"\x0fvalue_aggregate\x18\x04 \x01(\v2,.graph.substreams.data_service.common.v1.GRTR\x0evalueAggregate\x12#\n" +
	"\rattempt_count\x18\x05 \x01(\x04R\fattemptCount\x12 \n" +
	"\flast_tx_hash\x18\x06 \x01(\tR\n" +
	"lastTxHash\x12\x1d\n" +
	"\n" +
	"last_error\x18\a \x01(\tR\tlastError\x12W\n" +
	"\x10collected_amount\x18\b \x01(\v2,.graph.substreams.data_service.common.v1.GRTR\x0fcollectedAmount\x12\"\n" +
	"\rcreated_at_ns\x18\t \x01(\x04R\vcreatedAtNs\x12\"\n" +
	"\rupdated_at_ns\x18\n" +
	" \x01(\x04R\vupdatedAtNs\"\xf4\x03\n" +
	"\x13ListSessionsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12X\n" +
	"\x06status\x18\x02 \x01(\x0e2@.graph.substreams.data_service.provider.v1.OperatorSessionStatusR\x06status\x12F\n" +
	"\x05payer\x18\x03 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\x05payer\x12L\n" +
	"\breceiver\x18\x04 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\breceiver\x12S\n" +
	"\fdata_service\x18\x05 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\vdataService\x12\x1f\n" +
	"\vinclude_rav\x18\x06 \x01(\bR\n" +
	"includeRav\x12a\n" +
	"\ffunds_status\x18\a \x01(\x0e2>.graph.substreams.data_service.provider.v1.OperatorFundsStatusR\vfundsStatus\"n\n" +
	"\x14ListSessionsResponse\x12V\n" +
	"\bsessions\x18\x01 \x03(\v2:.graph.substreams.data_service.provider.v1.OperatorSessionR\bsessions\"S\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vinclude_rav\x18\x02 \x01(\bR\n" +
	"includeRav\"j\n" +
	"\x12GetSessionResponse\x12T\n" +
	"\asession\x18\x01 \x01(\v2:.graph.substreams.data_service.provider.v1.OperatorSessionR\asession\"\xed\x02\n" +
	"\x17ListAcceptedRAVsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12#\n" +
	"\rcollection_id\x18\x03 \x01(\fR\fcollectionId\x12F\n" +
	"\x05payer\x18\x04 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\x05payer\x12[\n" +
	"\x10service_provider\x18\x05 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\x0fserviceProvider\x12S\n" +
	"\fdata_service\x18\x06 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\vdataService\"f\n" +
	"\x18ListAcceptedRAVsResponse\x12J\n" +
	"\x04ravs\x18\x01 \x03(\v26.graph.substreams.data_service.provider.v1.AcceptedRAVR\x04ravs\"6\n" +
	"\x15GetAcceptedRAVRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"b\n" +
	"\x16GetAcceptedRAVResponse\x12H\n" +
	"\x03rav\x18\x01 \x01(\v26.graph.substreams.data_service.provider.v1.AcceptedRAVR\x03rav\"\xbe\x03\n" +
	"\x16ListCollectionsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12P\n" +
	"\x05state\x18\x03 \x01(\x0e2:.graph.substreams.data_service.provider.v1.CollectionStateR\x05state\x12F\n" +
	"\x05payer\x18\x04 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\x05payer\x12[\n" +
	"\x10service_provider\x18\x05 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\x0fserviceProvider\x12S\n" +
	"\fdata_service\x18\x06 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\vdataService\x12#\n" +
	"\rcollection_id\x18\a \x01(\fR\fcollectionId\"x\n" +
	"\x17ListCollectionsResponse\x12]\n" +
	"\vcollections\x18\x01 \x03(\v2;.graph.substreams.data_service.provider.v1.CollectionRecordR\vcollections\"b\n" +
	"\x14GetCollectionRequest\x12J\n" +
	"\x03key\x18\x01 \x01(\v28.graph.substreams.data_service.provider.v1.CollectionKeyR\x03key\"t\n" +
	"\x15GetCollectionResponse\x12[\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2;.graph.substreams.data_service.provider.v1.CollectionRecordR\n" +
	"collection\"\xd8\x01\n" +
	"\x1cMarkCollectionPendingRequest\x12J\n" +
	"\x03key\x18\x01 \x01(\v28.graph.substreams.data_service.provider.v1.CollectionKeyR\x03key\x12S\n" +
	"\x0eexpected_value\x18\x02 \x01(\v2,.graph.substreams.data_service.common.v1.GRTR\rexpectedValue\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\"|\n" +
	"\x1dMarkCollectionPendingResponse\x12[\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2;.graph.substreams.data_service.provider.v1.CollectionRecordR\n" +
	"collection\"\xb3\x02\n" +
	"\x1eMarkCollectionCollectedRequest\x12J\n" +
	"\x03key\x18\x01 \x01(\v28.graph.substreams.data_service.provider.v1.CollectionKeyR\x03key\x12S\n" +
	"\x0eexpected_value\x18\x02 \x01(\v2,.graph.substreams.data_service.common.v1.GRTR\rexpectedValue\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12W\n" +
	"\x10collected_amount\x18\x04 \x01(\v2,.graph.substreams.data_service.common.v1.GRTR\x0fcollectedAmount\"~\n" +
	"\x1fMarkCollectionCollectedResponse\x12[\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2;.graph.substreams.data_service.provider.v1.CollectionRecordR\n" +
	"collection\"\xf9\x01\n" +
	"\x1eMarkCollectionRetryableRequest\x12J\n" +
	"\x03key\x18\x01 \x01(\v28.graph.substreams.data_service.provider.v1.CollectionKeyR\x03key\x12S\n" +
	"\x0eexpected_value\x18\x02 \x01(\v2,.graph.substreams.data_service.common.v1.GRTR\rexpectedValue\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12\x1d\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tR\tlastError\"~\n" +
	"\x1fMarkCollectionRetryableResponse\x12[\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2;.graph.substreams.data_service.provider.v1.CollectionRecordR\n" +
	"collection*\xb0\x01\n" +
	"\x15OperatorSessionStatus\x12'\n" +
	"#OPERATOR_SESSION_STATUS_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eOPERATOR_SESSION_STATUS_ACTIVE\x10\x01\x12\"\n" +
	"\x1eOPERATOR_SESSION_STATUS_PAUSED\x10\x02\x12&\n" +
	"\"OPERATOR_SESSION_STATUS_TERMINATED\x10\x03*\xca\x01\n" +
	"\x0fCollectionState\x12 \n" +
	"\x1cCOLLECTION_STATE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCOLLECTION_STATE_COLLECTIBLE\x10\x01\x12$\n" +
	" COLLECTION_STATE_COLLECT_PENDING\x10\x02\x12\x1e\n" +
	"\x1aCOLLECTION_STATE_COLLECTED\x10\x03\x12-\n" +
	")COLLECTION_STATE_COLLECT_FAILED_RETRYABLE\x10\x04*\xa5\x01\n" +
	"\x13OperatorFundsStatus\x12%\n" +
	"!OPERATOR_FUNDS_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18OPERATOR_FUNDS_STATUS_OK\x10\x01\x12&\n" +
	"\"OPERATOR_FUNDS_STATUS_INSUFFICIENT\x10\x02\x12!\n" +
	"\x1dOPERATOR_FUNDS_STATUS_UNKNOWN\x10\x032\xb0\v\n" +
	"\x17ProviderOperatorService\x12\x8f\x01\n" +
	"\fListSessions\x12>.graph.substreams.data_service.provider.v1.ListSessionsRequest\x1a?.graph.substreams.data_service.provider.v1.ListSessionsResponse\x12\x89\x01\n" +
	"\n" +
	"GetSession\x12<.graph.substreams.data_service.provider.v1.GetSessionRequest\x1a=.graph.substreams.data_service.provider.v1.GetSessionResponse\x12\x9b\x01\n" +
	"\x10ListAcceptedRAVs\x12B.graph.substreams.data_service.provider.v1.ListAcceptedRAVsRequest\x1aC.graph.substreams.data_service.provider.v1.ListAcceptedRAVsResponse\x12\x95\x01\n" +
	"\x0eGetAcceptedRAV\x12@.graph.substreams.data_service.provider.v1.GetAcceptedRAVRequest\x1aA.graph.substreams.data_service.provider.v1.GetAcceptedRAVResponse\x12\x98\x01\n" +
	"\x0fListCollections\x12A.graph.substreams.data_service.provider.v1.ListCollectionsRequest\x1aB.graph.substreams.data_service.provider.v1.ListCollectionsResponse\x12\x92\x01\n" +
	"\rGetCollection\x12?.graph.substreams.data_service.provider.v1.GetCollectionRequest\x1a@.graph.substreams.data_service.provider.v1.GetCollectionResponse\x12\xaa\x01\n" +
	"\x15MarkCollectionPending\x12G.graph.substreams.data_service.provider.v1.MarkCollectionPendingRequest\x1aH.graph.substreams.data_service.provider.v1.MarkCollectionPendingResponse\x12\xb0\x01\n" +
	"\x17MarkCollectionCollected\x12I.graph.substreams.data_service.provider.v1.MarkCollectionCollectedRequest\x1aJ.graph.substreams.data_service.provider.v1.MarkCollectionCollectedResponse\x12\xb0\x01\n" +
	"\x17MarkCollectionRetryable\x12I.graph.substreams.data_service.provider.v1.MarkCollectionRetryableRequest\x1aJ.graph.substreams.data_service.provider.v1.MarkCollectionRetryableResponseB\xed\x02\n" +
	"-com.graph.substreams.data_service.provider.v1B\rOperatorProtoP\x01Zhgithub.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/provider/v1;providerv1\xa2\x02\x04GSDP\xaa\x02(Graph.Substreams.DataService.Provider.V1\xca\x02(Graph\\Substreams\\DataService\\Provider\\V1\xe2\x024Graph\\Substreams\\DataService\\Provider\\V1\\GPBMetadata\xea\x02,Graph::Substreams::DataService::Provider::V1b\x06proto3"

var (
	file_graph_substreams_data_service_provider_v1_operator_proto_rawDescOnce sync.Once
	file_graph_substreams_data_service_provider_v1_operator_proto_rawDescData []byte
)

func file_graph_substreams_data_service_provider_v1_operator_proto_rawDescGZIP() []byte {
	file_graph_substreams_data_service_provider_v1_operator_proto_rawDescOnce.Do(func() {
		file_graph_substreams_data_service_provider_v1_operator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_substreams_data_service_provider_v1_operator_proto_rawDesc), len(file_graph_substreams_data_service_provider_v1_operator_proto_rawDesc)))
	})
	return file_graph_substreams_data_service_provider_v1_operator_proto_rawDescData
}

var file_graph_substreams_data_service_provider_v1_operator_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_graph_substreams_data_service_provider_v1_operator_proto_goTypes = []any{
	(OperatorSessionStatus)(0),              // 0: graph.substreams.data_service.provider.v1.OperatorSessionStatus
	(CollectionState)(0),                    // 1: graph.substreams.data_service.provider.v1.CollectionState
	(OperatorFundsStatus)(0),                // 2: graph.substreams.data_service.provider.v1.OperatorFundsStatus
	(*CollectionKey)(nil),                   // 3: graph.substreams.data_service.provider.v1.CollectionKey
	(*OperatorPaymentState)(nil),            // 4: graph.substreams.data_service.provider.v1.OperatorPaymentState
	(*OperatorSession)(nil),                 // 5: graph.substreams.data_service.provider.v1.OperatorSession
	(*AcceptedRAV)(nil),                     // 6: graph.substreams.data_service.provider.v1.AcceptedRAV
	(*CollectionRecord)(nil),                // 7: graph.substreams.data_service.provider.v1.CollectionRecord
	(*ListSessionsRequest)(nil),             // 8: graph.substreams.data_service.provider.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),            // 9: graph.substreams.data_service.provider.v1.ListSessionsResponse
	(*GetSessionRequest)(nil),               // 10: graph.substreams.data_service.provider.v1.GetSessionRequest
	(*GetSessionResponse)(nil),              // 11: graph.substreams.data_service.provider.v1.GetSessionResponse
	(*ListAcceptedRAVsRequest)(nil),         // 12: graph.substreams.data_service.provider.v1.ListAcceptedRAVsRequest
	(*ListAcceptedRAVsResponse)(nil),        // 13: graph.substreams.data_service.provider.v1.ListAcceptedRAVsResponse
	(*GetAcceptedRAVRequest)(nil),           // 14: graph.substreams.data_service.provider.v1.GetAcceptedRAVRequest
	(*GetAcceptedRAVResponse)(nil),          // 15: graph.substreams.data_service.provider.v1.GetAcceptedRAVResponse
	(*ListCollectionsRequest)(nil),          // 16: graph.substreams.data_service.provider.v1.ListCollectionsRequest
	(*ListCollectionsResponse)(nil),         // 17: graph.substreams.data_service.provider.v1.ListCollectionsResponse
	(*GetCollectionRequest)(nil),            // 18: graph.substreams.data_service.provider.v1.GetCollectionRequest
	(*GetCollectionResponse)(nil),           // 19: graph.substreams.data_service.provider.v1.GetCollectionResponse
	(*MarkCollectionPendingRequest)(nil),    // 20: graph.substreams.data_service.provider.v1.MarkCollectionPendingRequest
	(*MarkCollectionPendingResponse)(nil),   // 21: graph.substreams.data_service.provider.v1.MarkCollectionPendingResponse
	(*MarkCollectionCollectedRequest)(nil),  // 22: graph.substreams.data_service.provider.v1.MarkCollectionCollectedRequest
	(*MarkCollectionCollectedResponse)(nil), // 23: graph.substreams.data_service.provider.v1.MarkCollectionCollectedResponse
	(*MarkCollectionRetryableRequest)(nil),  // 24: graph.substreams.data_service.provider.v1.MarkCollectionRetryableRequest
	(*MarkCollectionRetryableResponse)(nil), // 25: graph.substreams.data_service.provider.v1.MarkCollectionRetryableResponse
	(*v1.Address)(nil),                      // 26: graph.substreams.data_service.common.v1.Address
	(*v1.PaymentStatus)(nil),                // 27: graph.substreams.data_service.common.v1.PaymentStatus
	(*v1.GRT)(nil),                          // 28: graph.substreams.data_service.common.v1.GRT
	(v1.EndReason)(0),                       // 29: graph.substreams.data_service.common.v1.EndReason
	(*v1.Usage)(nil),                        // 30: graph.substreams.data_service.common.v1.Usage
	(*v1.SignedRAV)(nil),                    // 31: graph.substreams.data_service.common.v1.SignedRAV
}
var file_graph_substreams_data_service_provider_v1_operator_proto_depIdxs = []int32{
	26, // 0: graph.substreams.data_service.provider.v1.CollectionKey.payer:type_name -> graph.substreams.data_service.common.v1.Address
	26, // 1: graph.substreams.data_service.provider.v1.CollectionKey.service_provider:type_name -> graph.substreams.data_service.common.v1.Address
	26, // 2: graph.substreams.data_service.provider.v1.CollectionKey.data_service:type_name -> graph.substreams.data_service.common.v1.Address
	27, // 3: graph.substreams.data_service.provider.v1.OperatorPaymentState.payment_status:type_name -> graph.substreams.data_service.common.v1.PaymentStatus
	2,  // 4: graph.substreams.data_service.provider.v1.OperatorPaymentState.funds_status:type_name -> graph.substreams.data_service.provider.v1.OperatorFundsStatus
	28, // 5: graph.substreams.data_service.provider.v1.OperatorPaymentState.current_outstanding:type_name -> graph.substreams.data_service.common.v1.GRT
	28, // 6: graph.substreams.data_service.provider.v1.OperatorPaymentState.projected_outstanding:type_name -> graph.substreams.data_service.common.v1.GRT
	28, // 7: graph.substreams.data_service.provider.v1.OperatorPaymentState.minimum_needed:type_name -> graph.substreams.data_service.common.v1.GRT
	0,  // 8: graph.substreams.data_service.provider.v1.OperatorSession.status:type_name -> graph.substreams.data_service.provider.v1.OperatorSessionStatus
	26, // 9: graph.substreams.data_service.provider.v1.OperatorSession.payer:type_name -> graph.substreams.data_service.common.v1.Address
	26, // 10: graph.substreams.data_service.provider.v1.OperatorSession.receiver:type_name -> graph.substreams.data_service.common.v1.Address
	26, // 11: graph.substreams.data_service.provider.v1.OperatorSession.data_service:type_name -> graph.substreams.data_service.common.v1.Address
	29, // 12: graph.substreams.data_service.provider.v1.OperatorSession.end_reason:type_name -> graph.substreams.data_service.common.v1.EndReason
	30, // 13: graph.substreams.data_service.provider.v1.OperatorSession.accumulated_usage:type_name -> graph.substreams.data_service.common.v1.Usage
	30, // 14: graph.substreams.data_service.provider.v1.OperatorSession.baseline_usage:type_name -> graph.substreams.data_service.common.v1.Usage
	6,  // 15: graph.substreams.data_service.provider.v1.OperatorSession.accepted_rav:type_name -> graph.substreams.data_service.provider.v1.AcceptedRAV
	4,  // 16: graph.substreams.data_service.provider.v1.OperatorSession.payment_state:type_name -> graph.substreams.data_service.provider.v1.OperatorPaymentState
	26, // 17: graph.substreams.data_service.provider.v1.AcceptedRAV.payer:type_name -> graph.substreams.data_service.common.v1.Address
	26, // 18: graph.substreams.data_service.provider.v1.AcceptedRAV.service_provider:type_name -> graph.substreams.data_service.common.v1.Address
	26, // 19: graph.substreams.data_service.provider.v1.AcceptedRAV.data_service:type_name -> graph.substreams.data_service.common.v1.Address
	28, // 20: graph.substreams.data_service.provider.v1.AcceptedRAV.value_aggregate:type_name -> graph.substreams.data_service.common.v1.GRT
	31, // 21: graph.substreams.data_service.provider.v1.AcceptedRAV.signed_rav:type_name -> graph.substreams.data_service.common.v1.SignedRAV
	1,  // 22: graph.substreams.data_service.provider.v1.AcceptedRAV.collection_state:type_name -> graph.substreams.data_service.provider.v1.CollectionState
	3,  // 23: graph.substreams.data_service.provider.v1.CollectionRecord.key:type_name -> graph.substreams.data_service.provider.v1.CollectionKey
	1,  // 24: graph.substreams.data_service.provider.v1.CollectionRecord.state:type_name -> graph.substreams.data_service.provider.v1.CollectionState
	31, // 25: graph.substreams.data_service.provider.v1.CollectionRecord.signed_rav:type_name -> graph.substreams.data_service.common.v1.SignedRAV
	28, // 26: graph.substreams.data_service.provider.v1.CollectionRecord.value_aggregate:type_name -> graph.substreams.data_service.common.v1.GRT
	28, // 27: graph.substreams.data_service.provider.v1.CollectionRecord.collected_amount:type_name -> graph.substreams.data_service.common.v1.GRT
	0,  // 28: graph.substreams.data_service.provider.v1.ListSessionsRequest.status:type_name -> graph.substreams.data_service.provider.v1.OperatorSessionStatus
	26, // 29: graph.substreams.data_service.provider.v1.ListSessionsRequest.payer:type_name -> graph.substreams.data_service.common.v1.Address
	26, // 30: graph.substreams.data_service.provider.v1.ListSessionsRequest.receiver:type_name -> graph.substreams.data_service.common.v1.Address
	26, // 31: graph.substreams.data_service.provider.v1.ListSessionsRequest.data_service:type_name -> graph.substreams.data_service.common.v1.Address
	2,  // 32: graph.substreams.data_service.provider.v1.ListSessionsRequest.funds_status:type_name -> graph.substreams.data_service.provider.v1.OperatorFundsStatus
	5,  // 33: graph.substreams.data_service.provider.v1.ListSessionsResponse.sessions:type_name -> graph.substreams.data_service.provider.v1.OperatorSession
	5,  // 34: graph.substreams.data_service.provider.v1.GetSessionResponse.session:type_name -> graph.substreams.data_service.provider.v1.OperatorSession
	26, // 35: graph.substreams.data_service.provider.v1.ListAcceptedRAVsRequest.payer:type_name -> graph.substreams.data_service.common.v1.Address
	26, // 36: graph.substreams.data_service.provider.v1.ListAcceptedRAVsRequest.service_provider:type_name -> graph.substreams.data_service.common.v1.Address
	26, // 37: graph.substreams.data_service.provider.v1.ListAcceptedRAVsRequest.data_service:type_name -> graph.substreams.data_service.common.v1.Address
	6,  // 38: graph.substreams.data_service.provider.v1.ListAcceptedRAVsResponse.ravs:type_name -> graph.substreams.data_service.provider.v1.AcceptedRAV
	6,  // 39: graph.substreams.data_service.provider.v1.GetAcceptedRAVResponse.rav:type_name -> graph.substreams.data_service.provider.v1.AcceptedRAV
	1,  // 40: graph.substreams.data_service.provider.v1.ListCollectionsRequest.state:type_name -> graph.substreams.data_service.provider.v1.CollectionState
	26, // 41: graph.substreams.data_service.provider.v1.ListCollectionsRequest.payer:type_name -> graph.substreams.data_service.common.v1.Address
	26, // 42: graph.substreams.data_service.provider.v1.ListCollectionsRequest.service_provider:type_name -> graph.substreams.data_service.common.v1.Address
	26, // 43: graph.substreams.data_service.provider.v1.ListCollectionsRequest.data_service:type_name -> graph.substreams.data_service.common.v1.Address
	7,  // 44: graph.substreams.data_service.provider.v1.ListCollectionsResponse.collections:type_name -> graph.substreams.data_service.provider.v1.CollectionRecord
	3,  // 45: graph.substreams.data_service.provider.v1.GetCollectionRequest.key:type_name -> graph.substreams.data_service.provider.v1.CollectionKey
	7,  // 46: graph.substreams.data_service.provider.v1.GetCollectionResponse.collection:type_name -> graph.substreams.data_service.provider.v1.CollectionRecord
	3,  // 47: graph.substreams.data_service.provider.v1.MarkCollectionPendingRequest.key:type_name -> graph.substreams.data_service.provider.v1.CollectionKey
	28, // 48: graph.substreams.data_service.provider.v1.MarkCollectionPendingRequest.expected_value:type_name -> graph.substreams.data_service.common.v1.GRT
	7,  // 49: graph.substreams.data_service.provider.v1.MarkCollectionPendingResponse.collection:type_name -> graph.substreams.data_service.provider.v1.CollectionRecord
	3,  // 50: graph.substreams.data_service.provider.v1.MarkCollectionCollectedRequest.key:type_name -> graph.substreams.data_service.provider.v1.CollectionKey
	28, // 51: graph.substreams.data_service.provider.v1.MarkCollectionCollectedRequest.expected_value:type_name -> graph.substreams.data_service.common.v1.GRT
	28, // 52: graph.substreams.data_service.provider.v1.MarkCollectionCollectedRequest.collected_amount:type_name -> graph.substreams.data_service.common.v1.GRT
	7,  // 53: graph.substreams.data_service.provider.v1.MarkCollectionCollectedResponse.collection:type_name -> graph.substreams.data_service.provider.v1.CollectionRecord
	3,  // 54: graph.substreams.data_service.provider.v1.MarkCollectionRetryableRequest.key:type_name -> graph.substreams.data_service.provider.v1.CollectionKey
	28, // 55: graph.substreams.data_service.provider.v1.MarkCollectionRetryableRequest.expected_value:type_name -> graph.substreams.data_service.common.v1.GRT
	7,  // 56: graph.substreams.data_service.provider.v1.MarkCollectionRetryableResponse.collection:type_name -> graph.substreams.data_service.provider.v1.CollectionRecord
	8,  // 57: graph.substreams.data_service.provider.v1.ProviderOperatorService.ListSessions:input_type -> graph.substreams.data_service.provider.v1.ListSessionsRequest
	10, // 58: graph.substreams.data_service.provider.v1.ProviderOperatorService.GetSession:input_type -> graph.substreams.data_service.provider.v1.GetSessionRequest
	12, // 59: graph.substreams.data_service.provider.v1.ProviderOperatorService.ListAcceptedRAVs:input_type -> graph.substreams.data_service.provider.v1.ListAcceptedRAVsRequest
	14, // 60: graph.substreams.data_service.provider.v1.ProviderOperatorService.GetAcceptedRAV:input_type -> graph.substreams.data_service.provider.v1.GetAcceptedRAVRequest
	16, // 61: graph.substreams.data_service.provider.v1.ProviderOperatorService.ListCollections:input_type -> graph.substreams.data_service.provider.v1.ListCollectionsRequest
	18, // 62: graph.substreams.data_service.provider.v1.ProviderOperatorService.GetCollection:input_type -> graph.substreams.data_service.provider.v1.GetCollectionRequest
	20, // 63: graph.substreams.data_service.provider.v1.ProviderOperatorService.MarkCollectionPending:input_type -> graph.substreams.data_service.provider.v1.MarkCollectionPendingRequest
	22, // 64: graph.substreams.data_service.provider.v1.ProviderOperatorService.MarkCollectionCollected:input_type -> graph.substreams.data_service.provider.v1.MarkCollectionCollectedRequest
	24, // 65: graph.substreams.data_service.provider.v1.ProviderOperatorService.MarkCollectionRetryable:input_type -> graph.substreams.data_service.provider.v1.MarkCollectionRetryableRequest
	9,  // 66: graph.substreams.data_service.provider.v1.ProviderOperatorService.ListSessions:output_type -> graph.substreams.data_service.provider.v1.ListSessionsResponse
	11, // 67: graph.substreams.data_service.provider.v1.ProviderOperatorService.GetSession:output_type -> graph.substreams.data_service.provider.v1.GetSessionResponse
	13, // 68: graph.substreams.data_service.provider.v1.ProviderOperatorService.ListAcceptedRAVs:output_type -> graph.substreams.data_service.provider.v1.ListAcceptedRAVsResponse
	15, // 69: graph.substreams.data_service.provider.v1.ProviderOperatorService.GetAcceptedRAV:output_type -> graph.substreams.data_service.provider.v1.GetAcceptedRAVResponse
	17, // 70: graph.substreams.data_service.provider.v1.ProviderOperatorService.ListCollections:output_type -> graph.substreams.data_service.provider.v1.ListCollectionsResponse
	19, // 71: graph.substreams.data_service.provider.v1.ProviderOperatorService.GetCollection:output_type -> graph.substreams.data_service.provider.v1.GetCollectionResponse
	21, // 72: graph.substreams.data_service.provider.v1.ProviderOperatorService.MarkCollectionPending:output_type -> graph.substreams.data_service.provider.v1.MarkCollectionPendingResponse
	23, // 73: graph.substreams.data_service.provider.v1.ProviderOperatorService.MarkCollectionCollected:output_type -> graph.substreams.data_service.provider.v1.MarkCollectionCollectedResponse
	25, // 74: graph.substreams.data_service.provider.v1.ProviderOperatorService.MarkCollectionRetryable:output_type -> graph.substreams.data_service.provider.v1.MarkCollectionRetryableResponse
	66, // [66:75] is the sub-list for method output_type
	57, // [57:66] is the sub-list for method input_type
	57, // [57:57] is the sub-list for extension type_name
	57, // [57:57] is the sub-list for extension extendee
	0,  // [0:57] is the sub-list for field type_name
}

func init() { file_graph_substreams_data_service_provider_v1_operator_proto_init() }
func file_graph_substreams_data_service_provider_v1_operator_proto_init() {
	if File_graph_substreams_data_service_provider_v1_operator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_substreams_data_service_provider_v1_operator_proto_rawDesc), len(file_graph_substreams_data_service_provider_v1_operator_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graph_substreams_data_service_provider_v1_operator_proto_goTypes,
		DependencyIndexes: file_graph_substreams_data_service_provider_v1_operator_proto_depIdxs,
		EnumInfos:         file_graph_substreams_data_service_provider_v1_operator_proto_enumTypes,
		MessageInfos:      file_graph_substreams_data_service_provider_v1_operator_proto_msgTypes,
	}.Build()
	File_graph_substreams_data_service_provider_v1_operator_proto = out.File
	file_graph_substreams_data_service_provider_v1_operator_proto_goTypes = nil
	file_graph_substreams_data_service_provider_v1_operator_proto_depIdxs = nil
}
