package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/graphprotocol/substreams-data-service/horizon/devenv"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
	"github.com/streamingfast/cli"
	. "github.com/streamingfast/cli"
	"github.com/streamingfast/cli/sflags"
)

var demoSetupCmd = Command(
	runDemoSetup,
	"setup",
	"Verify demo-ready devenv state and write demo env vars",
	Description(`
		Connects to an already-running local devenv chain, verifies that the default
		demo-ready on-chain state is present, and writes the environment variables
		required by the local demo stack.

		This command does not mutate chain state.
	`),
	Flags(func(flags *pflag.FlagSet) {
		flags.String("rpc-endpoint", "http://localhost:58545", "Ethereum RPC endpoint (from `sds devenv` output)")
		flags.Uint64("chain-id", 1337, "Chain ID for the local devenv chain")
		flags.String("env-file", "devel/.demo.env", "Write an env file for `.reflex.stack` (set to empty to disable)")
	}),
)

func runDemoSetup(cmd *cobra.Command, args []string) error {
	ctx := cmd.Context()

	rpcEndpoint := strings.TrimSpace(sflags.MustGetString(cmd, "rpc-endpoint"))
	chainID := sflags.MustGetUint64(cmd, "chain-id")
	envFilePath := strings.TrimSpace(sflags.MustGetString(cmd, "env-file"))

	cli.Ensure(rpcEndpoint != "", "<rpc-endpoint> is required")

	env := devenv.Connect(ctx, rpcEndpoint, chainID)

	if err := env.VerifyDefaultDemoState(devenv.DefaultTestSetupConfig()); err != nil {
		return fmt.Errorf("demo-ready devenv state is not available at %s: %w\nrun `sds devenv` and wait for it to finish bootstrapping before re-running `sds demo setup`", rpcEndpoint, err)
	}

	if envFilePath != "" {
		if err := writeDemoEnvFile(envFilePath, map[string]string{
			"SDS_DEMO_CHAIN_ID":                 fmt.Sprintf("%d", chainID),
			"SDS_DEMO_RPC_ENDPOINT":             rpcEndpoint,
			"SDS_DEMO_COLLECTOR_ADDRESS":        env.Collector.Address.Pretty(),
			"SDS_DEMO_ESCROW_ADDRESS":           env.Escrow.Address.Pretty(),
			"SDS_DEMO_DATA_SERVICE_ADDRESS":     env.DataService.Address.Pretty(),
			"SDS_DEMO_SERVICE_PROVIDER_ADDRESS": env.ServiceProvider.Address.Pretty(),
			"SDS_DEMO_PAYER_ADDRESS":            env.Payer.Address.Pretty(),
			"SDS_DEMO_SIGNER_PRIVATE_KEY":       "0x" + env.DemoSigner.PrivateKey.String(),
			"SDS_DEMO_SIGNER_ADDRESS":           env.DemoSigner.Address.Pretty(),
		}); err != nil {
			return err
		}
		fmt.Printf("Verified demo-ready chain state and wrote demo env file: %s\n\n", envFilePath)
	}

	fmt.Printf("\nDemo-ready state verified successfully.\n\n")
	fmt.Printf("AUTHORIZED DEMO SIGNER:\n")
	fmt.Printf("  Signer address:      %s\n", env.DemoSigner.Address.Pretty())
	fmt.Printf("  Signer private key:  0x%s\n", env.DemoSigner.PrivateKey.String())
	fmt.Printf("\n")

	fmt.Printf("START COMMANDS:\n")
	fmt.Printf("  Provider gateway:\n")
	fmt.Printf("    sds provider gateway --service-provider %s --collector-address %s --escrow-address %s --rpc-endpoint %s --data-plane-endpoint localhost:10016 --plaintext --plugin-plaintext\n",
		env.ServiceProvider.Address.Pretty(),
		env.Collector.Address.Pretty(),
		env.Escrow.Address.Pretty(),
		rpcEndpoint,
	)
	fmt.Printf("\n")
	fmt.Printf("  Consumer sidecar:\n")
	fmt.Printf("    sds consumer sidecar --signer-private-key 0x%s --collector-address %s\n",
		env.DemoSigner.PrivateKey.String(),
		env.Collector.Address.Pretty(),
	)
	fmt.Printf("\n")
	fmt.Printf("  Substreams ingress example:\n")
	fmt.Printf("    substreams gui common@v0.1.0 map_clocks -e localhost:9002 --plaintext --network mainnet -s 0 -t +20\n")

	return nil
}

func writeDemoEnvFile(path string, exports map[string]string) error {
	var b strings.Builder
	b.WriteString("# Generated by `sds demo setup`\n")
	b.WriteString("# Source this file to align `.reflex.stack` with the deterministic demo signer.\n")

	keys := make([]string, 0, len(exports))
	for k := range exports {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		v := exports[k]
		if strings.TrimSpace(k) == "" {
			continue
		}
		v = strings.TrimSpace(v)
		v = strings.ReplaceAll(v, "'", "'\\''")
		fmt.Fprintf(&b, "export %s='%s'\n", k, v)
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("creating env file directory for %q: %w", path, err)
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o600); err != nil {
		return fmt.Errorf("writing env file %q: %w", path, err)
	}
	return nil
}
