// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: graph/substreams/data_service/consumer/v1/consumer.proto

package consumerv1

import (
	v1 "github.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The escrow account to use for funding this session
	EscrowAccount *v1.EscrowAccount `protobuf:"bytes,1,opt,name=escrow_account,json=escrowAccount,proto3" json:"escrow_account,omitempty"`
	// Direct provider override used before oracle discovery is implemented.
	// This is the provider control-plane endpoint used for session/payment management.
	// Supports ?insecure=true query parameter for self-signed certificates.
	ProviderControlPlaneEndpoint string `protobuf:"bytes,2,opt,name=provider_control_plane_endpoint,json=providerControlPlaneEndpoint,proto3" json:"provider_control_plane_endpoint,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_graph_substreams_data_service_consumer_v1_consumer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_consumer_v1_consumer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetEscrowAccount() *v1.EscrowAccount {
	if x != nil {
		return x.EscrowAccount
	}
	return nil
}

func (x *InitRequest) GetProviderControlPlaneEndpoint() string {
	if x != nil {
		return x.ProviderControlPlaneEndpoint
	}
	return ""
}

type InitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session information including the RAV to use
	Session *v1.SessionInfo `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	// The RAV to include in the payment header when connecting to provider
	PaymentRav *v1.SignedRAV `protobuf:"bytes,2,opt,name=payment_rav,json=paymentRav,proto3" json:"payment_rav,omitempty"`
	// The session-specific data-plane endpoint returned by the provider handshake.
	DataPlaneEndpoint string `protobuf:"bytes,3,opt,name=data_plane_endpoint,json=dataPlaneEndpoint,proto3" json:"data_plane_endpoint,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_graph_substreams_data_service_consumer_v1_consumer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_consumer_v1_consumer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDescGZIP(), []int{1}
}

func (x *InitResponse) GetSession() *v1.SessionInfo {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *InitResponse) GetPaymentRav() *v1.SignedRAV {
	if x != nil {
		return x.PaymentRav
	}
	return nil
}

func (x *InitResponse) GetDataPlaneEndpoint() string {
	if x != nil {
		return x.DataPlaneEndpoint
	}
	return ""
}

type ReportUsageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session ID
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// The usage to report
	Usage         *v1.Usage `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportUsageRequest) Reset() {
	*x = ReportUsageRequest{}
	mi := &file_graph_substreams_data_service_consumer_v1_consumer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUsageRequest) ProtoMessage() {}

func (x *ReportUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_consumer_v1_consumer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUsageRequest.ProtoReflect.Descriptor instead.
func (*ReportUsageRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDescGZIP(), []int{2}
}

func (x *ReportUsageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReportUsageRequest) GetUsage() *v1.Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type ReportUsageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated RAV if a new one was negotiated
	UpdatedRav *v1.SignedRAV `protobuf:"bytes,1,opt,name=updated_rav,json=updatedRav,proto3" json:"updated_rav,omitempty"`
	// Whether the session should continue
	ShouldContinue bool `protobuf:"varint,2,opt,name=should_continue,json=shouldContinue,proto3" json:"should_continue,omitempty"`
	// If should_continue is false, the reason for stopping
	StopReason    string `protobuf:"bytes,3,opt,name=stop_reason,json=stopReason,proto3" json:"stop_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportUsageResponse) Reset() {
	*x = ReportUsageResponse{}
	mi := &file_graph_substreams_data_service_consumer_v1_consumer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUsageResponse) ProtoMessage() {}

func (x *ReportUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_consumer_v1_consumer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUsageResponse.ProtoReflect.Descriptor instead.
func (*ReportUsageResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDescGZIP(), []int{3}
}

func (x *ReportUsageResponse) GetUpdatedRav() *v1.SignedRAV {
	if x != nil {
		return x.UpdatedRav
	}
	return nil
}

func (x *ReportUsageResponse) GetShouldContinue() bool {
	if x != nil {
		return x.ShouldContinue
	}
	return false
}

func (x *ReportUsageResponse) GetStopReason() string {
	if x != nil {
		return x.StopReason
	}
	return ""
}

type EndSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session ID
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Final usage to report
	FinalUsage    *v1.Usage `protobuf:"bytes,2,opt,name=final_usage,json=finalUsage,proto3" json:"final_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionRequest) Reset() {
	*x = EndSessionRequest{}
	mi := &file_graph_substreams_data_service_consumer_v1_consumer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionRequest) ProtoMessage() {}

func (x *EndSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_consumer_v1_consumer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionRequest.ProtoReflect.Descriptor instead.
func (*EndSessionRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDescGZIP(), []int{4}
}

func (x *EndSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EndSessionRequest) GetFinalUsage() *v1.Usage {
	if x != nil {
		return x.FinalUsage
	}
	return nil
}

type EndSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The final signed RAV for this session
	FinalRav *v1.SignedRAV `protobuf:"bytes,1,opt,name=final_rav,json=finalRav,proto3" json:"final_rav,omitempty"`
	// Total usage for the session
	TotalUsage    *v1.Usage `protobuf:"bytes,2,opt,name=total_usage,json=totalUsage,proto3" json:"total_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionResponse) Reset() {
	*x = EndSessionResponse{}
	mi := &file_graph_substreams_data_service_consumer_v1_consumer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionResponse) ProtoMessage() {}

func (x *EndSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_consumer_v1_consumer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionResponse.ProtoReflect.Descriptor instead.
func (*EndSessionResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDescGZIP(), []int{5}
}

func (x *EndSessionResponse) GetFinalRav() *v1.SignedRAV {
	if x != nil {
		return x.FinalRav
	}
	return nil
}

func (x *EndSessionResponse) GetTotalUsage() *v1.Usage {
	if x != nil {
		return x.TotalUsage
	}
	return nil
}

var File_graph_substreams_data_service_consumer_v1_consumer_proto protoreflect.FileDescriptor

const file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDesc = "" +
	"\n" +
	"8graph/substreams/data_service/consumer/v1/consumer.proto\x12)graph.substreams.data_service.consumer.v1\x1a3graph/substreams/data_service/common/v1/types.proto\"\xbf\x01\n" +
	"\vInitRequest\x12]\n" +
	"\x0eescrow_account\x18\x01 \x01(\v26.graph.substreams.data_service.common.v1.EscrowAccountR\rescrowAccount\x12E\n" +
	"\x1fprovider_control_plane_endpoint\x18\x02 \x01(\tR\x1cproviderControlPlaneEndpointJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05\"\xe3\x01\n" +
	"\fInitResponse\x12N\n" +
	"\asession\x18\x01 \x01(\v24.graph.substreams.data_service.common.v1.SessionInfoR\asession\x12S\n" +
	"\vpayment_rav\x18\x02 \x01(\v22.graph.substreams.data_service.common.v1.SignedRAVR\n" +
	"paymentRav\x12.\n" +
	"\x13data_plane_endpoint\x18\x03 \x01(\tR\x11dataPlaneEndpoint\"y\n" +
	"\x12ReportUsageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12D\n" +
	"\x05usage\x18\x02 \x01(\v2..graph.substreams.data_service.common.v1.UsageR\x05usage\"\xb4\x01\n" +
	"\x13ReportUsageResponse\x12S\n" +
	"\vupdated_rav\x18\x01 \x01(\v22.graph.substreams.data_service.common.v1.SignedRAVR\n" +
	"updatedRav\x12'\n" +
	"\x0fshould_continue\x18\x02 \x01(\bR\x0eshouldContinue\x12\x1f\n" +
	"\vstop_reason\x18\x03 \x01(\tR\n" +
	"stopReason\"\x83\x01\n" +
	"\x11EndSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12O\n" +
	"\vfinal_usage\x18\x02 \x01(\v2..graph.substreams.data_service.common.v1.UsageR\n" +
	"finalUsage\"\xb6\x01\n" +
	"\x12EndSessionResponse\x12O\n" +
	"\tfinal_rav\x18\x01 \x01(\v22.graph.substreams.data_service.common.v1.SignedRAVR\bfinalRav\x12O\n" +
	"\vtotal_usage\x18\x02 \x01(\v2..graph.substreams.data_service.common.v1.UsageR\n" +
	"totalUsage2\xac\x03\n" +
	"\x16ConsumerSidecarService\x12w\n" +
	"\x04Init\x126.graph.substreams.data_service.consumer.v1.InitRequest\x1a7.graph.substreams.data_service.consumer.v1.InitResponse\x12\x8c\x01\n" +
	"\vReportUsage\x12=.graph.substreams.data_service.consumer.v1.ReportUsageRequest\x1a>.graph.substreams.data_service.consumer.v1.ReportUsageResponse\x12\x89\x01\n" +
	"\n" +
	"EndSession\x12<.graph.substreams.data_service.consumer.v1.EndSessionRequest\x1a=.graph.substreams.data_service.consumer.v1.EndSessionResponseB\xed\x02\n" +
	"-com.graph.substreams.data_service.consumer.v1B\rConsumerProtoP\x01Zhgithub.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/consumer/v1;consumerv1\xa2\x02\x04GSDC\xaa\x02(Graph.Substreams.DataService.Consumer.V1\xca\x02(Graph\\Substreams\\DataService\\Consumer\\V1\xe2\x024Graph\\Substreams\\DataService\\Consumer\\V1\\GPBMetadata\xea\x02,Graph::Substreams::DataService::Consumer::V1b\x06proto3"

var (
	file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDescOnce sync.Once
	file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDescData []byte
)

func file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDescGZIP() []byte {
	file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDescOnce.Do(func() {
		file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDesc), len(file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDesc)))
	})
	return file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDescData
}

var file_graph_substreams_data_service_consumer_v1_consumer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_graph_substreams_data_service_consumer_v1_consumer_proto_goTypes = []any{
	(*InitRequest)(nil),         // 0: graph.substreams.data_service.consumer.v1.InitRequest
	(*InitResponse)(nil),        // 1: graph.substreams.data_service.consumer.v1.InitResponse
	(*ReportUsageRequest)(nil),  // 2: graph.substreams.data_service.consumer.v1.ReportUsageRequest
	(*ReportUsageResponse)(nil), // 3: graph.substreams.data_service.consumer.v1.ReportUsageResponse
	(*EndSessionRequest)(nil),   // 4: graph.substreams.data_service.consumer.v1.EndSessionRequest
	(*EndSessionResponse)(nil),  // 5: graph.substreams.data_service.consumer.v1.EndSessionResponse
	(*v1.EscrowAccount)(nil),    // 6: graph.substreams.data_service.common.v1.EscrowAccount
	(*v1.SessionInfo)(nil),      // 7: graph.substreams.data_service.common.v1.SessionInfo
	(*v1.SignedRAV)(nil),        // 8: graph.substreams.data_service.common.v1.SignedRAV
	(*v1.Usage)(nil),            // 9: graph.substreams.data_service.common.v1.Usage
}
var file_graph_substreams_data_service_consumer_v1_consumer_proto_depIdxs = []int32{
	6,  // 0: graph.substreams.data_service.consumer.v1.InitRequest.escrow_account:type_name -> graph.substreams.data_service.common.v1.EscrowAccount
	7,  // 1: graph.substreams.data_service.consumer.v1.InitResponse.session:type_name -> graph.substreams.data_service.common.v1.SessionInfo
	8,  // 2: graph.substreams.data_service.consumer.v1.InitResponse.payment_rav:type_name -> graph.substreams.data_service.common.v1.SignedRAV
	9,  // 3: graph.substreams.data_service.consumer.v1.ReportUsageRequest.usage:type_name -> graph.substreams.data_service.common.v1.Usage
	8,  // 4: graph.substreams.data_service.consumer.v1.ReportUsageResponse.updated_rav:type_name -> graph.substreams.data_service.common.v1.SignedRAV
	9,  // 5: graph.substreams.data_service.consumer.v1.EndSessionRequest.final_usage:type_name -> graph.substreams.data_service.common.v1.Usage
	8,  // 6: graph.substreams.data_service.consumer.v1.EndSessionResponse.final_rav:type_name -> graph.substreams.data_service.common.v1.SignedRAV
	9,  // 7: graph.substreams.data_service.consumer.v1.EndSessionResponse.total_usage:type_name -> graph.substreams.data_service.common.v1.Usage
	0,  // 8: graph.substreams.data_service.consumer.v1.ConsumerSidecarService.Init:input_type -> graph.substreams.data_service.consumer.v1.InitRequest
	2,  // 9: graph.substreams.data_service.consumer.v1.ConsumerSidecarService.ReportUsage:input_type -> graph.substreams.data_service.consumer.v1.ReportUsageRequest
	4,  // 10: graph.substreams.data_service.consumer.v1.ConsumerSidecarService.EndSession:input_type -> graph.substreams.data_service.consumer.v1.EndSessionRequest
	1,  // 11: graph.substreams.data_service.consumer.v1.ConsumerSidecarService.Init:output_type -> graph.substreams.data_service.consumer.v1.InitResponse
	3,  // 12: graph.substreams.data_service.consumer.v1.ConsumerSidecarService.ReportUsage:output_type -> graph.substreams.data_service.consumer.v1.ReportUsageResponse
	5,  // 13: graph.substreams.data_service.consumer.v1.ConsumerSidecarService.EndSession:output_type -> graph.substreams.data_service.consumer.v1.EndSessionResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_graph_substreams_data_service_consumer_v1_consumer_proto_init() }
func file_graph_substreams_data_service_consumer_v1_consumer_proto_init() {
	if File_graph_substreams_data_service_consumer_v1_consumer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDesc), len(file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graph_substreams_data_service_consumer_v1_consumer_proto_goTypes,
		DependencyIndexes: file_graph_substreams_data_service_consumer_v1_consumer_proto_depIdxs,
		MessageInfos:      file_graph_substreams_data_service_consumer_v1_consumer_proto_msgTypes,
	}.Build()
	File_graph_substreams_data_service_consumer_v1_consumer_proto = out.File
	file_graph_substreams_data_service_consumer_v1_consumer_proto_goTypes = nil
	file_graph_substreams_data_service_consumer_v1_consumer_proto_depIdxs = nil
}
