// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: graph/substreams/data_service/consumer/v1/consumer.proto

package consumerv1

import (
	v1 "github.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/common/v1"
	v11 "github.com/graphprotocol/substreams-data-service/pb/sf/substreams/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The escrow account to use for funding this session
	EscrowAccount *v1.EscrowAccount `protobuf:"bytes,1,opt,name=escrow_account,json=escrowAccount,proto3" json:"escrow_account,omitempty"`
	// Direct provider override. When set, this bypasses oracle discovery.
	// This is the provider control-plane endpoint used for session/payment management.
	// Supports ?insecure=true query parameter for self-signed certificates.
	ProviderControlPlaneEndpoint string `protobuf:"bytes,2,opt,name=provider_control_plane_endpoint,json=providerControlPlaneEndpoint,proto3" json:"provider_control_plane_endpoint,omitempty"`
	// The already-loaded Substreams package used for network derivation.
	SubstreamsPackage *v11.Package `protobuf:"bytes,5,opt,name=substreams_package,json=substreamsPackage,proto3" json:"substreams_package,omitempty"`
	// Optional explicit network fallback when package derivation is unavailable.
	RequestedNetwork string `protobuf:"bytes,6,opt,name=requested_network,json=requestedNetwork,proto3" json:"requested_network,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_graph_substreams_data_service_consumer_v1_consumer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_consumer_v1_consumer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetEscrowAccount() *v1.EscrowAccount {
	if x != nil {
		return x.EscrowAccount
	}
	return nil
}

func (x *InitRequest) GetProviderControlPlaneEndpoint() string {
	if x != nil {
		return x.ProviderControlPlaneEndpoint
	}
	return ""
}

func (x *InitRequest) GetSubstreamsPackage() *v11.Package {
	if x != nil {
		return x.SubstreamsPackage
	}
	return nil
}

func (x *InitRequest) GetRequestedNetwork() string {
	if x != nil {
		return x.RequestedNetwork
	}
	return ""
}

type InitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session information including the RAV to use
	Session *v1.SessionInfo `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	// The RAV to include in the payment header when connecting to provider
	PaymentRav *v1.SignedRAV `protobuf:"bytes,2,opt,name=payment_rav,json=paymentRav,proto3" json:"payment_rav,omitempty"`
	// The session-specific data-plane endpoint returned by the provider handshake.
	DataPlaneEndpoint string `protobuf:"bytes,3,opt,name=data_plane_endpoint,json=dataPlaneEndpoint,proto3" json:"data_plane_endpoint,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_graph_substreams_data_service_consumer_v1_consumer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_consumer_v1_consumer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDescGZIP(), []int{1}
}

func (x *InitResponse) GetSession() *v1.SessionInfo {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *InitResponse) GetPaymentRav() *v1.SignedRAV {
	if x != nil {
		return x.PaymentRav
	}
	return nil
}

func (x *InitResponse) GetDataPlaneEndpoint() string {
	if x != nil {
		return x.DataPlaneEndpoint
	}
	return ""
}

type EndSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session ID
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Final usage to report
	FinalUsage    *v1.Usage `protobuf:"bytes,2,opt,name=final_usage,json=finalUsage,proto3" json:"final_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionRequest) Reset() {
	*x = EndSessionRequest{}
	mi := &file_graph_substreams_data_service_consumer_v1_consumer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionRequest) ProtoMessage() {}

func (x *EndSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_consumer_v1_consumer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionRequest.ProtoReflect.Descriptor instead.
func (*EndSessionRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDescGZIP(), []int{2}
}

func (x *EndSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EndSessionRequest) GetFinalUsage() *v1.Usage {
	if x != nil {
		return x.FinalUsage
	}
	return nil
}

type EndSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The final signed RAV for this session
	FinalRav *v1.SignedRAV `protobuf:"bytes,1,opt,name=final_rav,json=finalRav,proto3" json:"final_rav,omitempty"`
	// Total usage for the session
	TotalUsage    *v1.Usage `protobuf:"bytes,2,opt,name=total_usage,json=totalUsage,proto3" json:"total_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionResponse) Reset() {
	*x = EndSessionResponse{}
	mi := &file_graph_substreams_data_service_consumer_v1_consumer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionResponse) ProtoMessage() {}

func (x *EndSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_consumer_v1_consumer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionResponse.ProtoReflect.Descriptor instead.
func (*EndSessionResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDescGZIP(), []int{3}
}

func (x *EndSessionResponse) GetFinalRav() *v1.SignedRAV {
	if x != nil {
		return x.FinalRav
	}
	return nil
}

func (x *EndSessionResponse) GetTotalUsage() *v1.Usage {
	if x != nil {
		return x.TotalUsage
	}
	return nil
}

var File_graph_substreams_data_service_consumer_v1_consumer_proto protoreflect.FileDescriptor

const file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDesc = "" +
	"\n" +
	"8graph/substreams/data_service/consumer/v1/consumer.proto\x12)graph.substreams.data_service.consumer.v1\x1a3graph/substreams/data_service/common/v1/types.proto\x1a\x1esf/substreams/v1/package.proto\"\xb6\x02\n" +
	"\vInitRequest\x12]\n" +
	"\x0eescrow_account\x18\x01 \x01(\v26.graph.substreams.data_service.common.v1.EscrowAccountR\rescrowAccount\x12E\n" +
	"\x1fprovider_control_plane_endpoint\x18\x02 \x01(\tR\x1cproviderControlPlaneEndpoint\x12H\n" +
	"\x12substreams_package\x18\x05 \x01(\v2\x19.sf.substreams.v1.PackageR\x11substreamsPackage\x12+\n" +
	"\x11requested_network\x18\x06 \x01(\tR\x10requestedNetworkJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05\"\xe3\x01\n" +
	"\fInitResponse\x12N\n" +
	"\asession\x18\x01 \x01(\v24.graph.substreams.data_service.common.v1.SessionInfoR\asession\x12S\n" +
	"\vpayment_rav\x18\x02 \x01(\v22.graph.substreams.data_service.common.v1.SignedRAVR\n" +
	"paymentRav\x12.\n" +
	"\x13data_plane_endpoint\x18\x03 \x01(\tR\x11dataPlaneEndpoint\"\x83\x01\n" +
	"\x11EndSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12O\n" +
	"\vfinal_usage\x18\x02 \x01(\v2..graph.substreams.data_service.common.v1.UsageR\n" +
	"finalUsage\"\xb6\x01\n" +
	"\x12EndSessionResponse\x12O\n" +
	"\tfinal_rav\x18\x01 \x01(\v22.graph.substreams.data_service.common.v1.SignedRAVR\bfinalRav\x12O\n" +
	"\vtotal_usage\x18\x02 \x01(\v2..graph.substreams.data_service.common.v1.UsageR\n" +
	"totalUsage2\x9d\x02\n" +
	"\x16ConsumerSidecarService\x12w\n" +
	"\x04Init\x126.graph.substreams.data_service.consumer.v1.InitRequest\x1a7.graph.substreams.data_service.consumer.v1.InitResponse\x12\x89\x01\n" +
	"\n" +
	"EndSession\x12<.graph.substreams.data_service.consumer.v1.EndSessionRequest\x1a=.graph.substreams.data_service.consumer.v1.EndSessionResponseB\xed\x02\n" +
	"-com.graph.substreams.data_service.consumer.v1B\rConsumerProtoP\x01Zhgithub.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/consumer/v1;consumerv1\xa2\x02\x04GSDC\xaa\x02(Graph.Substreams.DataService.Consumer.V1\xca\x02(Graph\\Substreams\\DataService\\Consumer\\V1\xe2\x024Graph\\Substreams\\DataService\\Consumer\\V1\\GPBMetadata\xea\x02,Graph::Substreams::DataService::Consumer::V1b\x06proto3"

var (
	file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDescOnce sync.Once
	file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDescData []byte
)

func file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDescGZIP() []byte {
	file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDescOnce.Do(func() {
		file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDesc), len(file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDesc)))
	})
	return file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDescData
}

var file_graph_substreams_data_service_consumer_v1_consumer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_graph_substreams_data_service_consumer_v1_consumer_proto_goTypes = []any{
	(*InitRequest)(nil),        // 0: graph.substreams.data_service.consumer.v1.InitRequest
	(*InitResponse)(nil),       // 1: graph.substreams.data_service.consumer.v1.InitResponse
	(*EndSessionRequest)(nil),  // 2: graph.substreams.data_service.consumer.v1.EndSessionRequest
	(*EndSessionResponse)(nil), // 3: graph.substreams.data_service.consumer.v1.EndSessionResponse
	(*v1.EscrowAccount)(nil),   // 4: graph.substreams.data_service.common.v1.EscrowAccount
	(*v11.Package)(nil),        // 5: sf.substreams.v1.Package
	(*v1.SessionInfo)(nil),     // 6: graph.substreams.data_service.common.v1.SessionInfo
	(*v1.SignedRAV)(nil),       // 7: graph.substreams.data_service.common.v1.SignedRAV
	(*v1.Usage)(nil),           // 8: graph.substreams.data_service.common.v1.Usage
}
var file_graph_substreams_data_service_consumer_v1_consumer_proto_depIdxs = []int32{
	4, // 0: graph.substreams.data_service.consumer.v1.InitRequest.escrow_account:type_name -> graph.substreams.data_service.common.v1.EscrowAccount
	5, // 1: graph.substreams.data_service.consumer.v1.InitRequest.substreams_package:type_name -> sf.substreams.v1.Package
	6, // 2: graph.substreams.data_service.consumer.v1.InitResponse.session:type_name -> graph.substreams.data_service.common.v1.SessionInfo
	7, // 3: graph.substreams.data_service.consumer.v1.InitResponse.payment_rav:type_name -> graph.substreams.data_service.common.v1.SignedRAV
	8, // 4: graph.substreams.data_service.consumer.v1.EndSessionRequest.final_usage:type_name -> graph.substreams.data_service.common.v1.Usage
	7, // 5: graph.substreams.data_service.consumer.v1.EndSessionResponse.final_rav:type_name -> graph.substreams.data_service.common.v1.SignedRAV
	8, // 6: graph.substreams.data_service.consumer.v1.EndSessionResponse.total_usage:type_name -> graph.substreams.data_service.common.v1.Usage
	0, // 7: graph.substreams.data_service.consumer.v1.ConsumerSidecarService.Init:input_type -> graph.substreams.data_service.consumer.v1.InitRequest
	2, // 8: graph.substreams.data_service.consumer.v1.ConsumerSidecarService.EndSession:input_type -> graph.substreams.data_service.consumer.v1.EndSessionRequest
	1, // 9: graph.substreams.data_service.consumer.v1.ConsumerSidecarService.Init:output_type -> graph.substreams.data_service.consumer.v1.InitResponse
	3, // 10: graph.substreams.data_service.consumer.v1.ConsumerSidecarService.EndSession:output_type -> graph.substreams.data_service.consumer.v1.EndSessionResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_graph_substreams_data_service_consumer_v1_consumer_proto_init() }
func file_graph_substreams_data_service_consumer_v1_consumer_proto_init() {
	if File_graph_substreams_data_service_consumer_v1_consumer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDesc), len(file_graph_substreams_data_service_consumer_v1_consumer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graph_substreams_data_service_consumer_v1_consumer_proto_goTypes,
		DependencyIndexes: file_graph_substreams_data_service_consumer_v1_consumer_proto_depIdxs,
		MessageInfos:      file_graph_substreams_data_service_consumer_v1_consumer_proto_msgTypes,
	}.Build()
	File_graph_substreams_data_service_consumer_v1_consumer_proto = out.File
	file_graph_substreams_data_service_consumer_v1_consumer_proto_goTypes = nil
	file_graph_substreams_data_service_consumer_v1_consumer_proto_depIdxs = nil
}
