// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: graph/substreams/data_service/consumer/v1/consumer.proto

package consumerv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/consumer/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConsumerSidecarServiceName is the fully-qualified name of the ConsumerSidecarService service.
	ConsumerSidecarServiceName = "graph.substreams.data_service.consumer.v1.ConsumerSidecarService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConsumerSidecarServiceInitProcedure is the fully-qualified name of the ConsumerSidecarService's
	// Init RPC.
	ConsumerSidecarServiceInitProcedure = "/graph.substreams.data_service.consumer.v1.ConsumerSidecarService/Init"
	// ConsumerSidecarServiceEndSessionProcedure is the fully-qualified name of the
	// ConsumerSidecarService's EndSession RPC.
	ConsumerSidecarServiceEndSessionProcedure = "/graph.substreams.data_service.consumer.v1.ConsumerSidecarService/EndSession"
)

// ConsumerSidecarServiceClient is a client for the
// graph.substreams.data_service.consumer.v1.ConsumerSidecarService service.
type ConsumerSidecarServiceClient interface {
	// Init initializes a new payment session with a provider.
	// Called by substreams before connecting to a provider.
	// Returns the initial RAV to use for authentication.
	Init(context.Context, *connect.Request[v1.InitRequest]) (*connect.Response[v1.InitResponse], error)
	// EndSession ends the current session and reports final usage.
	// Called by substreams when the stream ends.
	EndSession(context.Context, *connect.Request[v1.EndSessionRequest]) (*connect.Response[v1.EndSessionResponse], error)
}

// NewConsumerSidecarServiceClient constructs a client for the
// graph.substreams.data_service.consumer.v1.ConsumerSidecarService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConsumerSidecarServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConsumerSidecarServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	consumerSidecarServiceMethods := v1.File_graph_substreams_data_service_consumer_v1_consumer_proto.Services().ByName("ConsumerSidecarService").Methods()
	return &consumerSidecarServiceClient{
		init: connect.NewClient[v1.InitRequest, v1.InitResponse](
			httpClient,
			baseURL+ConsumerSidecarServiceInitProcedure,
			connect.WithSchema(consumerSidecarServiceMethods.ByName("Init")),
			connect.WithClientOptions(opts...),
		),
		endSession: connect.NewClient[v1.EndSessionRequest, v1.EndSessionResponse](
			httpClient,
			baseURL+ConsumerSidecarServiceEndSessionProcedure,
			connect.WithSchema(consumerSidecarServiceMethods.ByName("EndSession")),
			connect.WithClientOptions(opts...),
		),
	}
}

// consumerSidecarServiceClient implements ConsumerSidecarServiceClient.
type consumerSidecarServiceClient struct {
	init       *connect.Client[v1.InitRequest, v1.InitResponse]
	endSession *connect.Client[v1.EndSessionRequest, v1.EndSessionResponse]
}

// Init calls graph.substreams.data_service.consumer.v1.ConsumerSidecarService.Init.
func (c *consumerSidecarServiceClient) Init(ctx context.Context, req *connect.Request[v1.InitRequest]) (*connect.Response[v1.InitResponse], error) {
	return c.init.CallUnary(ctx, req)
}

// EndSession calls graph.substreams.data_service.consumer.v1.ConsumerSidecarService.EndSession.
func (c *consumerSidecarServiceClient) EndSession(ctx context.Context, req *connect.Request[v1.EndSessionRequest]) (*connect.Response[v1.EndSessionResponse], error) {
	return c.endSession.CallUnary(ctx, req)
}

// ConsumerSidecarServiceHandler is an implementation of the
// graph.substreams.data_service.consumer.v1.ConsumerSidecarService service.
type ConsumerSidecarServiceHandler interface {
	// Init initializes a new payment session with a provider.
	// Called by substreams before connecting to a provider.
	// Returns the initial RAV to use for authentication.
	Init(context.Context, *connect.Request[v1.InitRequest]) (*connect.Response[v1.InitResponse], error)
	// EndSession ends the current session and reports final usage.
	// Called by substreams when the stream ends.
	EndSession(context.Context, *connect.Request[v1.EndSessionRequest]) (*connect.Response[v1.EndSessionResponse], error)
}

// NewConsumerSidecarServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConsumerSidecarServiceHandler(svc ConsumerSidecarServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	consumerSidecarServiceMethods := v1.File_graph_substreams_data_service_consumer_v1_consumer_proto.Services().ByName("ConsumerSidecarService").Methods()
	consumerSidecarServiceInitHandler := connect.NewUnaryHandler(
		ConsumerSidecarServiceInitProcedure,
		svc.Init,
		connect.WithSchema(consumerSidecarServiceMethods.ByName("Init")),
		connect.WithHandlerOptions(opts...),
	)
	consumerSidecarServiceEndSessionHandler := connect.NewUnaryHandler(
		ConsumerSidecarServiceEndSessionProcedure,
		svc.EndSession,
		connect.WithSchema(consumerSidecarServiceMethods.ByName("EndSession")),
		connect.WithHandlerOptions(opts...),
	)
	return "/graph.substreams.data_service.consumer.v1.ConsumerSidecarService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConsumerSidecarServiceInitProcedure:
			consumerSidecarServiceInitHandler.ServeHTTP(w, r)
		case ConsumerSidecarServiceEndSessionProcedure:
			consumerSidecarServiceEndSessionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConsumerSidecarServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConsumerSidecarServiceHandler struct{}

func (UnimplementedConsumerSidecarServiceHandler) Init(context.Context, *connect.Request[v1.InitRequest]) (*connect.Response[v1.InitResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.consumer.v1.ConsumerSidecarService.Init is not implemented"))
}

func (UnimplementedConsumerSidecarServiceHandler) EndSession(context.Context, *connect.Request[v1.EndSessionRequest]) (*connect.Response[v1.EndSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.consumer.v1.ConsumerSidecarService.EndSession is not implemented"))
}
