// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: graph/substreams/data_service/sds/usage/v1/usage.proto

package usagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Batched metering events
	Events        []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_graph_substreams_data_service_sds_usage_v1_usage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_sds_usage_v1_usage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_sds_usage_v1_usage_proto_rawDescGZIP(), []int{0}
}

func (x *ReportRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type ReportResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the session/key has been revoked
	Revoked bool `protobuf:"varint,1,opt,name=revoked,proto3" json:"revoked,omitempty"`
	// If revoked, the reason for revocation
	RevocationReason string `protobuf:"bytes,2,opt,name=revocation_reason,json=revocationReason,proto3" json:"revocation_reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_graph_substreams_data_service_sds_usage_v1_usage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_sds_usage_v1_usage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_sds_usage_v1_usage_proto_rawDescGZIP(), []int{1}
}

func (x *ReportResponse) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *ReportResponse) GetRevocationReason() string {
	if x != nil {
		return x.RevocationReason
	}
	return ""
}

// Event represents a single metered usage event as reported by the dmetering plugin.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Payer Ethereum address (from auth context)
	OrganizationId string `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// Optional sub-key or signer identifier
	ApiKeyId string `protobuf:"bytes,2,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	// Client IP address
	IpAddress string `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// Endpoint called, e.g., "sf.substreams.rpc.v2/Blocks"
	Endpoint string `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Network identifier, e.g., "eth-mainnet"
	Network string `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	// SDS session ID from auth service (for linking usage to payment sessions)
	SdsSessionId string `protobuf:"bytes,6,opt,name=sds_session_id,json=sdsSessionId,proto3" json:"sds_session_id,omitempty"`
	// Provider Ethereum address
	Provider string `protobuf:"bytes,8,opt,name=provider,proto3" json:"provider,omitempty"`
	// Output module hash (for Substreams)
	OutputModuleHash string `protobuf:"bytes,9,opt,name=output_module_hash,json=outputModuleHash,proto3" json:"output_module_hash,omitempty"`
	// Individual metrics (blocks_count, bytes_sent, etc.)
	Metrics []*Metric `protobuf:"bytes,20,rep,name=metrics,proto3" json:"metrics,omitempty"`
	// Event timestamp
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,30,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_graph_substreams_data_service_sds_usage_v1_usage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_sds_usage_v1_usage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_sds_usage_v1_usage_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Event) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

func (x *Event) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Event) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Event) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Event) GetSdsSessionId() string {
	if x != nil {
		return x.SdsSessionId
	}
	return ""
}

func (x *Event) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Event) GetOutputModuleHash() string {
	if x != nil {
		return x.OutputModuleHash
	}
	return ""
}

func (x *Event) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Metric is a single named counter value within a usage event.
type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_graph_substreams_data_service_sds_usage_v1_usage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_sds_usage_v1_usage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_sds_usage_v1_usage_proto_rawDescGZIP(), []int{3}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_graph_substreams_data_service_sds_usage_v1_usage_proto protoreflect.FileDescriptor

const file_graph_substreams_data_service_sds_usage_v1_usage_proto_rawDesc = "" +
	"\n" +
	"6graph/substreams/data_service/sds/usage/v1/usage.proto\x12*graph.substreams.data_service.sds.usage.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"Z\n" +
	"\rReportRequest\x12I\n" +
	"\x06events\x18\x01 \x03(\v21.graph.substreams.data_service.sds.usage.v1.EventR\x06events\"W\n" +
	"\x0eReportResponse\x12\x18\n" +
	"\arevoked\x18\x01 \x01(\bR\arevoked\x12+\n" +
	"\x11revocation_reason\x18\x02 \x01(\tR\x10revocationReason\"\xa7\x03\n" +
	"\x05Event\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x02 \x01(\tR\bapiKeyId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12\x18\n" +
	"\anetwork\x18\x05 \x01(\tR\anetwork\x12$\n" +
	"\x0esds_session_id\x18\x06 \x01(\tR\fsdsSessionId\x12\x1a\n" +
	"\bprovider\x18\b \x01(\tR\bprovider\x12,\n" +
	"\x12output_module_hash\x18\t \x01(\tR\x10outputModuleHash\x12L\n" +
	"\ametrics\x18\x14 \x03(\v22.graph.substreams.data_service.sds.usage.v1.MetricR\ametrics\x128\n" +
	"\ttimestamp\x18\x1e \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampJ\x04\b\a\x10\bR\x04meta\"2\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value2\x8f\x01\n" +
	"\fUsageService\x12\x7f\n" +
	"\x06Report\x129.graph.substreams.data_service.sds.usage.v1.ReportRequest\x1a:.graph.substreams.data_service.sds.usage.v1.ReportResponseB\xef\x02\n" +
	".com.graph.substreams.data_service.sds.usage.v1B\n" +
	"UsageProtoP\x01Zfgithub.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/sds/usage/v1;usagev1\xa2\x02\x05GSDSU\xaa\x02)Graph.Substreams.DataService.Sds.Usage.V1\xca\x02)Graph\\Substreams\\DataService\\Sds\\Usage\\V1\xe2\x025Graph\\Substreams\\DataService\\Sds\\Usage\\V1\\GPBMetadata\xea\x02.Graph::Substreams::DataService::Sds::Usage::V1b\x06proto3"

var (
	file_graph_substreams_data_service_sds_usage_v1_usage_proto_rawDescOnce sync.Once
	file_graph_substreams_data_service_sds_usage_v1_usage_proto_rawDescData []byte
)

func file_graph_substreams_data_service_sds_usage_v1_usage_proto_rawDescGZIP() []byte {
	file_graph_substreams_data_service_sds_usage_v1_usage_proto_rawDescOnce.Do(func() {
		file_graph_substreams_data_service_sds_usage_v1_usage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_substreams_data_service_sds_usage_v1_usage_proto_rawDesc), len(file_graph_substreams_data_service_sds_usage_v1_usage_proto_rawDesc)))
	})
	return file_graph_substreams_data_service_sds_usage_v1_usage_proto_rawDescData
}

var file_graph_substreams_data_service_sds_usage_v1_usage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_graph_substreams_data_service_sds_usage_v1_usage_proto_goTypes = []any{
	(*ReportRequest)(nil),         // 0: graph.substreams.data_service.sds.usage.v1.ReportRequest
	(*ReportResponse)(nil),        // 1: graph.substreams.data_service.sds.usage.v1.ReportResponse
	(*Event)(nil),                 // 2: graph.substreams.data_service.sds.usage.v1.Event
	(*Metric)(nil),                // 3: graph.substreams.data_service.sds.usage.v1.Metric
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_graph_substreams_data_service_sds_usage_v1_usage_proto_depIdxs = []int32{
	2, // 0: graph.substreams.data_service.sds.usage.v1.ReportRequest.events:type_name -> graph.substreams.data_service.sds.usage.v1.Event
	3, // 1: graph.substreams.data_service.sds.usage.v1.Event.metrics:type_name -> graph.substreams.data_service.sds.usage.v1.Metric
	4, // 2: graph.substreams.data_service.sds.usage.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	0, // 3: graph.substreams.data_service.sds.usage.v1.UsageService.Report:input_type -> graph.substreams.data_service.sds.usage.v1.ReportRequest
	1, // 4: graph.substreams.data_service.sds.usage.v1.UsageService.Report:output_type -> graph.substreams.data_service.sds.usage.v1.ReportResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_graph_substreams_data_service_sds_usage_v1_usage_proto_init() }
func file_graph_substreams_data_service_sds_usage_v1_usage_proto_init() {
	if File_graph_substreams_data_service_sds_usage_v1_usage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_substreams_data_service_sds_usage_v1_usage_proto_rawDesc), len(file_graph_substreams_data_service_sds_usage_v1_usage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graph_substreams_data_service_sds_usage_v1_usage_proto_goTypes,
		DependencyIndexes: file_graph_substreams_data_service_sds_usage_v1_usage_proto_depIdxs,
		MessageInfos:      file_graph_substreams_data_service_sds_usage_v1_usage_proto_msgTypes,
	}.Build()
	File_graph_substreams_data_service_sds_usage_v1_usage_proto = out.File
	file_graph_substreams_data_service_sds_usage_v1_usage_proto_goTypes = nil
	file_graph_substreams_data_service_sds_usage_v1_usage_proto_depIdxs = nil
}
