// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: graph/substreams/data_service/sds/usage/v1/usage.proto

package usagev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/sds/usage/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UsageServiceName is the fully-qualified name of the UsageService service.
	UsageServiceName = "graph.substreams.data_service.sds.usage.v1.UsageService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UsageServiceReportProcedure is the fully-qualified name of the UsageService's Report RPC.
	UsageServiceReportProcedure = "/graph.substreams.data_service.sds.usage.v1.UsageService/Report"
)

// UsageServiceClient is a client for the graph.substreams.data_service.sds.usage.v1.UsageService
// service.
type UsageServiceClient interface {
	// Report receives a batch of metering events from the firehose-core dmetering plugin.
	Report(context.Context, *connect.Request[v1.ReportRequest]) (*connect.Response[v1.ReportResponse], error)
}

// NewUsageServiceClient constructs a client for the
// graph.substreams.data_service.sds.usage.v1.UsageService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUsageServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UsageServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	usageServiceMethods := v1.File_graph_substreams_data_service_sds_usage_v1_usage_proto.Services().ByName("UsageService").Methods()
	return &usageServiceClient{
		report: connect.NewClient[v1.ReportRequest, v1.ReportResponse](
			httpClient,
			baseURL+UsageServiceReportProcedure,
			connect.WithSchema(usageServiceMethods.ByName("Report")),
			connect.WithClientOptions(opts...),
		),
	}
}

// usageServiceClient implements UsageServiceClient.
type usageServiceClient struct {
	report *connect.Client[v1.ReportRequest, v1.ReportResponse]
}

// Report calls graph.substreams.data_service.sds.usage.v1.UsageService.Report.
func (c *usageServiceClient) Report(ctx context.Context, req *connect.Request[v1.ReportRequest]) (*connect.Response[v1.ReportResponse], error) {
	return c.report.CallUnary(ctx, req)
}

// UsageServiceHandler is an implementation of the
// graph.substreams.data_service.sds.usage.v1.UsageService service.
type UsageServiceHandler interface {
	// Report receives a batch of metering events from the firehose-core dmetering plugin.
	Report(context.Context, *connect.Request[v1.ReportRequest]) (*connect.Response[v1.ReportResponse], error)
}

// NewUsageServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUsageServiceHandler(svc UsageServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	usageServiceMethods := v1.File_graph_substreams_data_service_sds_usage_v1_usage_proto.Services().ByName("UsageService").Methods()
	usageServiceReportHandler := connect.NewUnaryHandler(
		UsageServiceReportProcedure,
		svc.Report,
		connect.WithSchema(usageServiceMethods.ByName("Report")),
		connect.WithHandlerOptions(opts...),
	)
	return "/graph.substreams.data_service.sds.usage.v1.UsageService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UsageServiceReportProcedure:
			usageServiceReportHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUsageServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUsageServiceHandler struct{}

func (UnimplementedUsageServiceHandler) Report(context.Context, *connect.Request[v1.ReportRequest]) (*connect.Response[v1.ReportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.sds.usage.v1.UsageService.Report is not implemented"))
}
