// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: graph/substreams/data_service/oracle/v1/oracle.proto

package oraclev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/oracle/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// OracleServiceName is the fully-qualified name of the OracleService service.
	OracleServiceName = "graph.substreams.data_service.oracle.v1.OracleService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OracleServiceDiscoverProvidersProcedure is the fully-qualified name of the OracleService's
	// DiscoverProviders RPC.
	OracleServiceDiscoverProvidersProcedure = "/graph.substreams.data_service.oracle.v1.OracleService/DiscoverProviders"
)

// OracleServiceClient is a client for the graph.substreams.data_service.oracle.v1.OracleService
// service.
type OracleServiceClient interface {
	DiscoverProviders(context.Context, *connect.Request[v1.DiscoverProvidersRequest]) (*connect.Response[v1.DiscoverProvidersResponse], error)
}

// NewOracleServiceClient constructs a client for the
// graph.substreams.data_service.oracle.v1.OracleService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOracleServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OracleServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	oracleServiceMethods := v1.File_graph_substreams_data_service_oracle_v1_oracle_proto.Services().ByName("OracleService").Methods()
	return &oracleServiceClient{
		discoverProviders: connect.NewClient[v1.DiscoverProvidersRequest, v1.DiscoverProvidersResponse](
			httpClient,
			baseURL+OracleServiceDiscoverProvidersProcedure,
			connect.WithSchema(oracleServiceMethods.ByName("DiscoverProviders")),
			connect.WithClientOptions(opts...),
		),
	}
}

// oracleServiceClient implements OracleServiceClient.
type oracleServiceClient struct {
	discoverProviders *connect.Client[v1.DiscoverProvidersRequest, v1.DiscoverProvidersResponse]
}

// DiscoverProviders calls graph.substreams.data_service.oracle.v1.OracleService.DiscoverProviders.
func (c *oracleServiceClient) DiscoverProviders(ctx context.Context, req *connect.Request[v1.DiscoverProvidersRequest]) (*connect.Response[v1.DiscoverProvidersResponse], error) {
	return c.discoverProviders.CallUnary(ctx, req)
}

// OracleServiceHandler is an implementation of the
// graph.substreams.data_service.oracle.v1.OracleService service.
type OracleServiceHandler interface {
	DiscoverProviders(context.Context, *connect.Request[v1.DiscoverProvidersRequest]) (*connect.Response[v1.DiscoverProvidersResponse], error)
}

// NewOracleServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOracleServiceHandler(svc OracleServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	oracleServiceMethods := v1.File_graph_substreams_data_service_oracle_v1_oracle_proto.Services().ByName("OracleService").Methods()
	oracleServiceDiscoverProvidersHandler := connect.NewUnaryHandler(
		OracleServiceDiscoverProvidersProcedure,
		svc.DiscoverProviders,
		connect.WithSchema(oracleServiceMethods.ByName("DiscoverProviders")),
		connect.WithHandlerOptions(opts...),
	)
	return "/graph.substreams.data_service.oracle.v1.OracleService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OracleServiceDiscoverProvidersProcedure:
			oracleServiceDiscoverProvidersHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOracleServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOracleServiceHandler struct{}

func (UnimplementedOracleServiceHandler) DiscoverProviders(context.Context, *connect.Request[v1.DiscoverProvidersRequest]) (*connect.Response[v1.DiscoverProvidersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.oracle.v1.OracleService.DiscoverProviders is not implemented"))
}
