// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: graph/substreams/data_service/sds/auth/v1/auth.proto

package authv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/sds/auth/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "graph.substreams.data_service.sds.auth.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceValidateAuthProcedure is the fully-qualified name of the AuthService's ValidateAuth
	// RPC.
	AuthServiceValidateAuthProcedure = "/graph.substreams.data_service.sds.auth.v1.AuthService/ValidateAuth"
)

// AuthServiceClient is a client for the graph.substreams.data_service.sds.auth.v1.AuthService
// service.
type AuthServiceClient interface {
	// ValidateAuth validates authentication and returns trusted headers.
	// Called by the sds:// dauth plugin for every authenticated request.
	// The plugin forwards raw headers, path, and IP - this service extracts
	// and validates the RAV, session ID, and any other auth context.
	ValidateAuth(context.Context, *connect.Request[v1.ValidateAuthRequest]) (*connect.Response[v1.ValidateAuthResponse], error)
}

// NewAuthServiceClient constructs a client for the
// graph.substreams.data_service.sds.auth.v1.AuthService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v1.File_graph_substreams_data_service_sds_auth_v1_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		validateAuth: connect.NewClient[v1.ValidateAuthRequest, v1.ValidateAuthResponse](
			httpClient,
			baseURL+AuthServiceValidateAuthProcedure,
			connect.WithSchema(authServiceMethods.ByName("ValidateAuth")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	validateAuth *connect.Client[v1.ValidateAuthRequest, v1.ValidateAuthResponse]
}

// ValidateAuth calls graph.substreams.data_service.sds.auth.v1.AuthService.ValidateAuth.
func (c *authServiceClient) ValidateAuth(ctx context.Context, req *connect.Request[v1.ValidateAuthRequest]) (*connect.Response[v1.ValidateAuthResponse], error) {
	return c.validateAuth.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the
// graph.substreams.data_service.sds.auth.v1.AuthService service.
type AuthServiceHandler interface {
	// ValidateAuth validates authentication and returns trusted headers.
	// Called by the sds:// dauth plugin for every authenticated request.
	// The plugin forwards raw headers, path, and IP - this service extracts
	// and validates the RAV, session ID, and any other auth context.
	ValidateAuth(context.Context, *connect.Request[v1.ValidateAuthRequest]) (*connect.Response[v1.ValidateAuthResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v1.File_graph_substreams_data_service_sds_auth_v1_auth_proto.Services().ByName("AuthService").Methods()
	authServiceValidateAuthHandler := connect.NewUnaryHandler(
		AuthServiceValidateAuthProcedure,
		svc.ValidateAuth,
		connect.WithSchema(authServiceMethods.ByName("ValidateAuth")),
		connect.WithHandlerOptions(opts...),
	)
	return "/graph.substreams.data_service.sds.auth.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceValidateAuthProcedure:
			authServiceValidateAuthHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) ValidateAuth(context.Context, *connect.Request[v1.ValidateAuthRequest]) (*connect.Response[v1.ValidateAuthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.sds.auth.v1.AuthService.ValidateAuth is not implemented"))
}
