#!/usr/bin/env bash

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

main() {
  set -e

  exec go run ./cmd/sds \
    sink \
    --consumer-sidecar-addr=http://localhost:9002 \
    --payer-address=0xe90874856c339d5d3733c92ea5acadc6014b34d5 \
    --receiver-address=0xa6f1845e54b1d6a95319251f1ca775b4ad406cdf \
    --data-service-address=0x37478fd2f5845e3664fe4155d74c00e1a4e7a5e2 \
    --endpoint=localhost:10016 --insecure \
    --provider-control-plane-endpoint="http://localhost:9001" \
    "$@"
}

main "$@"
