// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: graph/substreams/data_service/sds/auth/v1/auth.proto

package authv1

import (
	_ "github.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Header value(s) for a single header name
type HeaderValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderValues) Reset() {
	*x = HeaderValues{}
	mi := &file_graph_substreams_data_service_sds_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderValues) ProtoMessage() {}

func (x *HeaderValues) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_sds_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderValues.ProtoReflect.Descriptor instead.
func (*HeaderValues) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *HeaderValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type ValidateAuthRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Untrusted headers from the incoming request.
	//
	// These headers come directly from the client and MUST NOT be trusted.
	// The service will extract x-sds-rav, x-sds-session-id, and any other
	// auth-related headers from this map and validate them before trusting any values.
	//
	// SECURITY: Never use these headers directly without validation. Always extract
	// and validate before using in any security-sensitive context.
	UntrustedHeaders map[string]*HeaderValues `protobuf:"bytes,1,rep,name=untrusted_headers,json=untrustedHeaders,proto3" json:"untrusted_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Request path/endpoint (e.g., "/sf.substreams.rpc.v2.Stream/Blocks")
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Client IP address (for logging/rate-limiting)
	IpAddress     string `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAuthRequest) Reset() {
	*x = ValidateAuthRequest{}
	mi := &file_graph_substreams_data_service_sds_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAuthRequest) ProtoMessage() {}

func (x *ValidateAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_sds_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAuthRequest.ProtoReflect.Descriptor instead.
func (*ValidateAuthRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateAuthRequest) GetUntrustedHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.UntrustedHeaders
	}
	return nil
}

func (x *ValidateAuthRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ValidateAuthRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type ValidateAuthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Trusted headers to inject into the request context.
	// The dauth plugin will add these as trusted headers that cannot be
	// spoofed by the client. Common headers include:
	//   - x-user-id / x-organization-id: Payer address
	//   - x-api-key-id: Optional API key identifier
	//   - x-sds-session-id: Session ID
	//   - x-real-ip: Client IP address
	TrustedHeaders map[string]string `protobuf:"bytes,1,rep,name=trusted_headers,json=trustedHeaders,proto3" json:"trusted_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidateAuthResponse) Reset() {
	*x = ValidateAuthResponse{}
	mi := &file_graph_substreams_data_service_sds_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAuthResponse) ProtoMessage() {}

func (x *ValidateAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_sds_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAuthResponse.ProtoReflect.Descriptor instead.
func (*ValidateAuthResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateAuthResponse) GetTrustedHeaders() map[string]string {
	if x != nil {
		return x.TrustedHeaders
	}
	return nil
}

var File_graph_substreams_data_service_sds_auth_v1_auth_proto protoreflect.FileDescriptor

const file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"4graph/substreams/data_service/sds/auth/v1/auth.proto\x12)graph.substreams.data_service.sds.auth.v1\x1a3graph/substreams/data_service/common/v1/types.proto\"&\n" +
	"\fHeaderValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xca\x02\n" +
	"\x13ValidateAuthRequest\x12\x81\x01\n" +
	"\x11untrusted_headers\x18\x01 \x03(\v2T.graph.substreams.data_service.sds.auth.v1.ValidateAuthRequest.UntrustedHeadersEntryR\x10untrustedHeaders\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x1a|\n" +
	"\x15UntrustedHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12M\n" +
	"\x05value\x18\x02 \x01(\v27.graph.substreams.data_service.sds.auth.v1.HeaderValuesR\x05value:\x028\x01\"\xd7\x01\n" +
	"\x14ValidateAuthResponse\x12|\n" +
	"\x0ftrusted_headers\x18\x01 \x03(\v2S.graph.substreams.data_service.sds.auth.v1.ValidateAuthResponse.TrustedHeadersEntryR\x0etrustedHeaders\x1aA\n" +
	"\x13TrustedHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x9f\x01\n" +
	"\vAuthService\x12\x8f\x01\n" +
	"\fValidateAuth\x12>.graph.substreams.data_service.sds.auth.v1.ValidateAuthRequest\x1a?.graph.substreams.data_service.sds.auth.v1.ValidateAuthResponseB\xe7\x02\n" +
	"-com.graph.substreams.data_service.sds.auth.v1B\tAuthProtoP\x01Zdgithub.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/sds/auth/v1;authv1\xa2\x02\x05GSDSA\xaa\x02(Graph.Substreams.DataService.Sds.Auth.V1\xca\x02(Graph\\Substreams\\DataService\\Sds\\Auth\\V1\xe2\x024Graph\\Substreams\\DataService\\Sds\\Auth\\V1\\GPBMetadata\xea\x02-Graph::Substreams::DataService::Sds::Auth::V1b\x06proto3"

var (
	file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDescOnce sync.Once
	file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDescData []byte
)

func file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDesc), len(file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDesc)))
	})
	return file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDescData
}

var file_graph_substreams_data_service_sds_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_graph_substreams_data_service_sds_auth_v1_auth_proto_goTypes = []any{
	(*HeaderValues)(nil),         // 0: graph.substreams.data_service.sds.auth.v1.HeaderValues
	(*ValidateAuthRequest)(nil),  // 1: graph.substreams.data_service.sds.auth.v1.ValidateAuthRequest
	(*ValidateAuthResponse)(nil), // 2: graph.substreams.data_service.sds.auth.v1.ValidateAuthResponse
	nil,                          // 3: graph.substreams.data_service.sds.auth.v1.ValidateAuthRequest.UntrustedHeadersEntry
	nil,                          // 4: graph.substreams.data_service.sds.auth.v1.ValidateAuthResponse.TrustedHeadersEntry
}
var file_graph_substreams_data_service_sds_auth_v1_auth_proto_depIdxs = []int32{
	3, // 0: graph.substreams.data_service.sds.auth.v1.ValidateAuthRequest.untrusted_headers:type_name -> graph.substreams.data_service.sds.auth.v1.ValidateAuthRequest.UntrustedHeadersEntry
	4, // 1: graph.substreams.data_service.sds.auth.v1.ValidateAuthResponse.trusted_headers:type_name -> graph.substreams.data_service.sds.auth.v1.ValidateAuthResponse.TrustedHeadersEntry
	0, // 2: graph.substreams.data_service.sds.auth.v1.ValidateAuthRequest.UntrustedHeadersEntry.value:type_name -> graph.substreams.data_service.sds.auth.v1.HeaderValues
	1, // 3: graph.substreams.data_service.sds.auth.v1.AuthService.ValidateAuth:input_type -> graph.substreams.data_service.sds.auth.v1.ValidateAuthRequest
	2, // 4: graph.substreams.data_service.sds.auth.v1.AuthService.ValidateAuth:output_type -> graph.substreams.data_service.sds.auth.v1.ValidateAuthResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_graph_substreams_data_service_sds_auth_v1_auth_proto_init() }
func file_graph_substreams_data_service_sds_auth_v1_auth_proto_init() {
	if File_graph_substreams_data_service_sds_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDesc), len(file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graph_substreams_data_service_sds_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_graph_substreams_data_service_sds_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_graph_substreams_data_service_sds_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_graph_substreams_data_service_sds_auth_v1_auth_proto = out.File
	file_graph_substreams_data_service_sds_auth_v1_auth_proto_goTypes = nil
	file_graph_substreams_data_service_sds_auth_v1_auth_proto_depIdxs = nil
}
