// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: graph/substreams/data_service/sds/auth/v1/auth.proto

package authv1

import (
	v1 "github.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateAuthRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SignedRAV extracted from the `x-sds-rav` gRPC header
	PaymentRav *v1.SignedRAV `protobuf:"bytes,1,opt,name=payment_rav,json=paymentRav,proto3" json:"payment_rav,omitempty"`
	// Client IP address (optional, for logging/rate-limiting)
	IpAddress string `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// Request path/endpoint (optional)
	Path          string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAuthRequest) Reset() {
	*x = ValidateAuthRequest{}
	mi := &file_graph_substreams_data_service_sds_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAuthRequest) ProtoMessage() {}

func (x *ValidateAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_sds_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAuthRequest.ProtoReflect.Descriptor instead.
func (*ValidateAuthRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateAuthRequest) GetPaymentRav() *v1.SignedRAV {
	if x != nil {
		return x.PaymentRav
	}
	return nil
}

func (x *ValidateAuthRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *ValidateAuthRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ValidateAuthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Payer Ethereum address (0x...) → maps to x-user-id / x-organization-id
	OrganizationId string `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// Optional identifier for sub-key or signer; empty for now
	ApiKeyId string `protobuf:"bytes,2,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	// Additional context to pass through as trusted headers
	Metadata      map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAuthResponse) Reset() {
	*x = ValidateAuthResponse{}
	mi := &file_graph_substreams_data_service_sds_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAuthResponse) ProtoMessage() {}

func (x *ValidateAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_sds_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAuthResponse.ProtoReflect.Descriptor instead.
func (*ValidateAuthResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateAuthResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ValidateAuthResponse) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

func (x *ValidateAuthResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_graph_substreams_data_service_sds_auth_v1_auth_proto protoreflect.FileDescriptor

const file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"4graph/substreams/data_service/sds/auth/v1/auth.proto\x12)graph.substreams.data_service.sds.auth.v1\x1a3graph/substreams/data_service/common/v1/types.proto\"\x9d\x01\n" +
	"\x13ValidateAuthRequest\x12S\n" +
	"\vpayment_rav\x18\x01 \x01(\v22.graph.substreams.data_service.common.v1.SignedRAVR\n" +
	"paymentRav\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"\x85\x02\n" +
	"\x14ValidateAuthResponse\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x02 \x01(\tR\bapiKeyId\x12i\n" +
	"\bmetadata\x18\x03 \x03(\v2M.graph.substreams.data_service.sds.auth.v1.ValidateAuthResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x9f\x01\n" +
	"\vAuthService\x12\x8f\x01\n" +
	"\fValidateAuth\x12>.graph.substreams.data_service.sds.auth.v1.ValidateAuthRequest\x1a?.graph.substreams.data_service.sds.auth.v1.ValidateAuthResponseB\xe7\x02\n" +
	"-com.graph.substreams.data_service.sds.auth.v1B\tAuthProtoP\x01Zdgithub.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/sds/auth/v1;authv1\xa2\x02\x05GSDSA\xaa\x02(Graph.Substreams.DataService.Sds.Auth.V1\xca\x02(Graph\\Substreams\\DataService\\Sds\\Auth\\V1\xe2\x024Graph\\Substreams\\DataService\\Sds\\Auth\\V1\\GPBMetadata\xea\x02-Graph::Substreams::DataService::Sds::Auth::V1b\x06proto3"

var (
	file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDescOnce sync.Once
	file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDescData []byte
)

func file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDesc), len(file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDesc)))
	})
	return file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDescData
}

var file_graph_substreams_data_service_sds_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_graph_substreams_data_service_sds_auth_v1_auth_proto_goTypes = []any{
	(*ValidateAuthRequest)(nil),  // 0: graph.substreams.data_service.sds.auth.v1.ValidateAuthRequest
	(*ValidateAuthResponse)(nil), // 1: graph.substreams.data_service.sds.auth.v1.ValidateAuthResponse
	nil,                          // 2: graph.substreams.data_service.sds.auth.v1.ValidateAuthResponse.MetadataEntry
	(*v1.SignedRAV)(nil),         // 3: graph.substreams.data_service.common.v1.SignedRAV
}
var file_graph_substreams_data_service_sds_auth_v1_auth_proto_depIdxs = []int32{
	3, // 0: graph.substreams.data_service.sds.auth.v1.ValidateAuthRequest.payment_rav:type_name -> graph.substreams.data_service.common.v1.SignedRAV
	2, // 1: graph.substreams.data_service.sds.auth.v1.ValidateAuthResponse.metadata:type_name -> graph.substreams.data_service.sds.auth.v1.ValidateAuthResponse.MetadataEntry
	0, // 2: graph.substreams.data_service.sds.auth.v1.AuthService.ValidateAuth:input_type -> graph.substreams.data_service.sds.auth.v1.ValidateAuthRequest
	1, // 3: graph.substreams.data_service.sds.auth.v1.AuthService.ValidateAuth:output_type -> graph.substreams.data_service.sds.auth.v1.ValidateAuthResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_graph_substreams_data_service_sds_auth_v1_auth_proto_init() }
func file_graph_substreams_data_service_sds_auth_v1_auth_proto_init() {
	if File_graph_substreams_data_service_sds_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDesc), len(file_graph_substreams_data_service_sds_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graph_substreams_data_service_sds_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_graph_substreams_data_service_sds_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_graph_substreams_data_service_sds_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_graph_substreams_data_service_sds_auth_v1_auth_proto = out.File
	file_graph_substreams_data_service_sds_auth_v1_auth_proto_goTypes = nil
	file_graph_substreams_data_service_sds_auth_v1_auth_proto_depIdxs = nil
}
