// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: graph/substreams/data_service/oracle/v1/oracle.proto

package oraclev1

import (
	v1 "github.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiscoverProvidersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Canonical Graph network key. The oracle performs exact matching only.
	Network       string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverProvidersRequest) Reset() {
	*x = DiscoverProvidersRequest{}
	mi := &file_graph_substreams_data_service_oracle_v1_oracle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverProvidersRequest) ProtoMessage() {}

func (x *DiscoverProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_oracle_v1_oracle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverProvidersRequest.ProtoReflect.Descriptor instead.
func (*DiscoverProvidersRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_oracle_v1_oracle_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoverProvidersRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type EligibleProvider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable provider identifier from oracle configuration.
	ProviderId string `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	// Service provider address for the provider.
	ServiceProvider *v1.Address `protobuf:"bytes,2,opt,name=service_provider,json=serviceProvider,proto3" json:"service_provider,omitempty"`
	// Provider control-plane endpoint used for session initialization.
	ControlPlaneEndpoint string `protobuf:"bytes,3,opt,name=control_plane_endpoint,json=controlPlaneEndpoint,proto3" json:"control_plane_endpoint,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EligibleProvider) Reset() {
	*x = EligibleProvider{}
	mi := &file_graph_substreams_data_service_oracle_v1_oracle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EligibleProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EligibleProvider) ProtoMessage() {}

func (x *EligibleProvider) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_oracle_v1_oracle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EligibleProvider.ProtoReflect.Descriptor instead.
func (*EligibleProvider) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_oracle_v1_oracle_proto_rawDescGZIP(), []int{1}
}

func (x *EligibleProvider) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *EligibleProvider) GetServiceProvider() *v1.Address {
	if x != nil {
		return x.ServiceProvider
	}
	return nil
}

func (x *EligibleProvider) GetControlPlaneEndpoint() string {
	if x != nil {
		return x.ControlPlaneEndpoint
	}
	return ""
}

type DiscoverProvidersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Canonical network key used for this discovery result.
	Network string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	// Canonical oracle-authoritative pricing for the network.
	CanonicalPricing *v1.PricingConfig `protobuf:"bytes,2,opt,name=canonical_pricing,json=canonicalPricing,proto3" json:"canonical_pricing,omitempty"`
	// All providers eligible for the requested network.
	EligibleProviders []*EligibleProvider `protobuf:"bytes,3,rep,name=eligible_providers,json=eligibleProviders,proto3" json:"eligible_providers,omitempty"`
	// Provider ID chosen as the oracle recommendation.
	RecommendedProviderId string `protobuf:"bytes,4,opt,name=recommended_provider_id,json=recommendedProviderId,proto3" json:"recommended_provider_id,omitempty"`
	// Full selected provider details for the recommended provider.
	SelectedProvider *EligibleProvider `protobuf:"bytes,5,opt,name=selected_provider,json=selectedProvider,proto3" json:"selected_provider,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DiscoverProvidersResponse) Reset() {
	*x = DiscoverProvidersResponse{}
	mi := &file_graph_substreams_data_service_oracle_v1_oracle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverProvidersResponse) ProtoMessage() {}

func (x *DiscoverProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_oracle_v1_oracle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverProvidersResponse.ProtoReflect.Descriptor instead.
func (*DiscoverProvidersResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_oracle_v1_oracle_proto_rawDescGZIP(), []int{2}
}

func (x *DiscoverProvidersResponse) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *DiscoverProvidersResponse) GetCanonicalPricing() *v1.PricingConfig {
	if x != nil {
		return x.CanonicalPricing
	}
	return nil
}

func (x *DiscoverProvidersResponse) GetEligibleProviders() []*EligibleProvider {
	if x != nil {
		return x.EligibleProviders
	}
	return nil
}

func (x *DiscoverProvidersResponse) GetRecommendedProviderId() string {
	if x != nil {
		return x.RecommendedProviderId
	}
	return ""
}

func (x *DiscoverProvidersResponse) GetSelectedProvider() *EligibleProvider {
	if x != nil {
		return x.SelectedProvider
	}
	return nil
}

var File_graph_substreams_data_service_oracle_v1_oracle_proto protoreflect.FileDescriptor

const file_graph_substreams_data_service_oracle_v1_oracle_proto_rawDesc = "" +
	"\n" +
	"4graph/substreams/data_service/oracle/v1/oracle.proto\x12'graph.substreams.data_service.oracle.v1\x1a3graph/substreams/data_service/common/v1/types.proto\"4\n" +
	"\x18DiscoverProvidersRequest\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\"\xc6\x01\n" +
	"\x10EligibleProvider\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12[\n" +
	"\x10service_provider\x18\x02 \x01(\v20.graph.substreams.data_service.common.v1.AddressR\x0fserviceProvider\x124\n" +
	"\x16control_plane_endpoint\x18\x03 \x01(\tR\x14controlPlaneEndpoint\"\xa4\x03\n" +
	"\x19DiscoverProvidersResponse\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12c\n" +
	"\x11canonical_pricing\x18\x02 \x01(\v26.graph.substreams.data_service.common.v1.PricingConfigR\x10canonicalPricing\x12h\n" +
	"\x12eligible_providers\x18\x03 \x03(\v29.graph.substreams.data_service.oracle.v1.EligibleProviderR\x11eligibleProviders\x126\n" +
	"\x17recommended_provider_id\x18\x04 \x01(\tR\x15recommendedProviderId\x12f\n" +
	"\x11selected_provider\x18\x05 \x01(\v29.graph.substreams.data_service.oracle.v1.EligibleProviderR\x10selectedProvider2\xac\x01\n" +
	"\rOracleService\x12\x9a\x01\n" +
	"\x11DiscoverProviders\x12A.graph.substreams.data_service.oracle.v1.DiscoverProvidersRequest\x1aB.graph.substreams.data_service.oracle.v1.DiscoverProvidersResponseB\xdd\x02\n" +
	"+com.graph.substreams.data_service.oracle.v1B\vOracleProtoP\x01Zdgithub.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/oracle/v1;oraclev1\xa2\x02\x04GSDO\xaa\x02&Graph.Substreams.DataService.Oracle.V1\xca\x02&Graph\\Substreams\\DataService\\Oracle\\V1\xe2\x022Graph\\Substreams\\DataService\\Oracle\\V1\\GPBMetadata\xea\x02*Graph::Substreams::DataService::Oracle::V1b\x06proto3"

var (
	file_graph_substreams_data_service_oracle_v1_oracle_proto_rawDescOnce sync.Once
	file_graph_substreams_data_service_oracle_v1_oracle_proto_rawDescData []byte
)

func file_graph_substreams_data_service_oracle_v1_oracle_proto_rawDescGZIP() []byte {
	file_graph_substreams_data_service_oracle_v1_oracle_proto_rawDescOnce.Do(func() {
		file_graph_substreams_data_service_oracle_v1_oracle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_substreams_data_service_oracle_v1_oracle_proto_rawDesc), len(file_graph_substreams_data_service_oracle_v1_oracle_proto_rawDesc)))
	})
	return file_graph_substreams_data_service_oracle_v1_oracle_proto_rawDescData
}

var file_graph_substreams_data_service_oracle_v1_oracle_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_graph_substreams_data_service_oracle_v1_oracle_proto_goTypes = []any{
	(*DiscoverProvidersRequest)(nil),  // 0: graph.substreams.data_service.oracle.v1.DiscoverProvidersRequest
	(*EligibleProvider)(nil),          // 1: graph.substreams.data_service.oracle.v1.EligibleProvider
	(*DiscoverProvidersResponse)(nil), // 2: graph.substreams.data_service.oracle.v1.DiscoverProvidersResponse
	(*v1.Address)(nil),                // 3: graph.substreams.data_service.common.v1.Address
	(*v1.PricingConfig)(nil),          // 4: graph.substreams.data_service.common.v1.PricingConfig
}
var file_graph_substreams_data_service_oracle_v1_oracle_proto_depIdxs = []int32{
	3, // 0: graph.substreams.data_service.oracle.v1.EligibleProvider.service_provider:type_name -> graph.substreams.data_service.common.v1.Address
	4, // 1: graph.substreams.data_service.oracle.v1.DiscoverProvidersResponse.canonical_pricing:type_name -> graph.substreams.data_service.common.v1.PricingConfig
	1, // 2: graph.substreams.data_service.oracle.v1.DiscoverProvidersResponse.eligible_providers:type_name -> graph.substreams.data_service.oracle.v1.EligibleProvider
	1, // 3: graph.substreams.data_service.oracle.v1.DiscoverProvidersResponse.selected_provider:type_name -> graph.substreams.data_service.oracle.v1.EligibleProvider
	0, // 4: graph.substreams.data_service.oracle.v1.OracleService.DiscoverProviders:input_type -> graph.substreams.data_service.oracle.v1.DiscoverProvidersRequest
	2, // 5: graph.substreams.data_service.oracle.v1.OracleService.DiscoverProviders:output_type -> graph.substreams.data_service.oracle.v1.DiscoverProvidersResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_graph_substreams_data_service_oracle_v1_oracle_proto_init() }
func file_graph_substreams_data_service_oracle_v1_oracle_proto_init() {
	if File_graph_substreams_data_service_oracle_v1_oracle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_substreams_data_service_oracle_v1_oracle_proto_rawDesc), len(file_graph_substreams_data_service_oracle_v1_oracle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graph_substreams_data_service_oracle_v1_oracle_proto_goTypes,
		DependencyIndexes: file_graph_substreams_data_service_oracle_v1_oracle_proto_depIdxs,
		MessageInfos:      file_graph_substreams_data_service_oracle_v1_oracle_proto_msgTypes,
	}.Build()
	File_graph_substreams_data_service_oracle_v1_oracle_proto = out.File
	file_graph_substreams_data_service_oracle_v1_oracle_proto_goTypes = nil
	file_graph_substreams_data_service_oracle_v1_oracle_proto_depIdxs = nil
}
